/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.model;



public class SickHistoryReal {
    private String account_state;
    private Long amount;
    private Long credit;
    private String date;
    private Long debit;
    private String description;
    private Long id;
    private String receipt_id;
    private String sick_id;
    
    
    public String getAccount_state() {
        return this.account_state;
    }
    
    public void setAccount_state(String account_state) {
        this.account_state = account_state;
    }
    
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }
    
    public Long getCredit() {
        return this.credit;
    }
    
    public void setCredit(Long credit) {
        this.credit = credit;
    }
    
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    
    public Long getDebit() {
        return this.debit;
    }
    
    public void setDebit(Long debit) {
        this.debit = debit;
    }
    
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getReceipt_id() {
        return this.receipt_id;
    }
    
    public void setReceipt_id(String receipt_id) {
        this.receipt_id = receipt_id;
    }
    
    public String getSick_id() {
        return this.sick_id;
    }
    
    public void setSick_id(String sick_id) {
        this.sick_id = sick_id;
    }
}
