/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.Account;


public interface AccountRepository {
    Account findByUsername(String username, List<String> fields_to_ignore, Connection con);
    
    Account findByUsername(String username, Connection con);
    
    Account findByUsername(String username, List<String> fields_to_ignore);
    
    Account findByUsername(String username);
    
    Account insert(Account account, Connection con);
    
    Account insert(Account account);
    
    Account update(Account account, boolean exclude_nulls, Connection con);
    
    Account update(Account account, boolean exclude_nulls);
    
    Account save(Account account, Connection con);
    
    Account save(Account account);
    
    List<Account> findAll(List<String> fields_to_ignore, Connection con);
    
    List<Account> findAll(Connection con);
    
    List<Account> findAll(List<String> fields_to_ignore);
    
    List<Account> findAll();
    
    List<Account> findByModel(Account account, List<String> fields_to_ignore, Connection con);
    
    List<Account> findByModel(Account account, Connection con);
    
    List<Account> findByModel(Account account, List<String> fields_to_ignore);
    
    List<Account> findByModel(Account account);
    
    void delete(String username, Connection con);
    
    void delete(String username);
    
    void deleteByModel(Account account, Connection con);
    
    void deleteByModel(Account account);
}
