/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.ClinicInfo;


public interface ClinicInfoRepository {
    ClinicInfo findByName(String name, List<String> fields_to_ignore, Connection con);
    
    ClinicInfo findByName(String name, Connection con);
    
    ClinicInfo findByName(String name, List<String> fields_to_ignore);
    
    ClinicInfo findByName(String name);
    
    ClinicInfo insert(ClinicInfo clinicInfo, Connection con);
    
    ClinicInfo insert(ClinicInfo clinicInfo);
    
    ClinicInfo update(ClinicInfo clinicInfo, boolean exclude_nulls, Connection con);
    
    ClinicInfo update(ClinicInfo clinicInfo, boolean exclude_nulls);
    
    ClinicInfo save(ClinicInfo clinicInfo, Connection con);
    
    ClinicInfo save(ClinicInfo clinicInfo);
    
    List<ClinicInfo> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ClinicInfo> findAll(Connection con);
    
    List<ClinicInfo> findAll(List<String> fields_to_ignore);
    
    List<ClinicInfo> findAll();
    
    List<ClinicInfo> findByModel(ClinicInfo clinicInfo, List<String> fields_to_ignore, Connection con);
    
    List<ClinicInfo> findByModel(ClinicInfo clinicInfo, Connection con);
    
    List<ClinicInfo> findByModel(ClinicInfo clinicInfo, List<String> fields_to_ignore);
    
    List<ClinicInfo> findByModel(ClinicInfo clinicInfo);
    
    void delete(String name, Connection con);
    
    void delete(String name);
    
    void deleteByModel(ClinicInfo clinicInfo, Connection con);
    
    void deleteByModel(ClinicInfo clinicInfo);
}
