/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.DepotReal;
import com.arc.utility.Sql2oUtility;


@Repository
public class DepotRealRepositoryImpl implements DepotRealRepository {
    private final static Logger logger = LoggerFactory.getLogger(DepotRealRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DRUG_NAME")) {
            res += "d.DRUG_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("FEE")) {
            res += "d.FEE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("REMAINED")) {
            res += "d.REMAINED, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("UNIT")) {
            res += "d.UNIT, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public DepotReal findByDrug_name(String drug_name, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByDrug_name() - drug_name: " + drug_name);
        
        String sql = "select " + DepotRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from DEPOT_REAL d ";
        sql += "where "; 
        sql += "DRUG_NAME = :drug_name ";
        
        DepotReal res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("drug_name", drug_name);

            res = query.executeAndFetchFirst(DepotReal.class);
        }
        
        logger.debug("<< DB getByDrug_name() - END");
        return res;
    }
    
    @Override
    public DepotReal findByDrug_name(String drug_name, Connection con) {
        return this.findByDrug_name(drug_name, null, con);
    }
    
    @Override
    public DepotReal findByDrug_name(String drug_name, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByDrug_name(drug_name, fields_to_ignore, con);
        }
    }
    
    @Override
    public DepotReal findByDrug_name(String drug_name) {
        return this.findByDrug_name(drug_name, (List<String>) null);
    }
    
    @Override
    public List<DepotReal> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + DepotRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from DEPOT_REAL d ";
        
        List<DepotReal> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(DepotReal.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<DepotReal> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<DepotReal> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<DepotReal> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<DepotReal> findByModel(DepotReal depotReal, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + DepotRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from DEPOT_REAL d ";
        sql += "where ";
        
        if (depotReal.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (depotReal.getFee() != null) { 
            sql += "FEE = :fee and ";
        }
        
        if (depotReal.getRemained() != null) { 
            sql += "REMAINED = :remained and ";
        }
        
        if (depotReal.getUnit() != null) { 
            sql += "UNIT = :unit and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<DepotReal> res;
        
        try (Query query = con.createQuery(sql)) {
            if (depotReal.getDrug_name() != null) {
                query.addParameter("drug_name", depotReal.getDrug_name());
            }
            
            if (depotReal.getFee() != null) {
                query.addParameter("fee", depotReal.getFee());
            }
            
            if (depotReal.getRemained() != null) {
                query.addParameter("remained", depotReal.getRemained());
            }
            
            if (depotReal.getUnit() != null) {
                query.addParameter("unit", depotReal.getUnit());
            }
            
            res = query.executeAndFetch(DepotReal.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<DepotReal> findByModel(DepotReal depotReal, Connection con) {
        return this.findByModel(depotReal, null, con);
    }
    
    @Override
    public List<DepotReal> findByModel(DepotReal depotReal, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(depotReal, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<DepotReal> findByModel(DepotReal depotReal) {
        return this.findByModel(depotReal, (List<String>) null);
    }
    
    @Override
    public DepotReal insert(DepotReal depotReal, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into DEPOT_REAL ( " + 
                "DRUG_NAME, " + 
                "FEE, " + 
                "REMAINED, " + 
                "UNIT " + 
            ") " + 
            "values (" +
                ":drug_name, " + 
                ":fee, " + 
                ":remained, " + 
                ":unit " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(depotReal);

            key = query.executeUpdate().getKey();
        }
        
        final String res = Sql2oUtility.getInsertedId("DEPOT_REAL", "DRUG_NAME", con, key, String.class);
        depotReal.setDrug_name(res);
        logger.info("<< DB insert() - END");
        return depotReal;
    }
    
    @Override
    public DepotReal insert(DepotReal depotReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(depotReal, con);
            con.commit();
            return depotReal;
        }
    }
    
    @Override
    public DepotReal update(DepotReal depotReal, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - drug_name: " + depotReal.getDrug_name());
        
        String sql = "update DEPOT_REAL set ";
        
        if (! exclude_nulls || depotReal.getFee() != null) { 
            sql += "FEE = :fee, ";
        }
        
        if (! exclude_nulls || depotReal.getRemained() != null) { 
            sql += "REMAINED = :remained, ";
        }
        
        if (! exclude_nulls || depotReal.getUnit() != null) { 
            sql += "UNIT = :unit, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || depotReal.getDrug_name() != null) {
                query.addParameter("drug_name", depotReal.getDrug_name());
            }
            
            if (! exclude_nulls || depotReal.getFee() != null) {
                query.addParameter("fee", depotReal.getFee());
            }
            
            if (! exclude_nulls || depotReal.getRemained() != null) {
                query.addParameter("remained", depotReal.getRemained());
            }
            
            if (! exclude_nulls || depotReal.getUnit() != null) {
                query.addParameter("unit", depotReal.getUnit());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return depotReal;
    }
    
    @Override
    public DepotReal update(DepotReal depotReal, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(depotReal, exclude_nulls, con);
            con.commit();
            return depotReal;
        }
    }
    
    @Override
    public DepotReal save(DepotReal depotReal, Connection con) {
        final String drug_name = depotReal.getDrug_name();

        final DepotReal depotReal2 = this.findByDrug_name(drug_name, null, con);
        
        if (depotReal2 == null) {
            return this.insert(depotReal, con);
        }
        return this.update(depotReal, false, con);
    }
    
    @Override
    public DepotReal save(DepotReal depotReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(depotReal, con);
            con.commit();
            return depotReal;
        }
    }
    
    @Override
    public void delete(String drug_name, Connection con) {
        logger.info("DB>> delete() - drug_name: " + drug_name);
        
        String sql = "delete from DEPOT_REAL ";
        sql += "where "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("drug_name", drug_name);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(String drug_name) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(drug_name, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(DepotReal depotReal, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from DEPOT_REAL ";
        sql += "where ";
        
        if (depotReal.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (depotReal.getFee() != null) { 
            sql += "FEE = :fee and ";
        }
        
        if (depotReal.getRemained() != null) { 
            sql += "REMAINED = :remained and ";
        }
        
        if (depotReal.getUnit() != null) { 
            sql += "UNIT = :unit and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (depotReal.getDrug_name() != null) {
                query.addParameter("drug_name", depotReal.getDrug_name());
            }
            
            if (depotReal.getFee() != null) {
                query.addParameter("fee", depotReal.getFee());
            }
            
            if (depotReal.getRemained() != null) {
                query.addParameter("remained", depotReal.getRemained());
            }
            
            if (depotReal.getUnit() != null) {
                query.addParameter("unit", depotReal.getUnit());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(DepotReal depotReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(depotReal, con);
            con.commit();
        }
    }
}
