/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.DispensedItem;
import com.arc.utility.Sql2oUtility;


@Repository
public class DispensedItemRepositoryImpl implements DispensedItemRepository {
    private final static Logger logger = LoggerFactory.getLogger(DispensedItemRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COUNT")) {
            res += "d.COUNT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DISPENSE_DATE")) {
            res += "d.DISPENSE_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DISPENSE_DAY")) {
            res += "d.DISPENSE_DAY, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DRUG_NAME")) {
            res += "d.DRUG_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("FROM_DATE")) {
            res += "d.FROM_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "d.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "d.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "d.SICK_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TO_DATE")) {
            res += "d.TO_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_METHOD")) {
            res += "d.TREATMENT_METHOD, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public DispensedItem findByIds(Long id, String drug_name, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByIds() - id: " + id + "drug_name: " + drug_name);
        
        String sql = "select " + DispensedItemRepositoryImpl.getSelectBase(fields_to_ignore) + "from DISPENSED_ITEMS d ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "DRUG_NAME = :drug_name ";
        
        DispensedItem res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);
            query.addParameter("drug_name", drug_name);

            res = query.executeAndFetchFirst(DispensedItem.class);
        }
        
        logger.debug("<< DB getByIds() - END");
        return res;
    }
    
    @Override
    public DispensedItem findByIds(Long id, String drug_name, Connection con) {
        return this.findByIds(id, drug_name, null, con);
    }
    
    @Override
    public DispensedItem findByIds(Long id, String drug_name, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByIds(id, drug_name, fields_to_ignore, con);
        }
    }
    
    @Override
    public DispensedItem findByIds(Long id, String drug_name) {
        return this.findByIds(id, drug_name, (List<String>) null);
    }
    
    @Override
    public List<DispensedItem> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + DispensedItemRepositoryImpl.getSelectBase(fields_to_ignore) + "from DISPENSED_ITEMS d ";
        
        List<DispensedItem> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(DispensedItem.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<DispensedItem> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<DispensedItem> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<DispensedItem> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<DispensedItem> findByModel(DispensedItem dispensedItem, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + DispensedItemRepositoryImpl.getSelectBase(fields_to_ignore) + "from DISPENSED_ITEMS d ";
        sql += "where ";
        
        if (dispensedItem.getCount() != null) { 
            sql += "COUNT = :count and ";
        }
        
        if (dispensedItem.getDispense_date() != null) { 
            sql += "DISPENSE_DATE = :dispense_date and ";
        }
        
        if (dispensedItem.getDispense_day() != null) { 
            sql += "DISPENSE_DAY = :dispense_day and ";
        }
        
        if (dispensedItem.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (dispensedItem.getFrom_date() != null) { 
            sql += "FROM_DATE = :from_date and ";
        }
        
        if (dispensedItem.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (dispensedItem.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (dispensedItem.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (dispensedItem.getTo_date() != null) { 
            sql += "TO_DATE = :to_date and ";
        }
        
        if (dispensedItem.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<DispensedItem> res;
        
        try (Query query = con.createQuery(sql)) {
            if (dispensedItem.getCount() != null) {
                query.addParameter("count", dispensedItem.getCount());
            }
            
            if (dispensedItem.getDispense_date() != null) {
                query.addParameter("dispense_date", dispensedItem.getDispense_date());
            }
            
            if (dispensedItem.getDispense_day() != null) {
                query.addParameter("dispense_day", dispensedItem.getDispense_day());
            }
            
            if (dispensedItem.getDrug_name() != null) {
                query.addParameter("drug_name", dispensedItem.getDrug_name());
            }
            
            if (dispensedItem.getFrom_date() != null) {
                query.addParameter("from_date", dispensedItem.getFrom_date());
            }
            
            if (dispensedItem.getId() != null) {
                query.addParameter("id", dispensedItem.getId());
            }
            
            if (dispensedItem.getSick_id() != null) {
                query.addParameter("sick_id", dispensedItem.getSick_id());
            }
            
            if (dispensedItem.getSick_name() != null) {
                query.addParameter("sick_name", dispensedItem.getSick_name());
            }
            
            if (dispensedItem.getTo_date() != null) {
                query.addParameter("to_date", dispensedItem.getTo_date());
            }
            
            if (dispensedItem.getTreatment_method() != null) {
                query.addParameter("treatment_method", dispensedItem.getTreatment_method());
            }
            
            res = query.executeAndFetch(DispensedItem.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<DispensedItem> findByModel(DispensedItem dispensedItem, Connection con) {
        return this.findByModel(dispensedItem, null, con);
    }
    
    @Override
    public List<DispensedItem> findByModel(DispensedItem dispensedItem, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(dispensedItem, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<DispensedItem> findByModel(DispensedItem dispensedItem) {
        return this.findByModel(dispensedItem, (List<String>) null);
    }
    
    @Override
    public DispensedItem insert(DispensedItem dispensedItem, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into DISPENSED_ITEMS ( " + 
                "COUNT, " + 
                "DISPENSE_DATE, " + 
                "DISPENSE_DAY, " + 
                "DRUG_NAME, " + 
                "FROM_DATE, " + 
                "ID, " + 
                "SICK_ID, " + 
                "SICK_NAME, " + 
                "TO_DATE, " + 
                "TREATMENT_METHOD " + 
            ") " + 
            "values (" +
                ":count, " + 
                ":dispense_date, " + 
                ":dispense_day, " + 
                ":drug_name, " + 
                ":from_date, " + 
                ":id, " + 
                ":sick_id, " + 
                ":sick_name, " + 
                ":to_date, " + 
                ":treatment_method " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(dispensedItem);

            key = query.executeUpdate().getKey();
        }
        

        logger.info("<< DB insert() - END");
        return dispensedItem;
    }
    
    @Override
    public DispensedItem insert(DispensedItem dispensedItem) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(dispensedItem, con);
            con.commit();
            return dispensedItem;
        }
    }
    
    @Override
    public DispensedItem update(DispensedItem dispensedItem, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + dispensedItem.getId() + "drug_name: " + dispensedItem.getDrug_name());
        
        String sql = "update DISPENSED_ITEMS set ";
        
        if (! exclude_nulls || dispensedItem.getCount() != null) { 
            sql += "COUNT = :count, ";
        }
        
        if (! exclude_nulls || dispensedItem.getDispense_date() != null) { 
            sql += "DISPENSE_DATE = :dispense_date, ";
        }
        
        if (! exclude_nulls || dispensedItem.getDispense_day() != null) { 
            sql += "DISPENSE_DAY = :dispense_day, ";
        }
        
        if (! exclude_nulls || dispensedItem.getFrom_date() != null) { 
            sql += "FROM_DATE = :from_date, ";
        }
        
        if (! exclude_nulls || dispensedItem.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || dispensedItem.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        if (! exclude_nulls || dispensedItem.getTo_date() != null) { 
            sql += "TO_DATE = :to_date, ";
        }
        
        if (! exclude_nulls || dispensedItem.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || dispensedItem.getCount() != null) {
                query.addParameter("count", dispensedItem.getCount());
            }
            
            if (! exclude_nulls || dispensedItem.getDispense_date() != null) {
                query.addParameter("dispense_date", dispensedItem.getDispense_date());
            }
            
            if (! exclude_nulls || dispensedItem.getDispense_day() != null) {
                query.addParameter("dispense_day", dispensedItem.getDispense_day());
            }
            
            if (! exclude_nulls || dispensedItem.getDrug_name() != null) {
                query.addParameter("drug_name", dispensedItem.getDrug_name());
            }
            
            if (! exclude_nulls || dispensedItem.getFrom_date() != null) {
                query.addParameter("from_date", dispensedItem.getFrom_date());
            }
            
            if (! exclude_nulls || dispensedItem.getId() != null) {
                query.addParameter("id", dispensedItem.getId());
            }
            
            if (! exclude_nulls || dispensedItem.getSick_id() != null) {
                query.addParameter("sick_id", dispensedItem.getSick_id());
            }
            
            if (! exclude_nulls || dispensedItem.getSick_name() != null) {
                query.addParameter("sick_name", dispensedItem.getSick_name());
            }
            
            if (! exclude_nulls || dispensedItem.getTo_date() != null) {
                query.addParameter("to_date", dispensedItem.getTo_date());
            }
            
            if (! exclude_nulls || dispensedItem.getTreatment_method() != null) {
                query.addParameter("treatment_method", dispensedItem.getTreatment_method());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return dispensedItem;
    }
    
    @Override
    public DispensedItem update(DispensedItem dispensedItem, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(dispensedItem, exclude_nulls, con);
            con.commit();
            return dispensedItem;
        }
    }
    
    @Override
    public DispensedItem save(DispensedItem dispensedItem, Connection con) {
        final Long id = dispensedItem.getId();
        final String drug_name = dispensedItem.getDrug_name();

        final DispensedItem dispensedItem2 = this.findByIds(id, drug_name, null, con);
        
        if (dispensedItem2 == null) {
            return this.insert(dispensedItem, con);
        }
        return this.update(dispensedItem, false, con);
    }
    
    @Override
    public DispensedItem save(DispensedItem dispensedItem) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(dispensedItem, con);
            con.commit();
            return dispensedItem;
        }
    }
    
    @Override
    public void delete(Long id, String drug_name, Connection con) {
        logger.info("DB>> delete() - id: " + id + "drug_name: " + drug_name);
        
        String sql = "delete from DISPENSED_ITEMS ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);
            query.addParameter("drug_name", drug_name);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id, String drug_name) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, drug_name, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(DispensedItem dispensedItem, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from DISPENSED_ITEMS ";
        sql += "where ";
        
        if (dispensedItem.getCount() != null) { 
            sql += "COUNT = :count and ";
        }
        
        if (dispensedItem.getDispense_date() != null) { 
            sql += "DISPENSE_DATE = :dispense_date and ";
        }
        
        if (dispensedItem.getDispense_day() != null) { 
            sql += "DISPENSE_DAY = :dispense_day and ";
        }
        
        if (dispensedItem.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (dispensedItem.getFrom_date() != null) { 
            sql += "FROM_DATE = :from_date and ";
        }
        
        if (dispensedItem.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (dispensedItem.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (dispensedItem.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (dispensedItem.getTo_date() != null) { 
            sql += "TO_DATE = :to_date and ";
        }
        
        if (dispensedItem.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (dispensedItem.getCount() != null) {
                query.addParameter("count", dispensedItem.getCount());
            }
            
            if (dispensedItem.getDispense_date() != null) {
                query.addParameter("dispense_date", dispensedItem.getDispense_date());
            }
            
            if (dispensedItem.getDispense_day() != null) {
                query.addParameter("dispense_day", dispensedItem.getDispense_day());
            }
            
            if (dispensedItem.getDrug_name() != null) {
                query.addParameter("drug_name", dispensedItem.getDrug_name());
            }
            
            if (dispensedItem.getFrom_date() != null) {
                query.addParameter("from_date", dispensedItem.getFrom_date());
            }
            
            if (dispensedItem.getId() != null) {
                query.addParameter("id", dispensedItem.getId());
            }
            
            if (dispensedItem.getSick_id() != null) {
                query.addParameter("sick_id", dispensedItem.getSick_id());
            }
            
            if (dispensedItem.getSick_name() != null) {
                query.addParameter("sick_name", dispensedItem.getSick_name());
            }
            
            if (dispensedItem.getTo_date() != null) {
                query.addParameter("to_date", dispensedItem.getTo_date());
            }
            
            if (dispensedItem.getTreatment_method() != null) {
                query.addParameter("treatment_method", dispensedItem.getTreatment_method());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(DispensedItem dispensedItem) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(dispensedItem, con);
            con.commit();
        }
    }
}
