/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.Promotions;


public interface PromotionsRepository {
    Promotions findById(Long id, List<String> fields_to_ignore, Connection con);
    
    Promotions findById(Long id, Connection con);
    
    Promotions findById(Long id, List<String> fields_to_ignore);
    
    Promotions findById(Long id);
    
    Promotions insert(Promotions promotions, Connection con);
    
    Promotions insert(Promotions promotions);
    
    Promotions update(Promotions promotions, boolean exclude_nulls, Connection con);
    
    Promotions update(Promotions promotions, boolean exclude_nulls);
    
    Promotions save(Promotions promotions, Connection con);
    
    Promotions save(Promotions promotions);
    
    List<Promotions> findAll(List<String> fields_to_ignore, Connection con);
    
    List<Promotions> findAll(Connection con);
    
    List<Promotions> findAll(List<String> fields_to_ignore);
    
    List<Promotions> findAll();
    
    List<Promotions> findByModel(Promotions promotions, List<String> fields_to_ignore, Connection con);
    
    List<Promotions> findByModel(Promotions promotions, Connection con);
    
    List<Promotions> findByModel(Promotions promotions, List<String> fields_to_ignore);
    
    List<Promotions> findByModel(Promotions promotions);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(Promotions promotions, Connection con);
    
    void deleteByModel(Promotions promotions);
}
