/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.RecordSnapshots;
import com.arc.utility.Sql2oUtility;


@Repository
public class RecordSnapshotsRepositoryImpl implements RecordSnapshotsRepository {
    private final static Logger logger = LoggerFactory.getLogger(RecordSnapshotsRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CURRENT_TOTAL")) {
            res += "r.CURRENT_TOTAL, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CURRENT_TOTAL_ALL")) {
            res += "r.CURRENT_TOTAL_ALL, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CURRENT_TOTAL_NURSE")) {
            res += "r.CURRENT_TOTAL_NURSE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CURRENT_TOTAL_REAL")) {
            res += "r.CURRENT_TOTAL_REAL, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "r.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DIFFERENCES")) {
            res += "r.DIFFERENCES, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DRUG_NAME")) {
            res += "r.DRUG_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("EMPTY_CASE")) {
            res += "r.EMPTY_CASE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "r.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("LAST_TOTAL_ON_DATE")) {
            res += "r.LAST_TOTAL_ON_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("LAST_TOTAL_ON_DATE_REAL")) {
            res += "r.LAST_TOTAL_ON_DATE_REAL, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("REG_DATE")) {
            res += "r.REG_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TOTAL_USED")) {
            res += "r.TOTAL_USED, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TOTAL_USED_REAL")) {
            res += "r.TOTAL_USED_REAL, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public RecordSnapshots findById(Integer id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + RecordSnapshotsRepositoryImpl.getSelectBase(fields_to_ignore) + "from RECORDS_SNAPSHOTS r ";
        sql += "where "; 
        sql += "ID = :id ";
        
        RecordSnapshots res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(RecordSnapshots.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public RecordSnapshots findById(Integer id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public RecordSnapshots findById(Integer id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public RecordSnapshots findById(Integer id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<RecordSnapshots> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + RecordSnapshotsRepositoryImpl.getSelectBase(fields_to_ignore) + "from RECORDS_SNAPSHOTS r ";
        
        List<RecordSnapshots> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(RecordSnapshots.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<RecordSnapshots> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<RecordSnapshots> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<RecordSnapshots> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + RecordSnapshotsRepositoryImpl.getSelectBase(fields_to_ignore) + "from RECORDS_SNAPSHOTS r ";
        sql += "where ";
        
        if (recordSnapshots.getCurrent_total() != null) { 
            sql += "CURRENT_TOTAL = :current_total and ";
        }
        
        if (recordSnapshots.getCurrent_total_all() != null) { 
            sql += "CURRENT_TOTAL_ALL = :current_total_all and ";
        }
        
        if (recordSnapshots.getCurrent_total_nurse() != null) { 
            sql += "CURRENT_TOTAL_NURSE = :current_total_nurse and ";
        }
        
        if (recordSnapshots.getCurrent_total_real() != null) { 
            sql += "CURRENT_TOTAL_REAL = :current_total_real and ";
        }
        
        if (recordSnapshots.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (recordSnapshots.getDifferences() != null) { 
            sql += "DIFFERENCES = :differences and ";
        }
        
        if (recordSnapshots.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (recordSnapshots.getEmpty_case() != null) { 
            sql += "EMPTY_CASE = :empty_case and ";
        }
        
        if (recordSnapshots.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (recordSnapshots.getLast_total_on_date() != null) { 
            sql += "LAST_TOTAL_ON_DATE = :last_total_on_date and ";
        }
        
        if (recordSnapshots.getLast_total_on_date_real() != null) { 
            sql += "LAST_TOTAL_ON_DATE_REAL = :last_total_on_date_real and ";
        }
        
        if (recordSnapshots.getReg_date() != null) { 
            sql += "REG_DATE = :reg_date and ";
        }
        
        if (recordSnapshots.getTotal_used() != null) { 
            sql += "TOTAL_USED = :total_used and ";
        }
        
        if (recordSnapshots.getTotal_used_real() != null) { 
            sql += "TOTAL_USED_REAL = :total_used_real and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<RecordSnapshots> res;
        
        try (Query query = con.createQuery(sql)) {
            if (recordSnapshots.getCurrent_total() != null) {
                query.addParameter("current_total", recordSnapshots.getCurrent_total());
            }
            
            if (recordSnapshots.getCurrent_total_all() != null) {
                query.addParameter("current_total_all", recordSnapshots.getCurrent_total_all());
            }
            
            if (recordSnapshots.getCurrent_total_nurse() != null) {
                query.addParameter("current_total_nurse", recordSnapshots.getCurrent_total_nurse());
            }
            
            if (recordSnapshots.getCurrent_total_real() != null) {
                query.addParameter("current_total_real", recordSnapshots.getCurrent_total_real());
            }
            
            if (recordSnapshots.getDate() != null) {
                query.addParameter("date", recordSnapshots.getDate());
            }
            
            if (recordSnapshots.getDifferences() != null) {
                query.addParameter("differences", recordSnapshots.getDifferences());
            }
            
            if (recordSnapshots.getDrug_name() != null) {
                query.addParameter("drug_name", recordSnapshots.getDrug_name());
            }
            
            if (recordSnapshots.getEmpty_case() != null) {
                query.addParameter("empty_case", recordSnapshots.getEmpty_case());
            }
            
            if (recordSnapshots.getId() != null) {
                query.addParameter("id", recordSnapshots.getId());
            }
            
            if (recordSnapshots.getLast_total_on_date() != null) {
                query.addParameter("last_total_on_date", recordSnapshots.getLast_total_on_date());
            }
            
            if (recordSnapshots.getLast_total_on_date_real() != null) {
                query.addParameter("last_total_on_date_real", recordSnapshots.getLast_total_on_date_real());
            }
            
            if (recordSnapshots.getReg_date() != null) {
                query.addParameter("reg_date", recordSnapshots.getReg_date());
            }
            
            if (recordSnapshots.getTotal_used() != null) {
                query.addParameter("total_used", recordSnapshots.getTotal_used());
            }
            
            if (recordSnapshots.getTotal_used_real() != null) {
                query.addParameter("total_used_real", recordSnapshots.getTotal_used_real());
            }
            
            res = query.executeAndFetch(RecordSnapshots.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots, Connection con) {
        return this.findByModel(recordSnapshots, null, con);
    }
    
    @Override
    public List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(recordSnapshots, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots) {
        return this.findByModel(recordSnapshots, (List<String>) null);
    }
    
    @Override
    public RecordSnapshots insert(RecordSnapshots recordSnapshots, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into RECORDS_SNAPSHOTS ( " + 
                "CURRENT_TOTAL, " + 
                "CURRENT_TOTAL_ALL, " + 
                "CURRENT_TOTAL_NURSE, " + 
                "CURRENT_TOTAL_REAL, " + 
                "DATE, " + 
                "DIFFERENCES, " + 
                "DRUG_NAME, " + 
                "EMPTY_CASE, " + 
                "ID, " + 
                "LAST_TOTAL_ON_DATE, " + 
                "LAST_TOTAL_ON_DATE_REAL, " + 
                "REG_DATE, " + 
                "TOTAL_USED, " + 
                "TOTAL_USED_REAL " + 
            ") " + 
            "values (" +
                ":current_total, " + 
                ":current_total_all, " + 
                ":current_total_nurse, " + 
                ":current_total_real, " + 
                ":date, " + 
                ":differences, " + 
                ":drug_name, " + 
                ":empty_case, " + 
                ":id, " + 
                ":last_total_on_date, " + 
                ":last_total_on_date_real, " + 
                ":reg_date, " + 
                ":total_used, " + 
                ":total_used_real " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(recordSnapshots);

            key = query.executeUpdate().getKey();
        }
        
        final Integer res = Sql2oUtility.getInsertedId("RECORDS_SNAPSHOTS", "ID", con, key, Integer.class);
        recordSnapshots.setId(res);
        logger.info("<< DB insert() - END");
        return recordSnapshots;
    }
    
    @Override
    public RecordSnapshots insert(RecordSnapshots recordSnapshots) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(recordSnapshots, con);
            con.commit();
            return recordSnapshots;
        }
    }
    
    @Override
    public RecordSnapshots update(RecordSnapshots recordSnapshots, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + recordSnapshots.getId());
        
        String sql = "update RECORDS_SNAPSHOTS set ";
        
        if (! exclude_nulls || recordSnapshots.getCurrent_total() != null) { 
            sql += "CURRENT_TOTAL = :current_total, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getCurrent_total_all() != null) { 
            sql += "CURRENT_TOTAL_ALL = :current_total_all, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getCurrent_total_nurse() != null) { 
            sql += "CURRENT_TOTAL_NURSE = :current_total_nurse, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getCurrent_total_real() != null) { 
            sql += "CURRENT_TOTAL_REAL = :current_total_real, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getDifferences() != null) { 
            sql += "DIFFERENCES = :differences, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getEmpty_case() != null) { 
            sql += "EMPTY_CASE = :empty_case, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getLast_total_on_date() != null) { 
            sql += "LAST_TOTAL_ON_DATE = :last_total_on_date, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getLast_total_on_date_real() != null) { 
            sql += "LAST_TOTAL_ON_DATE_REAL = :last_total_on_date_real, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getReg_date() != null) { 
            sql += "REG_DATE = :reg_date, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getTotal_used() != null) { 
            sql += "TOTAL_USED = :total_used, ";
        }
        
        if (! exclude_nulls || recordSnapshots.getTotal_used_real() != null) { 
            sql += "TOTAL_USED_REAL = :total_used_real, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || recordSnapshots.getCurrent_total() != null) {
                query.addParameter("current_total", recordSnapshots.getCurrent_total());
            }
            
            if (! exclude_nulls || recordSnapshots.getCurrent_total_all() != null) {
                query.addParameter("current_total_all", recordSnapshots.getCurrent_total_all());
            }
            
            if (! exclude_nulls || recordSnapshots.getCurrent_total_nurse() != null) {
                query.addParameter("current_total_nurse", recordSnapshots.getCurrent_total_nurse());
            }
            
            if (! exclude_nulls || recordSnapshots.getCurrent_total_real() != null) {
                query.addParameter("current_total_real", recordSnapshots.getCurrent_total_real());
            }
            
            if (! exclude_nulls || recordSnapshots.getDate() != null) {
                query.addParameter("date", recordSnapshots.getDate());
            }
            
            if (! exclude_nulls || recordSnapshots.getDifferences() != null) {
                query.addParameter("differences", recordSnapshots.getDifferences());
            }
            
            if (! exclude_nulls || recordSnapshots.getDrug_name() != null) {
                query.addParameter("drug_name", recordSnapshots.getDrug_name());
            }
            
            if (! exclude_nulls || recordSnapshots.getEmpty_case() != null) {
                query.addParameter("empty_case", recordSnapshots.getEmpty_case());
            }
            
            if (! exclude_nulls || recordSnapshots.getId() != null) {
                query.addParameter("id", recordSnapshots.getId());
            }
            
            if (! exclude_nulls || recordSnapshots.getLast_total_on_date() != null) {
                query.addParameter("last_total_on_date", recordSnapshots.getLast_total_on_date());
            }
            
            if (! exclude_nulls || recordSnapshots.getLast_total_on_date_real() != null) {
                query.addParameter("last_total_on_date_real", recordSnapshots.getLast_total_on_date_real());
            }
            
            if (! exclude_nulls || recordSnapshots.getReg_date() != null) {
                query.addParameter("reg_date", recordSnapshots.getReg_date());
            }
            
            if (! exclude_nulls || recordSnapshots.getTotal_used() != null) {
                query.addParameter("total_used", recordSnapshots.getTotal_used());
            }
            
            if (! exclude_nulls || recordSnapshots.getTotal_used_real() != null) {
                query.addParameter("total_used_real", recordSnapshots.getTotal_used_real());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return recordSnapshots;
    }
    
    @Override
    public RecordSnapshots update(RecordSnapshots recordSnapshots, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(recordSnapshots, exclude_nulls, con);
            con.commit();
            return recordSnapshots;
        }
    }
    
    @Override
    public RecordSnapshots save(RecordSnapshots recordSnapshots, Connection con) {
        final Integer id = recordSnapshots.getId();

        final RecordSnapshots recordSnapshots2 = this.findById(id, null, con);
        
        if (recordSnapshots2 == null) {
            return this.insert(recordSnapshots, con);
        }
        return this.update(recordSnapshots, false, con);
    }
    
    @Override
    public RecordSnapshots save(RecordSnapshots recordSnapshots) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(recordSnapshots, con);
            con.commit();
            return recordSnapshots;
        }
    }
    
    @Override
    public void delete(Integer id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from RECORDS_SNAPSHOTS ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Integer id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(RecordSnapshots recordSnapshots, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from RECORDS_SNAPSHOTS ";
        sql += "where ";
        
        if (recordSnapshots.getCurrent_total() != null) { 
            sql += "CURRENT_TOTAL = :current_total and ";
        }
        
        if (recordSnapshots.getCurrent_total_all() != null) { 
            sql += "CURRENT_TOTAL_ALL = :current_total_all and ";
        }
        
        if (recordSnapshots.getCurrent_total_nurse() != null) { 
            sql += "CURRENT_TOTAL_NURSE = :current_total_nurse and ";
        }
        
        if (recordSnapshots.getCurrent_total_real() != null) { 
            sql += "CURRENT_TOTAL_REAL = :current_total_real and ";
        }
        
        if (recordSnapshots.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (recordSnapshots.getDifferences() != null) { 
            sql += "DIFFERENCES = :differences and ";
        }
        
        if (recordSnapshots.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (recordSnapshots.getEmpty_case() != null) { 
            sql += "EMPTY_CASE = :empty_case and ";
        }
        
        if (recordSnapshots.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (recordSnapshots.getLast_total_on_date() != null) { 
            sql += "LAST_TOTAL_ON_DATE = :last_total_on_date and ";
        }
        
        if (recordSnapshots.getLast_total_on_date_real() != null) { 
            sql += "LAST_TOTAL_ON_DATE_REAL = :last_total_on_date_real and ";
        }
        
        if (recordSnapshots.getReg_date() != null) { 
            sql += "REG_DATE = :reg_date and ";
        }
        
        if (recordSnapshots.getTotal_used() != null) { 
            sql += "TOTAL_USED = :total_used and ";
        }
        
        if (recordSnapshots.getTotal_used_real() != null) { 
            sql += "TOTAL_USED_REAL = :total_used_real and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (recordSnapshots.getCurrent_total() != null) {
                query.addParameter("current_total", recordSnapshots.getCurrent_total());
            }
            
            if (recordSnapshots.getCurrent_total_all() != null) {
                query.addParameter("current_total_all", recordSnapshots.getCurrent_total_all());
            }
            
            if (recordSnapshots.getCurrent_total_nurse() != null) {
                query.addParameter("current_total_nurse", recordSnapshots.getCurrent_total_nurse());
            }
            
            if (recordSnapshots.getCurrent_total_real() != null) {
                query.addParameter("current_total_real", recordSnapshots.getCurrent_total_real());
            }
            
            if (recordSnapshots.getDate() != null) {
                query.addParameter("date", recordSnapshots.getDate());
            }
            
            if (recordSnapshots.getDifferences() != null) {
                query.addParameter("differences", recordSnapshots.getDifferences());
            }
            
            if (recordSnapshots.getDrug_name() != null) {
                query.addParameter("drug_name", recordSnapshots.getDrug_name());
            }
            
            if (recordSnapshots.getEmpty_case() != null) {
                query.addParameter("empty_case", recordSnapshots.getEmpty_case());
            }
            
            if (recordSnapshots.getId() != null) {
                query.addParameter("id", recordSnapshots.getId());
            }
            
            if (recordSnapshots.getLast_total_on_date() != null) {
                query.addParameter("last_total_on_date", recordSnapshots.getLast_total_on_date());
            }
            
            if (recordSnapshots.getLast_total_on_date_real() != null) {
                query.addParameter("last_total_on_date_real", recordSnapshots.getLast_total_on_date_real());
            }
            
            if (recordSnapshots.getReg_date() != null) {
                query.addParameter("reg_date", recordSnapshots.getReg_date());
            }
            
            if (recordSnapshots.getTotal_used() != null) {
                query.addParameter("total_used", recordSnapshots.getTotal_used());
            }
            
            if (recordSnapshots.getTotal_used_real() != null) {
                query.addParameter("total_used_real", recordSnapshots.getTotal_used_real());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(RecordSnapshots recordSnapshots) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(recordSnapshots, con);
            con.commit();
        }
    }
}
