/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.SickHistory;


public interface SickHistoryRepository {
    SickHistory findByIds(Long id, String sick_id, List<String> fields_to_ignore, Connection con);
    
    SickHistory findByIds(Long id, String sick_id, Connection con);
    
    SickHistory findByIds(Long id, String sick_id, List<String> fields_to_ignore);
    
    SickHistory findByIds(Long id, String sick_id);
    
    SickHistory insert(SickHistory sickHistory, Connection con);
    
    SickHistory insert(SickHistory sickHistory);
    
    SickHistory update(SickHistory sickHistory, boolean exclude_nulls, Connection con);
    
    SickHistory update(SickHistory sickHistory, boolean exclude_nulls);
    
    SickHistory save(SickHistory sickHistory, Connection con);
    
    SickHistory save(SickHistory sickHistory);
    
    List<SickHistory> findAll(List<String> fields_to_ignore, Connection con);
    
    List<SickHistory> findAll(Connection con);
    
    List<SickHistory> findAll(List<String> fields_to_ignore);
    
    List<SickHistory> findAll();
    
    List<SickHistory> findByModel(SickHistory sickHistory, List<String> fields_to_ignore, Connection con);
    
    List<SickHistory> findByModel(SickHistory sickHistory, Connection con);
    
    List<SickHistory> findByModel(SickHistory sickHistory, List<String> fields_to_ignore);
    
    List<SickHistory> findByModel(SickHistory sickHistory);
    
    void delete(Long id, String sick_id, Connection con);
    
    void delete(Long id, String sick_id);
    
    void deleteByModel(SickHistory sickHistory, Connection con);
    
    void deleteByModel(SickHistory sickHistory);
}
