/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.Sick;


public interface SickRepository {
    Sick findById(String id, List<String> fields_to_ignore, Connection con);
    
    Sick findById(String id, Connection con);
    
    Sick findById(String id, List<String> fields_to_ignore);
    
    Sick findById(String id);
    
    Sick insert(Sick sick, Connection con);
    
    Sick insert(Sick sick);
    
    Sick update(Sick sick, boolean exclude_nulls, Connection con);
    
    Sick update(Sick sick, boolean exclude_nulls);
    
    Sick save(Sick sick, Connection con);
    
    Sick save(Sick sick);
    
    List<Sick> findAll(List<String> fields_to_ignore, Connection con);
    
    List<Sick> findAll(Connection con);
    
    List<Sick> findAll(List<String> fields_to_ignore);
    
    List<Sick> findAll();
    
    List<Sick> findByModel(Sick sick, List<String> fields_to_ignore, Connection con);
    
    List<Sick> findByModel(Sick sick, Connection con);
    
    List<Sick> findByModel(Sick sick, List<String> fields_to_ignore);
    
    List<Sick> findByModel(Sick sick);
    
    void delete(String id, Connection con);
    
    void delete(String id);
    
    void deleteByModel(Sick sick, Connection con);
    
    void deleteByModel(Sick sick);
}
