/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.Sick;
import com.arc.utility.Sql2oUtility;


@Repository
public class SickRepositoryImpl implements SickRepository {
    private final static Logger logger = LoggerFactory.getLogger(SickRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ACOUNT_STATE")) {
            res += "s.ACOUNT_STATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ADDRESS")) {
            res += "s.ADDRESS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("AMOUNT")) {
            res += "s.AMOUNT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("BIRTH_DATE")) {
            res += "s.BIRTH_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CITY")) {
            res += "s.CITY, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DAILY")) {
            res += "s.DAILY, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("END_DATE")) {
            res += "s.END_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("FATHER_NAME")) {
            res += "s.FATHER_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("HOME")) {
            res += "s.HOME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "s.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID_NO")) {
            res += "s.ID_NO, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("MOBILE")) {
            res += "s.MOBILE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("MONTHLY_FEE")) {
            res += "s.MONTHLY_FEE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("NAME")) {
            res += "s.NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SEX")) {
            res += "s.SEX, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_DATE")) {
            res += "s.TREATMENT_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_METHOD")) {
            res += "s.TREATMENT_METHOD, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("USAGE_TYPE")) {
            res += "s.USAGE_TYPE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public Sick findById(String id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + SickRepositoryImpl.getSelectBase(fields_to_ignore) + "from SICKS s ";
        sql += "where "; 
        sql += "ID = :id ";
        
        Sick res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(Sick.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public Sick findById(String id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public Sick findById(String id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public Sick findById(String id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<Sick> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + SickRepositoryImpl.getSelectBase(fields_to_ignore) + "from SICKS s ";
        
        List<Sick> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(Sick.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<Sick> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<Sick> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Sick> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<Sick> findByModel(Sick sick, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + SickRepositoryImpl.getSelectBase(fields_to_ignore) + "from SICKS s ";
        sql += "where ";
        
        if (sick.getAcount_state() != null) { 
            sql += "ACOUNT_STATE = :acount_state and ";
        }
        
        if (sick.getAddress() != null) { 
            sql += "ADDRESS = :address and ";
        }
        
        if (sick.getAmount() != null) { 
            sql += "AMOUNT = :amount and ";
        }
        
        if (sick.getBirth_date() != null) { 
            sql += "BIRTH_DATE = :birth_date and ";
        }
        
        if (sick.getCity() != null) { 
            sql += "CITY = :city and ";
        }
        
        if (sick.getDaily() != null) { 
            sql += "DAILY = :daily and ";
        }
        
        if (sick.getEnd_date() != null) { 
            sql += "END_DATE = :end_date and ";
        }
        
        if (sick.getFather_name() != null) { 
            sql += "FATHER_NAME = :father_name and ";
        }
        
        if (sick.getHome() != null) { 
            sql += "HOME = :home and ";
        }
        
        if (sick.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (sick.getId_no() != null) { 
            sql += "ID_NO = :id_no and ";
        }
        
        if (sick.getMobile() != null) { 
            sql += "MOBILE = :mobile and ";
        }
        
        if (sick.getMonthly_fee() != null) { 
            sql += "MONTHLY_FEE = :monthly_fee and ";
        }
        
        if (sick.getName() != null) { 
            sql += "NAME = :name and ";
        }
        
        if (sick.getSex() != null) { 
            sql += "SEX = :sex and ";
        }
        
        if (sick.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        if (sick.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method and ";
        }
        
        if (sick.getUsage_type() != null) { 
            sql += "USAGE_TYPE = :usage_type and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<Sick> res;
        
        try (Query query = con.createQuery(sql)) {
            if (sick.getAcount_state() != null) {
                query.addParameter("acount_state", sick.getAcount_state());
            }
            
            if (sick.getAddress() != null) {
                query.addParameter("address", sick.getAddress());
            }
            
            if (sick.getAmount() != null) {
                query.addParameter("amount", sick.getAmount());
            }
            
            if (sick.getBirth_date() != null) {
                query.addParameter("birth_date", sick.getBirth_date());
            }
            
            if (sick.getCity() != null) {
                query.addParameter("city", sick.getCity());
            }
            
            if (sick.getDaily() != null) {
                query.addParameter("daily", sick.getDaily());
            }
            
            if (sick.getEnd_date() != null) {
                query.addParameter("end_date", sick.getEnd_date());
            }
            
            if (sick.getFather_name() != null) {
                query.addParameter("father_name", sick.getFather_name());
            }
            
            if (sick.getHome() != null) {
                query.addParameter("home", sick.getHome());
            }
            
            if (sick.getId() != null) {
                query.addParameter("id", sick.getId());
            }
            
            if (sick.getId_no() != null) {
                query.addParameter("id_no", sick.getId_no());
            }
            
            if (sick.getMobile() != null) {
                query.addParameter("mobile", sick.getMobile());
            }
            
            if (sick.getMonthly_fee() != null) {
                query.addParameter("monthly_fee", sick.getMonthly_fee());
            }
            
            if (sick.getName() != null) {
                query.addParameter("name", sick.getName());
            }
            
            if (sick.getSex() != null) {
                query.addParameter("sex", sick.getSex());
            }
            
            if (sick.getTreatment_date() != null) {
                query.addParameter("treatment_date", sick.getTreatment_date());
            }
            
            if (sick.getTreatment_method() != null) {
                query.addParameter("treatment_method", sick.getTreatment_method());
            }
            
            if (sick.getUsage_type() != null) {
                query.addParameter("usage_type", sick.getUsage_type());
            }
            
            res = query.executeAndFetch(Sick.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<Sick> findByModel(Sick sick, Connection con) {
        return this.findByModel(sick, null, con);
    }
    
    @Override
    public List<Sick> findByModel(Sick sick, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(sick, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Sick> findByModel(Sick sick) {
        return this.findByModel(sick, (List<String>) null);
    }
    
    @Override
    public Sick insert(Sick sick, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into SICKS ( " + 
                "ACOUNT_STATE, " + 
                "ADDRESS, " + 
                "AMOUNT, " + 
                "BIRTH_DATE, " + 
                "CITY, " + 
                "DAILY, " + 
                "END_DATE, " + 
                "FATHER_NAME, " + 
                "HOME, " + 
                "ID, " + 
                "ID_NO, " + 
                "MOBILE, " + 
                "MONTHLY_FEE, " + 
                "NAME, " + 
                "SEX, " + 
                "TREATMENT_DATE, " + 
                "TREATMENT_METHOD, " + 
                "USAGE_TYPE " + 
            ") " + 
            "values (" +
                ":acount_state, " + 
                ":address, " + 
                ":amount, " + 
                ":birth_date, " + 
                ":city, " + 
                ":daily, " + 
                ":end_date, " + 
                ":father_name, " + 
                ":home, " + 
                ":id, " + 
                ":id_no, " + 
                ":mobile, " + 
                ":monthly_fee, " + 
                ":name, " + 
                ":sex, " + 
                ":treatment_date, " + 
                ":treatment_method, " + 
                ":usage_type " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(sick);

            key = query.executeUpdate().getKey();
        }
        
        final String res = Sql2oUtility.getInsertedId("SICKS", "ID", con, key, String.class);
        sick.setId(res);
        logger.info("<< DB insert() - END");
        return sick;
    }
    
    @Override
    public Sick insert(Sick sick) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(sick, con);
            con.commit();
            return sick;
        }
    }
    
    @Override
    public Sick update(Sick sick, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + sick.getId());
        
        String sql = "update SICKS set ";
        
        if (! exclude_nulls || sick.getAcount_state() != null) { 
            sql += "ACOUNT_STATE = :acount_state, ";
        }
        
        if (! exclude_nulls || sick.getAddress() != null) { 
            sql += "ADDRESS = :address, ";
        }
        
        if (! exclude_nulls || sick.getAmount() != null) { 
            sql += "AMOUNT = :amount, ";
        }
        
        if (! exclude_nulls || sick.getBirth_date() != null) { 
            sql += "BIRTH_DATE = :birth_date, ";
        }
        
        if (! exclude_nulls || sick.getCity() != null) { 
            sql += "CITY = :city, ";
        }
        
        if (! exclude_nulls || sick.getDaily() != null) { 
            sql += "DAILY = :daily, ";
        }
        
        if (! exclude_nulls || sick.getEnd_date() != null) { 
            sql += "END_DATE = :end_date, ";
        }
        
        if (! exclude_nulls || sick.getFather_name() != null) { 
            sql += "FATHER_NAME = :father_name, ";
        }
        
        if (! exclude_nulls || sick.getHome() != null) { 
            sql += "HOME = :home, ";
        }
        
        if (! exclude_nulls || sick.getId_no() != null) { 
            sql += "ID_NO = :id_no, ";
        }
        
        if (! exclude_nulls || sick.getMobile() != null) { 
            sql += "MOBILE = :mobile, ";
        }
        
        if (! exclude_nulls || sick.getMonthly_fee() != null) { 
            sql += "MONTHLY_FEE = :monthly_fee, ";
        }
        
        if (! exclude_nulls || sick.getName() != null) { 
            sql += "NAME = :name, ";
        }
        
        if (! exclude_nulls || sick.getSex() != null) { 
            sql += "SEX = :sex, ";
        }
        
        if (! exclude_nulls || sick.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date, ";
        }
        
        if (! exclude_nulls || sick.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method, ";
        }
        
        if (! exclude_nulls || sick.getUsage_type() != null) { 
            sql += "USAGE_TYPE = :usage_type, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || sick.getAcount_state() != null) {
                query.addParameter("acount_state", sick.getAcount_state());
            }
            
            if (! exclude_nulls || sick.getAddress() != null) {
                query.addParameter("address", sick.getAddress());
            }
            
            if (! exclude_nulls || sick.getAmount() != null) {
                query.addParameter("amount", sick.getAmount());
            }
            
            if (! exclude_nulls || sick.getBirth_date() != null) {
                query.addParameter("birth_date", sick.getBirth_date());
            }
            
            if (! exclude_nulls || sick.getCity() != null) {
                query.addParameter("city", sick.getCity());
            }
            
            if (! exclude_nulls || sick.getDaily() != null) {
                query.addParameter("daily", sick.getDaily());
            }
            
            if (! exclude_nulls || sick.getEnd_date() != null) {
                query.addParameter("end_date", sick.getEnd_date());
            }
            
            if (! exclude_nulls || sick.getFather_name() != null) {
                query.addParameter("father_name", sick.getFather_name());
            }
            
            if (! exclude_nulls || sick.getHome() != null) {
                query.addParameter("home", sick.getHome());
            }
            
            if (! exclude_nulls || sick.getId() != null) {
                query.addParameter("id", sick.getId());
            }
            
            if (! exclude_nulls || sick.getId_no() != null) {
                query.addParameter("id_no", sick.getId_no());
            }
            
            if (! exclude_nulls || sick.getMobile() != null) {
                query.addParameter("mobile", sick.getMobile());
            }
            
            if (! exclude_nulls || sick.getMonthly_fee() != null) {
                query.addParameter("monthly_fee", sick.getMonthly_fee());
            }
            
            if (! exclude_nulls || sick.getName() != null) {
                query.addParameter("name", sick.getName());
            }
            
            if (! exclude_nulls || sick.getSex() != null) {
                query.addParameter("sex", sick.getSex());
            }
            
            if (! exclude_nulls || sick.getTreatment_date() != null) {
                query.addParameter("treatment_date", sick.getTreatment_date());
            }
            
            if (! exclude_nulls || sick.getTreatment_method() != null) {
                query.addParameter("treatment_method", sick.getTreatment_method());
            }
            
            if (! exclude_nulls || sick.getUsage_type() != null) {
                query.addParameter("usage_type", sick.getUsage_type());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return sick;
    }
    
    @Override
    public Sick update(Sick sick, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(sick, exclude_nulls, con);
            con.commit();
            return sick;
        }
    }
    
    @Override
    public Sick save(Sick sick, Connection con) {
        final String id = sick.getId();

        final Sick sick2 = this.findById(id, null, con);
        
        if (sick2 == null) {
            return this.insert(sick, con);
        }
        return this.update(sick, false, con);
    }
    
    @Override
    public Sick save(Sick sick) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(sick, con);
            con.commit();
            return sick;
        }
    }
    
    @Override
    public void delete(String id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from SICKS ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(String id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(Sick sick, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from SICKS ";
        sql += "where ";
        
        if (sick.getAcount_state() != null) { 
            sql += "ACOUNT_STATE = :acount_state and ";
        }
        
        if (sick.getAddress() != null) { 
            sql += "ADDRESS = :address and ";
        }
        
        if (sick.getAmount() != null) { 
            sql += "AMOUNT = :amount and ";
        }
        
        if (sick.getBirth_date() != null) { 
            sql += "BIRTH_DATE = :birth_date and ";
        }
        
        if (sick.getCity() != null) { 
            sql += "CITY = :city and ";
        }
        
        if (sick.getDaily() != null) { 
            sql += "DAILY = :daily and ";
        }
        
        if (sick.getEnd_date() != null) { 
            sql += "END_DATE = :end_date and ";
        }
        
        if (sick.getFather_name() != null) { 
            sql += "FATHER_NAME = :father_name and ";
        }
        
        if (sick.getHome() != null) { 
            sql += "HOME = :home and ";
        }
        
        if (sick.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (sick.getId_no() != null) { 
            sql += "ID_NO = :id_no and ";
        }
        
        if (sick.getMobile() != null) { 
            sql += "MOBILE = :mobile and ";
        }
        
        if (sick.getMonthly_fee() != null) { 
            sql += "MONTHLY_FEE = :monthly_fee and ";
        }
        
        if (sick.getName() != null) { 
            sql += "NAME = :name and ";
        }
        
        if (sick.getSex() != null) { 
            sql += "SEX = :sex and ";
        }
        
        if (sick.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        if (sick.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method and ";
        }
        
        if (sick.getUsage_type() != null) { 
            sql += "USAGE_TYPE = :usage_type and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (sick.getAcount_state() != null) {
                query.addParameter("acount_state", sick.getAcount_state());
            }
            
            if (sick.getAddress() != null) {
                query.addParameter("address", sick.getAddress());
            }
            
            if (sick.getAmount() != null) {
                query.addParameter("amount", sick.getAmount());
            }
            
            if (sick.getBirth_date() != null) {
                query.addParameter("birth_date", sick.getBirth_date());
            }
            
            if (sick.getCity() != null) {
                query.addParameter("city", sick.getCity());
            }
            
            if (sick.getDaily() != null) {
                query.addParameter("daily", sick.getDaily());
            }
            
            if (sick.getEnd_date() != null) {
                query.addParameter("end_date", sick.getEnd_date());
            }
            
            if (sick.getFather_name() != null) {
                query.addParameter("father_name", sick.getFather_name());
            }
            
            if (sick.getHome() != null) {
                query.addParameter("home", sick.getHome());
            }
            
            if (sick.getId() != null) {
                query.addParameter("id", sick.getId());
            }
            
            if (sick.getId_no() != null) {
                query.addParameter("id_no", sick.getId_no());
            }
            
            if (sick.getMobile() != null) {
                query.addParameter("mobile", sick.getMobile());
            }
            
            if (sick.getMonthly_fee() != null) {
                query.addParameter("monthly_fee", sick.getMonthly_fee());
            }
            
            if (sick.getName() != null) {
                query.addParameter("name", sick.getName());
            }
            
            if (sick.getSex() != null) {
                query.addParameter("sex", sick.getSex());
            }
            
            if (sick.getTreatment_date() != null) {
                query.addParameter("treatment_date", sick.getTreatment_date());
            }
            
            if (sick.getTreatment_method() != null) {
                query.addParameter("treatment_method", sick.getTreatment_method());
            }
            
            if (sick.getUsage_type() != null) {
                query.addParameter("usage_type", sick.getUsage_type());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(Sick sick) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(sick, con);
            con.commit();
        }
    }
}
