/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.Test;


public interface TestRepository {
    Test findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    Test findByCode(Long code, Connection con);
    
    Test findByCode(Long code, List<String> fields_to_ignore);
    
    Test findByCode(Long code);
    
    Test insert(Test test, Connection con);
    
    Test insert(Test test);
    
    Test update(Test test, boolean exclude_nulls, Connection con);
    
    Test update(Test test, boolean exclude_nulls);
    
    Test save(Test test, Connection con);
    
    Test save(Test test);
    
    List<Test> findAll(List<String> fields_to_ignore, Connection con);
    
    List<Test> findAll(Connection con);
    
    List<Test> findAll(List<String> fields_to_ignore);
    
    List<Test> findAll();
    
    List<Test> findByModel(Test test, List<String> fields_to_ignore, Connection con);
    
    List<Test> findByModel(Test test, Connection con);
    
    List<Test> findByModel(Test test, List<String> fields_to_ignore);
    
    List<Test> findByModel(Test test);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(Test test, Connection con);
    
    void deleteByModel(Test test);
}
