/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.TrackingReal;
import com.arc.utility.Sql2oUtility;


@Repository
public class TrackingRealRepositoryImpl implements TrackingRealRepository {
    private final static Logger logger = LoggerFactory.getLogger(TrackingRealRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COMMENTS")) {
            res += "t.COMMENTS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "t.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "t.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("RESULT")) {
            res += "t.RESULT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "t.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "t.SICK_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TRACKING_NO")) {
            res += "t.TRACKING_NO, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_DATE")) {
            res += "t.TREATMENT_DATE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public TrackingReal findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + TrackingRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from TRACKINGS_REAL t ";
        sql += "where "; 
        sql += "ID = :id ";
        
        TrackingReal res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(TrackingReal.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public TrackingReal findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public TrackingReal findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public TrackingReal findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<TrackingReal> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + TrackingRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from TRACKINGS_REAL t ";
        
        List<TrackingReal> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(TrackingReal.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<TrackingReal> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<TrackingReal> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<TrackingReal> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<TrackingReal> findByModel(TrackingReal trackingReal, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + TrackingRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from TRACKINGS_REAL t ";
        sql += "where ";
        
        if (trackingReal.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (trackingReal.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (trackingReal.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (trackingReal.getResult() != null) { 
            sql += "RESULT = :result and ";
        }
        
        if (trackingReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (trackingReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (trackingReal.getTracking_no() != null) { 
            sql += "TRACKING_NO = :tracking_no and ";
        }
        
        if (trackingReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<TrackingReal> res;
        
        try (Query query = con.createQuery(sql)) {
            if (trackingReal.getComments() != null) {
                query.addParameter("comments", trackingReal.getComments());
            }
            
            if (trackingReal.getDate() != null) {
                query.addParameter("date", trackingReal.getDate());
            }
            
            if (trackingReal.getId() != null) {
                query.addParameter("id", trackingReal.getId());
            }
            
            if (trackingReal.getResult() != null) {
                query.addParameter("result", trackingReal.getResult());
            }
            
            if (trackingReal.getSick_id() != null) {
                query.addParameter("sick_id", trackingReal.getSick_id());
            }
            
            if (trackingReal.getSick_name() != null) {
                query.addParameter("sick_name", trackingReal.getSick_name());
            }
            
            if (trackingReal.getTracking_no() != null) {
                query.addParameter("tracking_no", trackingReal.getTracking_no());
            }
            
            if (trackingReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", trackingReal.getTreatment_date());
            }
            
            res = query.executeAndFetch(TrackingReal.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<TrackingReal> findByModel(TrackingReal trackingReal, Connection con) {
        return this.findByModel(trackingReal, null, con);
    }
    
    @Override
    public List<TrackingReal> findByModel(TrackingReal trackingReal, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(trackingReal, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<TrackingReal> findByModel(TrackingReal trackingReal) {
        return this.findByModel(trackingReal, (List<String>) null);
    }
    
    @Override
    public TrackingReal insert(TrackingReal trackingReal, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into TRACKINGS_REAL ( " + 
                "COMMENTS, " + 
                "DATE, " + 
                "ID, " + 
                "RESULT, " + 
                "SICK_ID, " + 
                "SICK_NAME, " + 
                "TRACKING_NO, " + 
                "TREATMENT_DATE " + 
            ") " + 
            "values (" +
                ":comments, " + 
                ":date, " + 
                ":id, " + 
                ":result, " + 
                ":sick_id, " + 
                ":sick_name, " + 
                ":tracking_no, " + 
                ":treatment_date " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(trackingReal);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("TRACKINGS_REAL", "ID", con, key, Long.class);
        trackingReal.setId(res);
        logger.info("<< DB insert() - END");
        return trackingReal;
    }
    
    @Override
    public TrackingReal insert(TrackingReal trackingReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(trackingReal, con);
            con.commit();
            return trackingReal;
        }
    }
    
    @Override
    public TrackingReal update(TrackingReal trackingReal, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + trackingReal.getId());
        
        String sql = "update TRACKINGS_REAL set ";
        
        if (! exclude_nulls || trackingReal.getComments() != null) { 
            sql += "COMMENTS = :comments, ";
        }
        
        if (! exclude_nulls || trackingReal.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || trackingReal.getResult() != null) { 
            sql += "RESULT = :result, ";
        }
        
        if (! exclude_nulls || trackingReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || trackingReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        if (! exclude_nulls || trackingReal.getTracking_no() != null) { 
            sql += "TRACKING_NO = :tracking_no, ";
        }
        
        if (! exclude_nulls || trackingReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || trackingReal.getComments() != null) {
                query.addParameter("comments", trackingReal.getComments());
            }
            
            if (! exclude_nulls || trackingReal.getDate() != null) {
                query.addParameter("date", trackingReal.getDate());
            }
            
            if (! exclude_nulls || trackingReal.getId() != null) {
                query.addParameter("id", trackingReal.getId());
            }
            
            if (! exclude_nulls || trackingReal.getResult() != null) {
                query.addParameter("result", trackingReal.getResult());
            }
            
            if (! exclude_nulls || trackingReal.getSick_id() != null) {
                query.addParameter("sick_id", trackingReal.getSick_id());
            }
            
            if (! exclude_nulls || trackingReal.getSick_name() != null) {
                query.addParameter("sick_name", trackingReal.getSick_name());
            }
            
            if (! exclude_nulls || trackingReal.getTracking_no() != null) {
                query.addParameter("tracking_no", trackingReal.getTracking_no());
            }
            
            if (! exclude_nulls || trackingReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", trackingReal.getTreatment_date());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return trackingReal;
    }
    
    @Override
    public TrackingReal update(TrackingReal trackingReal, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(trackingReal, exclude_nulls, con);
            con.commit();
            return trackingReal;
        }
    }
    
    @Override
    public TrackingReal save(TrackingReal trackingReal, Connection con) {
        final Long id = trackingReal.getId();

        final TrackingReal trackingReal2 = this.findById(id, null, con);
        
        if (trackingReal2 == null) {
            return this.insert(trackingReal, con);
        }
        return this.update(trackingReal, false, con);
    }
    
    @Override
    public TrackingReal save(TrackingReal trackingReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(trackingReal, con);
            con.commit();
            return trackingReal;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from TRACKINGS_REAL ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(TrackingReal trackingReal, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from TRACKINGS_REAL ";
        sql += "where ";
        
        if (trackingReal.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (trackingReal.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (trackingReal.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (trackingReal.getResult() != null) { 
            sql += "RESULT = :result and ";
        }
        
        if (trackingReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (trackingReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (trackingReal.getTracking_no() != null) { 
            sql += "TRACKING_NO = :tracking_no and ";
        }
        
        if (trackingReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (trackingReal.getComments() != null) {
                query.addParameter("comments", trackingReal.getComments());
            }
            
            if (trackingReal.getDate() != null) {
                query.addParameter("date", trackingReal.getDate());
            }
            
            if (trackingReal.getId() != null) {
                query.addParameter("id", trackingReal.getId());
            }
            
            if (trackingReal.getResult() != null) {
                query.addParameter("result", trackingReal.getResult());
            }
            
            if (trackingReal.getSick_id() != null) {
                query.addParameter("sick_id", trackingReal.getSick_id());
            }
            
            if (trackingReal.getSick_name() != null) {
                query.addParameter("sick_name", trackingReal.getSick_name());
            }
            
            if (trackingReal.getTracking_no() != null) {
                query.addParameter("tracking_no", trackingReal.getTracking_no());
            }
            
            if (trackingReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", trackingReal.getTreatment_date());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(TrackingReal trackingReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(trackingReal, con);
            con.commit();
        }
    }
}
