/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.DispensedItem;


public class DispensedItemAggregator {
    private DispensedItem dispensedItem;
    
    public DispensedItem getDispensedItem() {
        return this.dispensedItem;
    }
    
    public void setDispensedItem(DispensedItem dispensedItem) {
        this.dispensedItem = dispensedItem;
    }
}
