/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.MapBtoGAggregator;
import com.arc.model.MapBtoG;
import com.arc.repository.MapBtoGRepository;


@Service
public class MapBtoGServiceImpl implements MapBtoGService {
    @Autowired
    private MapBtoGRepository mapBtoGRepository;
    
    private MapBtoGAggregator enrich(MapBtoG mapBtoG) {
        MapBtoGAggregator mapBtoGAggregator = null;
        
        if (mapBtoG != null) {
            mapBtoGAggregator = new MapBtoGAggregator();
            
            mapBtoGAggregator.setMapBtoG(mapBtoG);
        }
        
        return mapBtoGAggregator;
    }
    
    private List<MapBtoGAggregator> enrich(List<MapBtoG> mapBtoGs) {
        final List<MapBtoGAggregator> mapBtoGAggregators = new ArrayList<>();
        
        if (mapBtoGs != null) {
            for (MapBtoG mapBtoG: mapBtoGs) {
                mapBtoGAggregators.add(this.enrich(mapBtoG));
            }
        }
        
        return mapBtoGAggregators;
    }
    
    @Override
    public List<MapBtoGAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findAll(Connection con) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findAll(con);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findAll(List<String> fields_to_ignore) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findAll(fields_to_ignore);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findAll() {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findAll();
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findByModel(MapBtoG mapBtoG, List<String> fields_to_ignore, Connection con) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findByModel(mapBtoG, fields_to_ignore, con);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findByModel(MapBtoG mapBtoG, Connection con) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findByModel(mapBtoG, con);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findByModel(MapBtoG mapBtoG, List<String> fields_to_ignore) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findByModel(mapBtoG, fields_to_ignore);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public List<MapBtoGAggregator> findByModel(MapBtoG mapBtoG) {
        final List<MapBtoG> mapBtoGs = this.mapBtoGRepository.findByModel(mapBtoG);
        
        return this.enrich(mapBtoGs);
    }
    
    @Override
    public MapBtoGAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con) {
        final MapBtoG mapBtoG = this.mapBtoGRepository.findByCode(code, fields_to_ignore, con);
        
        return this.enrich(mapBtoG);
    }
    
    @Override
    public MapBtoGAggregator findByCode(Long code, Connection con) {
        final MapBtoG mapBtoG = this.mapBtoGRepository.findByCode(code, con);
        
        return this.enrich(mapBtoG);
    }
    
    @Override
    public MapBtoGAggregator findByCode(Long code, List<String> fields_to_ignore) {
        final MapBtoG mapBtoG = this.mapBtoGRepository.findByCode(code, fields_to_ignore);
        
        return this.enrich(mapBtoG);
    }
    
    @Override
    public MapBtoGAggregator findByCode(Long code) {
        final MapBtoG mapBtoG = this.mapBtoGRepository.findByCode(code);
        
        return this.enrich(mapBtoG);
    }
    
    @Override
    public MapBtoG insert(MapBtoG mapBtoG, Connection con) {
        return this.mapBtoGRepository.insert(mapBtoG, con);
    }
    
    @Override
    public MapBtoG insert(MapBtoG mapBtoG) {
        return this.mapBtoGRepository.insert(mapBtoG);
    }
    
    @Override
    public MapBtoG update(MapBtoG mapBtoG, boolean exclude_nulls, Connection con) {
        return this.mapBtoGRepository.update(mapBtoG, exclude_nulls, con);
    }
    
    @Override
    public MapBtoG update(MapBtoG mapBtoG, boolean exclude_nulls) {
        return this.mapBtoGRepository.update(mapBtoG, exclude_nulls);
    }
    
    @Override
    public MapBtoG save(MapBtoG mapBtoG, Connection con) {
        return this.mapBtoGRepository.save(mapBtoG, con);
    }
    
    @Override
    public MapBtoG save(MapBtoG mapBtoG) {
        return this.mapBtoGRepository.save(mapBtoG);
    }
    
    @Override
    public void delete(Long code, Connection con) {
        this.mapBtoGRepository.delete(code, con);
    }
    
    @Override
    public void delete(Long code) {
        this.mapBtoGRepository.delete(code);
    }
    
    @Override
    public void deleteByModel(MapBtoG mapBtoG, Connection con) {
        this.mapBtoGRepository.deleteByModel(mapBtoG, con);
    }
    
    @Override
    public void deleteByModel(MapBtoG mapBtoG) {
        this.mapBtoGRepository.deleteByModel(mapBtoG);
    }
}
