/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.SickHistory;


public class SickHistoryAggregator {
    private SickHistory sickHistory;
    
    public SickHistory getSickHistory() {
        return this.sickHistory;
    }
    
    public void setSickHistory(SickHistory sickHistory) {
        this.sickHistory = sickHistory;
    }
}
