/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.ContactDepot;


public interface ContactDepotRepository {
    ContactDepot findByIds(String contact_id, String drug_name, List<String> fields_to_ignore, Connection con);
    
    ContactDepot findByIds(String contact_id, String drug_name, Connection con);
    
    ContactDepot findByIds(String contact_id, String drug_name, List<String> fields_to_ignore);
    
    ContactDepot findByIds(String contact_id, String drug_name);
    
    ContactDepot insert(ContactDepot contactDepot, Connection con);
    
    ContactDepot insert(ContactDepot contactDepot);
    
    ContactDepot update(ContactDepot contactDepot, boolean exclude_nulls, Connection con);
    
    ContactDepot update(ContactDepot contactDepot, boolean exclude_nulls);
    
    ContactDepot save(ContactDepot contactDepot, Connection con);
    
    ContactDepot save(ContactDepot contactDepot);
    
    List<ContactDepot> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ContactDepot> findAll(Connection con);
    
    List<ContactDepot> findAll(List<String> fields_to_ignore);
    
    List<ContactDepot> findAll();
    
    List<ContactDepot> findByModel(ContactDepot contactDepot, List<String> fields_to_ignore, Connection con);
    
    List<ContactDepot> findByModel(ContactDepot contactDepot, Connection con);
    
    List<ContactDepot> findByModel(ContactDepot contactDepot, List<String> fields_to_ignore);
    
    List<ContactDepot> findByModel(ContactDepot contactDepot);
    
    void delete(String contact_id, String drug_name, Connection con);
    
    void delete(String contact_id, String drug_name);
    
    void deleteByModel(ContactDepot contactDepot, Connection con);
    
    void deleteByModel(ContactDepot contactDepot);
}
