/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.model;



public class GeneralSetting {
    private String investigator_key;
    private String pay_type;
    private String pay_type_real;
    private String promotion;
    
    
    public String getInvestigator_key() {
        return this.investigator_key;
    }
    
    public void setInvestigator_key(String investigator_key) {
        this.investigator_key = investigator_key;
    }
    
    public String getPay_type() {
        return this.pay_type;
    }
    
    public void setPay_type(String pay_type) {
        this.pay_type = pay_type;
    }
    
    public String getPay_type_real() {
        return this.pay_type_real;
    }
    
    public void setPay_type_real(String pay_type_real) {
        this.pay_type_real = pay_type_real;
    }
    
    public String getPromotion() {
        return this.promotion;
    }
    
    public void setPromotion(String promotion) {
        this.promotion = promotion;
    }
}
