/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.ActionLog;


public class ActionLogAggregator {
    private ActionLog actionLog;
    
    public ActionLog getActionLog() {
        return this.actionLog;
    }
    
    public void setActionLog(ActionLog actionLog) {
        this.actionLog = actionLog;
    }
}
