/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Depot;


public class DepotAggregator {
    private Depot depot;
    
    public Depot getDepot() {
        return this.depot;
    }
    
    public void setDepot(Depot depot) {
        this.depot = depot;
    }
}
