/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Prescription;


public class PrescriptionAggregator {
    private Prescription prescription;
    
    public Prescription getPrescription() {
        return this.prescription;
    }
    
    public void setPrescription(Prescription prescription) {
        this.prescription = prescription;
    }
}
