/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Psychologist;


public class PsychologistAggregator {
    private Psychologist psychologist;
    
    public Psychologist getPsychologist() {
        return this.psychologist;
    }
    
    public void setPsychologist(Psychologist psychologist) {
        this.psychologist = psychologist;
    }
}
