/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.PsychologistReal;


public class PsychologistRealAggregator {
    private PsychologistReal psychologistReal;
    
    public PsychologistReal getPsychologistReal() {
        return this.psychologistReal;
    }
    
    public void setPsychologistReal(PsychologistReal psychologistReal) {
        this.psychologistReal = psychologistReal;
    }
}
