/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.TrackingReal;


public class TrackingRealAggregator {
    private TrackingReal trackingReal;
    
    public TrackingReal getTrackingReal() {
        return this.trackingReal;
    }
    
    public void setTrackingReal(TrackingReal trackingReal) {
        this.trackingReal = trackingReal;
    }
}
