/**
 * !!! DO NOT EDIT THIS FILE !!!
 * This file is auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.enums;

public enum DatasourceTypeEnum {
    MSSQL("mssql"),
    ORACLE("oracle");

    private String type;

    private DatasourceTypeEnum(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }
}

