/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.Expense;


public interface ExpenseRepository {
    Expense findById(Long id, List<String> fields_to_ignore, Connection con);
    
    Expense findById(Long id, Connection con);
    
    Expense findById(Long id, List<String> fields_to_ignore);
    
    Expense findById(Long id);
    
    Expense insert(Expense expense, Connection con);
    
    Expense insert(Expense expense);
    
    Expense update(Expense expense, boolean exclude_nulls, Connection con);
    
    Expense update(Expense expense, boolean exclude_nulls);
    
    Expense save(Expense expense, Connection con);
    
    Expense save(Expense expense);
    
    List<Expense> findAll(List<String> fields_to_ignore, Connection con);
    
    List<Expense> findAll(Connection con);
    
    List<Expense> findAll(List<String> fields_to_ignore);
    
    List<Expense> findAll();
    
    List<Expense> findByModel(Expense expense, List<String> fields_to_ignore, Connection con);
    
    List<Expense> findByModel(Expense expense, Connection con);
    
    List<Expense> findByModel(Expense expense, List<String> fields_to_ignore);
    
    List<Expense> findByModel(Expense expense);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(Expense expense, Connection con);
    
    void deleteByModel(Expense expense);
}
