/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.DispensedItemReal;


public interface DispensedItemRealRepository {
    DispensedItemReal findByIds(Long id, String drug_name, List<String> fields_to_ignore, Connection con);
    
    DispensedItemReal findByIds(Long id, String drug_name, Connection con);
    
    DispensedItemReal findByIds(Long id, String drug_name, List<String> fields_to_ignore);
    
    DispensedItemReal findByIds(Long id, String drug_name);
    
    DispensedItemReal insert(DispensedItemReal dispensedItemReal, Connection con);
    
    DispensedItemReal insert(DispensedItemReal dispensedItemReal);
    
    DispensedItemReal update(DispensedItemReal dispensedItemReal, boolean exclude_nulls, Connection con);
    
    DispensedItemReal update(DispensedItemReal dispensedItemReal, boolean exclude_nulls);
    
    DispensedItemReal save(DispensedItemReal dispensedItemReal, Connection con);
    
    DispensedItemReal save(DispensedItemReal dispensedItemReal);
    
    List<DispensedItemReal> findAll(List<String> fields_to_ignore, Connection con);
    
    List<DispensedItemReal> findAll(Connection con);
    
    List<DispensedItemReal> findAll(List<String> fields_to_ignore);
    
    List<DispensedItemReal> findAll();
    
    List<DispensedItemReal> findByModel(DispensedItemReal dispensedItemReal, List<String> fields_to_ignore, Connection con);
    
    List<DispensedItemReal> findByModel(DispensedItemReal dispensedItemReal, Connection con);
    
    List<DispensedItemReal> findByModel(DispensedItemReal dispensedItemReal, List<String> fields_to_ignore);
    
    List<DispensedItemReal> findByModel(DispensedItemReal dispensedItemReal);
    
    void delete(Long id, String drug_name, Connection con);
    
    void delete(Long id, String drug_name);
    
    void deleteByModel(DispensedItemReal dispensedItemReal, Connection con);
    
    void deleteByModel(DispensedItemReal dispensedItemReal);
}
