/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.PrescriptionRealAggregator;
import com.arc.model.PrescriptionReal;
import com.arc.repository.PrescriptionRealRepository;


@Service
public class PrescriptionRealServiceImpl implements PrescriptionRealService {
    @Autowired
    private PrescriptionRealRepository prescriptionRealRepository;
    
    private PrescriptionRealAggregator enrich(PrescriptionReal prescriptionReal) {
        PrescriptionRealAggregator prescriptionRealAggregator = null;
        
        if (prescriptionReal != null) {
            prescriptionRealAggregator = new PrescriptionRealAggregator();
            
            prescriptionRealAggregator.setPrescriptionReal(prescriptionReal);
        }
        
        return prescriptionRealAggregator;
    }
    
    private List<PrescriptionRealAggregator> enrich(List<PrescriptionReal> prescriptionReals) {
        final List<PrescriptionRealAggregator> prescriptionRealAggregators = new ArrayList<>();
        
        if (prescriptionReals != null) {
            for (PrescriptionReal prescriptionReal: prescriptionReals) {
                prescriptionRealAggregators.add(this.enrich(prescriptionReal));
            }
        }
        
        return prescriptionRealAggregators;
    }
    
    @Override
    public List<PrescriptionRealAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findAll(Connection con) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findAll(con);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findAll(List<String> fields_to_ignore) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findAll(fields_to_ignore);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findAll() {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findAll();
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal, List<String> fields_to_ignore, Connection con) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findByModel(prescriptionReal, fields_to_ignore, con);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal, Connection con) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findByModel(prescriptionReal, con);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal, List<String> fields_to_ignore) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findByModel(prescriptionReal, fields_to_ignore);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal) {
        final List<PrescriptionReal> prescriptionReals = this.prescriptionRealRepository.findByModel(prescriptionReal);
        
        return this.enrich(prescriptionReals);
    }
    
    @Override
    public PrescriptionRealAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con) {
        final PrescriptionReal prescriptionReal = this.prescriptionRealRepository.findByCode(code, fields_to_ignore, con);
        
        return this.enrich(prescriptionReal);
    }
    
    @Override
    public PrescriptionRealAggregator findByCode(Long code, Connection con) {
        final PrescriptionReal prescriptionReal = this.prescriptionRealRepository.findByCode(code, con);
        
        return this.enrich(prescriptionReal);
    }
    
    @Override
    public PrescriptionRealAggregator findByCode(Long code, List<String> fields_to_ignore) {
        final PrescriptionReal prescriptionReal = this.prescriptionRealRepository.findByCode(code, fields_to_ignore);
        
        return this.enrich(prescriptionReal);
    }
    
    @Override
    public PrescriptionRealAggregator findByCode(Long code) {
        final PrescriptionReal prescriptionReal = this.prescriptionRealRepository.findByCode(code);
        
        return this.enrich(prescriptionReal);
    }
    
    @Override
    public PrescriptionReal insert(PrescriptionReal prescriptionReal, Connection con) {
        return this.prescriptionRealRepository.insert(prescriptionReal, con);
    }
    
    @Override
    public PrescriptionReal insert(PrescriptionReal prescriptionReal) {
        return this.prescriptionRealRepository.insert(prescriptionReal);
    }
    
    @Override
    public PrescriptionReal update(PrescriptionReal prescriptionReal, boolean exclude_nulls, Connection con) {
        return this.prescriptionRealRepository.update(prescriptionReal, exclude_nulls, con);
    }
    
    @Override
    public PrescriptionReal update(PrescriptionReal prescriptionReal, boolean exclude_nulls) {
        return this.prescriptionRealRepository.update(prescriptionReal, exclude_nulls);
    }
    
    @Override
    public PrescriptionReal save(PrescriptionReal prescriptionReal, Connection con) {
        return this.prescriptionRealRepository.save(prescriptionReal, con);
    }
    
    @Override
    public PrescriptionReal save(PrescriptionReal prescriptionReal) {
        return this.prescriptionRealRepository.save(prescriptionReal);
    }
    
    @Override
    public void delete(Long code, Connection con) {
        this.prescriptionRealRepository.delete(code, con);
    }
    
    @Override
    public void delete(Long code) {
        this.prescriptionRealRepository.delete(code);
    }
    
    @Override
    public void deleteByModel(PrescriptionReal prescriptionReal, Connection con) {
        this.prescriptionRealRepository.deleteByModel(prescriptionReal, con);
    }
    
    @Override
    public void deleteByModel(PrescriptionReal prescriptionReal) {
        this.prescriptionRealRepository.deleteByModel(prescriptionReal);
    }
}
