/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.PrescriptionRealAggregator;
import com.arc.model.PrescriptionReal;


public interface PrescriptionRealService {
    PrescriptionRealAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    PrescriptionRealAggregator findByCode(Long code, Connection con);
    
    PrescriptionRealAggregator findByCode(Long code, List<String> fields_to_ignore);
    
    PrescriptionRealAggregator findByCode(Long code);
    
    PrescriptionReal insert(PrescriptionReal prescriptionReal, Connection con);
    
    PrescriptionReal insert(PrescriptionReal prescriptionReal);
    
    PrescriptionReal update(PrescriptionReal prescriptionReal, boolean exclude_nulls, Connection con);
    
    PrescriptionReal update(PrescriptionReal prescriptionReal, boolean exclude_nulls);
    
    PrescriptionReal save(PrescriptionReal prescriptionReal, Connection con);
    
    PrescriptionReal save(PrescriptionReal prescriptionReal);
    
    List<PrescriptionRealAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<PrescriptionRealAggregator> findAll(Connection con);
    
    List<PrescriptionRealAggregator> findAll(List<String> fields_to_ignore);
    
    List<PrescriptionRealAggregator> findAll();
    
    List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal, List<String> fields_to_ignore, Connection con);
    
    List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal, Connection con);
    
    List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal, List<String> fields_to_ignore);
    
    List<PrescriptionRealAggregator> findByModel(PrescriptionReal prescriptionReal);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(PrescriptionReal prescriptionReal, Connection con);
    
    void deleteByModel(PrescriptionReal prescriptionReal);
}
