/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.NurseDepotAggregator;
import com.arc.model.NurseDepot;


public interface NurseDepotService {
    NurseDepotAggregator findByDrug_name(String drug_name, List<String> fields_to_ignore, Connection con);
    
    NurseDepotAggregator findByDrug_name(String drug_name, Connection con);
    
    NurseDepotAggregator findByDrug_name(String drug_name, List<String> fields_to_ignore);
    
    NurseDepotAggregator findByDrug_name(String drug_name);
    
    NurseDepot insert(NurseDepot nurseDepot, Connection con);
    
    NurseDepot insert(NurseDepot nurseDepot);
    
    NurseDepot update(NurseDepot nurseDepot, boolean exclude_nulls, Connection con);
    
    NurseDepot update(NurseDepot nurseDepot, boolean exclude_nulls);
    
    NurseDepot save(NurseDepot nurseDepot, Connection con);
    
    NurseDepot save(NurseDepot nurseDepot);
    
    List<NurseDepotAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<NurseDepotAggregator> findAll(Connection con);
    
    List<NurseDepotAggregator> findAll(List<String> fields_to_ignore);
    
    List<NurseDepotAggregator> findAll();
    
    List<NurseDepotAggregator> findByModel(NurseDepot nurseDepot, List<String> fields_to_ignore, Connection con);
    
    List<NurseDepotAggregator> findByModel(NurseDepot nurseDepot, Connection con);
    
    List<NurseDepotAggregator> findByModel(NurseDepot nurseDepot, List<String> fields_to_ignore);
    
    List<NurseDepotAggregator> findByModel(NurseDepot nurseDepot);
    
    void delete(String drug_name, Connection con);
    
    void delete(String drug_name);
    
    void deleteByModel(NurseDepot nurseDepot, Connection con);
    
    void deleteByModel(NurseDepot nurseDepot);
}
