/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.PaymentReal;


public class PaymentRealAggregator {
    private PaymentReal paymentReal;
    
    public PaymentReal getPaymentReal() {
        return this.paymentReal;
    }
    
    public void setPaymentReal(PaymentReal paymentReal) {
        this.paymentReal = paymentReal;
    }
}
