/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.model;



public class Assessment {
    private String assessment_date;
    private Long code;
    private Integer q1a;
    private Integer q1b;
    private Integer q2a;
    private Integer q2b;
    private Integer q2c;
    private Integer q2d;
    private Integer q3a;
    private Integer q3b;
    private Integer q3c;
    private Integer q3d;
    private Integer q4a;
    private Integer q4b;
    private Integer q4c;
    private Integer q4d;
    private Integer q4e;
    private String sick_id;
    private String sick_name;
    private Integer sum_all;
    
    
    public String getAssessment_date() {
        return this.assessment_date;
    }
    
    public void setAssessment_date(String assessment_date) {
        this.assessment_date = assessment_date;
    }
    
    public Long getCode() {
        return this.code;
    }
    
    public void setCode(Long code) {
        this.code = code;
    }
    
    public Integer getQ1a() {
        return this.q1a;
    }
    
    public void setQ1a(Integer q1a) {
        this.q1a = q1a;
    }
    
    public Integer getQ1b() {
        return this.q1b;
    }
    
    public void setQ1b(Integer q1b) {
        this.q1b = q1b;
    }
    
    public Integer getQ2a() {
        return this.q2a;
    }
    
    public void setQ2a(Integer q2a) {
        this.q2a = q2a;
    }
    
    public Integer getQ2b() {
        return this.q2b;
    }
    
    public void setQ2b(Integer q2b) {
        this.q2b = q2b;
    }
    
    public Integer getQ2c() {
        return this.q2c;
    }
    
    public void setQ2c(Integer q2c) {
        this.q2c = q2c;
    }
    
    public Integer getQ2d() {
        return this.q2d;
    }
    
    public void setQ2d(Integer q2d) {
        this.q2d = q2d;
    }
    
    public Integer getQ3a() {
        return this.q3a;
    }
    
    public void setQ3a(Integer q3a) {
        this.q3a = q3a;
    }
    
    public Integer getQ3b() {
        return this.q3b;
    }
    
    public void setQ3b(Integer q3b) {
        this.q3b = q3b;
    }
    
    public Integer getQ3c() {
        return this.q3c;
    }
    
    public void setQ3c(Integer q3c) {
        this.q3c = q3c;
    }
    
    public Integer getQ3d() {
        return this.q3d;
    }
    
    public void setQ3d(Integer q3d) {
        this.q3d = q3d;
    }
    
    public Integer getQ4a() {
        return this.q4a;
    }
    
    public void setQ4a(Integer q4a) {
        this.q4a = q4a;
    }
    
    public Integer getQ4b() {
        return this.q4b;
    }
    
    public void setQ4b(Integer q4b) {
        this.q4b = q4b;
    }
    
    public Integer getQ4c() {
        return this.q4c;
    }
    
    public void setQ4c(Integer q4c) {
        this.q4c = q4c;
    }
    
    public Integer getQ4d() {
        return this.q4d;
    }
    
    public void setQ4d(Integer q4d) {
        this.q4d = q4d;
    }
    
    public Integer getQ4e() {
        return this.q4e;
    }
    
    public void setQ4e(Integer q4e) {
        this.q4e = q4e;
    }
    
    public String getSick_id() {
        return this.sick_id;
    }
    
    public void setSick_id(String sick_id) {
        this.sick_id = sick_id;
    }
    
    public String getSick_name() {
        return this.sick_name;
    }
    
    public void setSick_name(String sick_name) {
        this.sick_name = sick_name;
    }
    
    public Integer getSum_all() {
        return this.sum_all;
    }
    
    public void setSum_all(Integer sum_all) {
        this.sum_all = sum_all;
    }
}
