/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.model;



public class DispensedItemReal {
    private Double count;
    private String dispense_date;
    private String dispense_day;
    private String drug_name;
    private String from_date;
    private Long id;
    private String sick_id;
    private String sick_name;
    private String to_date;
    private String treatment_method;
    
    
    public Double getCount() {
        return this.count;
    }
    
    public void setCount(Double count) {
        this.count = count;
    }
    
    public String getDispense_date() {
        return this.dispense_date;
    }
    
    public void setDispense_date(String dispense_date) {
        this.dispense_date = dispense_date;
    }
    
    public String getDispense_day() {
        return this.dispense_day;
    }
    
    public void setDispense_day(String dispense_day) {
        this.dispense_day = dispense_day;
    }
    
    public String getDrug_name() {
        return this.drug_name;
    }
    
    public void setDrug_name(String drug_name) {
        this.drug_name = drug_name;
    }
    
    public String getFrom_date() {
        return this.from_date;
    }
    
    public void setFrom_date(String from_date) {
        this.from_date = from_date;
    }
    
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public String getSick_id() {
        return this.sick_id;
    }
    
    public void setSick_id(String sick_id) {
        this.sick_id = sick_id;
    }
    
    public String getSick_name() {
        return this.sick_name;
    }
    
    public void setSick_name(String sick_name) {
        this.sick_name = sick_name;
    }
    
    public String getTo_date() {
        return this.to_date;
    }
    
    public void setTo_date(String to_date) {
        this.to_date = to_date;
    }
    
    public String getTreatment_method() {
        return this.treatment_method;
    }
    
    public void setTreatment_method(String treatment_method) {
        this.treatment_method = treatment_method;
    }
}
