/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.model;



public class Test {
    private Long code;
    private String comments;
    private String date;
    private String result;
    private String sick_id;
    private String sick_name;
    private String treatment_date;
    private String type;
    
    
    public Long getCode() {
        return this.code;
    }
    
    public void setCode(Long code) {
        this.code = code;
    }
    
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }
    
    public String getSick_id() {
        return this.sick_id;
    }
    
    public void setSick_id(String sick_id) {
        this.sick_id = sick_id;
    }
    
    public String getSick_name() {
        return this.sick_name;
    }
    
    public void setSick_name(String sick_name) {
        this.sick_name = sick_name;
    }
    
    public String getTreatment_date() {
        return this.treatment_date;
    }
    
    public void setTreatment_date(String treatment_date) {
        this.treatment_date = treatment_date;
    }
    
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
}
