/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.RecordSnapshots;


public interface RecordSnapshotsRepository {
    RecordSnapshots findById(Integer id, List<String> fields_to_ignore, Connection con);
    
    RecordSnapshots findById(Integer id, Connection con);
    
    RecordSnapshots findById(Integer id, List<String> fields_to_ignore);
    
    RecordSnapshots findById(Integer id);
    
    RecordSnapshots insert(RecordSnapshots recordSnapshots, Connection con);
    
    RecordSnapshots insert(RecordSnapshots recordSnapshots);
    
    RecordSnapshots update(RecordSnapshots recordSnapshots, boolean exclude_nulls, Connection con);
    
    RecordSnapshots update(RecordSnapshots recordSnapshots, boolean exclude_nulls);
    
    RecordSnapshots save(RecordSnapshots recordSnapshots, Connection con);
    
    RecordSnapshots save(RecordSnapshots recordSnapshots);
    
    List<RecordSnapshots> findAll(List<String> fields_to_ignore, Connection con);
    
    List<RecordSnapshots> findAll(Connection con);
    
    List<RecordSnapshots> findAll(List<String> fields_to_ignore);
    
    List<RecordSnapshots> findAll();
    
    List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots, List<String> fields_to_ignore, Connection con);
    
    List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots, Connection con);
    
    List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots, List<String> fields_to_ignore);
    
    List<RecordSnapshots> findByModel(RecordSnapshots recordSnapshots);
    
    void delete(Integer id, Connection con);
    
    void delete(Integer id);
    
    void deleteByModel(RecordSnapshots recordSnapshots, Connection con);
    
    void deleteByModel(RecordSnapshots recordSnapshots);
}
