/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.MapHistory;


public interface MapHistoryRepository {
    MapHistory findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    MapHistory findByCode(Long code, Connection con);
    
    MapHistory findByCode(Long code, List<String> fields_to_ignore);
    
    MapHistory findByCode(Long code);
    
    MapHistory insert(MapHistory mapHistory, Connection con);
    
    MapHistory insert(MapHistory mapHistory);
    
    MapHistory update(MapHistory mapHistory, boolean exclude_nulls, Connection con);
    
    MapHistory update(MapHistory mapHistory, boolean exclude_nulls);
    
    MapHistory save(MapHistory mapHistory, Connection con);
    
    MapHistory save(MapHistory mapHistory);
    
    List<MapHistory> findAll(List<String> fields_to_ignore, Connection con);
    
    List<MapHistory> findAll(Connection con);
    
    List<MapHistory> findAll(List<String> fields_to_ignore);
    
    List<MapHistory> findAll();
    
    List<MapHistory> findByModel(MapHistory mapHistory, List<String> fields_to_ignore, Connection con);
    
    List<MapHistory> findByModel(MapHistory mapHistory, Connection con);
    
    List<MapHistory> findByModel(MapHistory mapHistory, List<String> fields_to_ignore);
    
    List<MapHistory> findByModel(MapHistory mapHistory);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(MapHistory mapHistory, Connection con);
    
    void deleteByModel(MapHistory mapHistory);
}
