/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.Psychologist;
import com.arc.utility.Sql2oUtility;


@Repository
public class PsychologistRepositoryImpl implements PsychologistRepository {
    private final static Logger logger = LoggerFactory.getLogger(PsychologistRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COMMENTS")) {
            res += "p.COMMENTS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "p.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DOCTOR_NAME")) {
            res += "p.DOCTOR_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "p.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("NEXT_DATE")) {
            res += "p.NEXT_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "p.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "p.SICK_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_DATE")) {
            res += "p.TREATMENT_DATE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public Psychologist findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + PsychologistRepositoryImpl.getSelectBase(fields_to_ignore) + "from PSYCHOLOGIST p ";
        sql += "where "; 
        sql += "ID = :id ";
        
        Psychologist res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(Psychologist.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public Psychologist findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public Psychologist findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public Psychologist findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<Psychologist> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + PsychologistRepositoryImpl.getSelectBase(fields_to_ignore) + "from PSYCHOLOGIST p ";
        
        List<Psychologist> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(Psychologist.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<Psychologist> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<Psychologist> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Psychologist> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<Psychologist> findByModel(Psychologist psychologist, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + PsychologistRepositoryImpl.getSelectBase(fields_to_ignore) + "from PSYCHOLOGIST p ";
        sql += "where ";
        
        if (psychologist.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (psychologist.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (psychologist.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name and ";
        }
        
        if (psychologist.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (psychologist.getNext_date() != null) { 
            sql += "NEXT_DATE = :next_date and ";
        }
        
        if (psychologist.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (psychologist.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (psychologist.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<Psychologist> res;
        
        try (Query query = con.createQuery(sql)) {
            if (psychologist.getComments() != null) {
                query.addParameter("comments", psychologist.getComments());
            }
            
            if (psychologist.getDate() != null) {
                query.addParameter("date", psychologist.getDate());
            }
            
            if (psychologist.getDoctor_name() != null) {
                query.addParameter("doctor_name", psychologist.getDoctor_name());
            }
            
            if (psychologist.getId() != null) {
                query.addParameter("id", psychologist.getId());
            }
            
            if (psychologist.getNext_date() != null) {
                query.addParameter("next_date", psychologist.getNext_date());
            }
            
            if (psychologist.getSick_id() != null) {
                query.addParameter("sick_id", psychologist.getSick_id());
            }
            
            if (psychologist.getSick_name() != null) {
                query.addParameter("sick_name", psychologist.getSick_name());
            }
            
            if (psychologist.getTreatment_date() != null) {
                query.addParameter("treatment_date", psychologist.getTreatment_date());
            }
            
            res = query.executeAndFetch(Psychologist.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<Psychologist> findByModel(Psychologist psychologist, Connection con) {
        return this.findByModel(psychologist, null, con);
    }
    
    @Override
    public List<Psychologist> findByModel(Psychologist psychologist, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(psychologist, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Psychologist> findByModel(Psychologist psychologist) {
        return this.findByModel(psychologist, (List<String>) null);
    }
    
    @Override
    public Psychologist insert(Psychologist psychologist, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into PSYCHOLOGIST ( " + 
                "COMMENTS, " + 
                "DATE, " + 
                "DOCTOR_NAME, " + 
                "ID, " + 
                "NEXT_DATE, " + 
                "SICK_ID, " + 
                "SICK_NAME, " + 
                "TREATMENT_DATE " + 
            ") " + 
            "values (" +
                ":comments, " + 
                ":date, " + 
                ":doctor_name, " + 
                ":id, " + 
                ":next_date, " + 
                ":sick_id, " + 
                ":sick_name, " + 
                ":treatment_date " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(psychologist);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("PSYCHOLOGIST", "ID", con, key, Long.class);
        psychologist.setId(res);
        logger.info("<< DB insert() - END");
        return psychologist;
    }
    
    @Override
    public Psychologist insert(Psychologist psychologist) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(psychologist, con);
            con.commit();
            return psychologist;
        }
    }
    
    @Override
    public Psychologist update(Psychologist psychologist, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + psychologist.getId());
        
        String sql = "update PSYCHOLOGIST set ";
        
        if (! exclude_nulls || psychologist.getComments() != null) { 
            sql += "COMMENTS = :comments, ";
        }
        
        if (! exclude_nulls || psychologist.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || psychologist.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name, ";
        }
        
        if (! exclude_nulls || psychologist.getNext_date() != null) { 
            sql += "NEXT_DATE = :next_date, ";
        }
        
        if (! exclude_nulls || psychologist.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || psychologist.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        if (! exclude_nulls || psychologist.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || psychologist.getComments() != null) {
                query.addParameter("comments", psychologist.getComments());
            }
            
            if (! exclude_nulls || psychologist.getDate() != null) {
                query.addParameter("date", psychologist.getDate());
            }
            
            if (! exclude_nulls || psychologist.getDoctor_name() != null) {
                query.addParameter("doctor_name", psychologist.getDoctor_name());
            }
            
            if (! exclude_nulls || psychologist.getId() != null) {
                query.addParameter("id", psychologist.getId());
            }
            
            if (! exclude_nulls || psychologist.getNext_date() != null) {
                query.addParameter("next_date", psychologist.getNext_date());
            }
            
            if (! exclude_nulls || psychologist.getSick_id() != null) {
                query.addParameter("sick_id", psychologist.getSick_id());
            }
            
            if (! exclude_nulls || psychologist.getSick_name() != null) {
                query.addParameter("sick_name", psychologist.getSick_name());
            }
            
            if (! exclude_nulls || psychologist.getTreatment_date() != null) {
                query.addParameter("treatment_date", psychologist.getTreatment_date());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return psychologist;
    }
    
    @Override
    public Psychologist update(Psychologist psychologist, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(psychologist, exclude_nulls, con);
            con.commit();
            return psychologist;
        }
    }
    
    @Override
    public Psychologist save(Psychologist psychologist, Connection con) {
        final Long id = psychologist.getId();

        final Psychologist psychologist2 = this.findById(id, null, con);
        
        if (psychologist2 == null) {
            return this.insert(psychologist, con);
        }
        return this.update(psychologist, false, con);
    }
    
    @Override
    public Psychologist save(Psychologist psychologist) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(psychologist, con);
            con.commit();
            return psychologist;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from PSYCHOLOGIST ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(Psychologist psychologist, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from PSYCHOLOGIST ";
        sql += "where ";
        
        if (psychologist.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (psychologist.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (psychologist.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name and ";
        }
        
        if (psychologist.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (psychologist.getNext_date() != null) { 
            sql += "NEXT_DATE = :next_date and ";
        }
        
        if (psychologist.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (psychologist.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (psychologist.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (psychologist.getComments() != null) {
                query.addParameter("comments", psychologist.getComments());
            }
            
            if (psychologist.getDate() != null) {
                query.addParameter("date", psychologist.getDate());
            }
            
            if (psychologist.getDoctor_name() != null) {
                query.addParameter("doctor_name", psychologist.getDoctor_name());
            }
            
            if (psychologist.getId() != null) {
                query.addParameter("id", psychologist.getId());
            }
            
            if (psychologist.getNext_date() != null) {
                query.addParameter("next_date", psychologist.getNext_date());
            }
            
            if (psychologist.getSick_id() != null) {
                query.addParameter("sick_id", psychologist.getSick_id());
            }
            
            if (psychologist.getSick_name() != null) {
                query.addParameter("sick_name", psychologist.getSick_name());
            }
            
            if (psychologist.getTreatment_date() != null) {
                query.addParameter("treatment_date", psychologist.getTreatment_date());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(Psychologist psychologist) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(psychologist, con);
            con.commit();
        }
    }
}
