/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.SickHistory;
import com.arc.utility.Sql2oUtility;


@Repository
public class SickHistoryRepositoryImpl implements SickHistoryRepository {
    private final static Logger logger = LoggerFactory.getLogger(SickHistoryRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ACCOUNT_STATE")) {
            res += "s.ACCOUNT_STATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("AMOUNT")) {
            res += "s.AMOUNT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CREDIT")) {
            res += "s.CREDIT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "s.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DEBIT")) {
            res += "s.DEBIT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DESCRIPTION")) {
            res += "s.DESCRIPTION, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "s.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("RECEIPT_ID")) {
            res += "s.RECEIPT_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "s.SICK_ID, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public SickHistory findByIds(Long id, String sick_id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByIds() - id: " + id + "sick_id: " + sick_id);
        
        String sql = "select " + SickHistoryRepositoryImpl.getSelectBase(fields_to_ignore) + "from SICK_HISTORY s ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "SICK_ID = :sick_id ";
        
        SickHistory res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);
            query.addParameter("sick_id", sick_id);

            res = query.executeAndFetchFirst(SickHistory.class);
        }
        
        logger.debug("<< DB getByIds() - END");
        return res;
    }
    
    @Override
    public SickHistory findByIds(Long id, String sick_id, Connection con) {
        return this.findByIds(id, sick_id, null, con);
    }
    
    @Override
    public SickHistory findByIds(Long id, String sick_id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByIds(id, sick_id, fields_to_ignore, con);
        }
    }
    
    @Override
    public SickHistory findByIds(Long id, String sick_id) {
        return this.findByIds(id, sick_id, (List<String>) null);
    }
    
    @Override
    public List<SickHistory> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + SickHistoryRepositoryImpl.getSelectBase(fields_to_ignore) + "from SICK_HISTORY s ";
        
        List<SickHistory> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(SickHistory.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<SickHistory> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<SickHistory> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<SickHistory> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<SickHistory> findByModel(SickHistory sickHistory, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + SickHistoryRepositoryImpl.getSelectBase(fields_to_ignore) + "from SICK_HISTORY s ";
        sql += "where ";
        
        if (sickHistory.getAccount_state() != null) { 
            sql += "ACCOUNT_STATE = :account_state and ";
        }
        
        if (sickHistory.getAmount() != null) { 
            sql += "AMOUNT = :amount and ";
        }
        
        if (sickHistory.getCredit() != null) { 
            sql += "CREDIT = :credit and ";
        }
        
        if (sickHistory.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (sickHistory.getDebit() != null) { 
            sql += "DEBIT = :debit and ";
        }
        
        if (sickHistory.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (sickHistory.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (sickHistory.getReceipt_id() != null) { 
            sql += "RECEIPT_ID = :receipt_id and ";
        }
        
        if (sickHistory.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<SickHistory> res;
        
        try (Query query = con.createQuery(sql)) {
            if (sickHistory.getAccount_state() != null) {
                query.addParameter("account_state", sickHistory.getAccount_state());
            }
            
            if (sickHistory.getAmount() != null) {
                query.addParameter("amount", sickHistory.getAmount());
            }
            
            if (sickHistory.getCredit() != null) {
                query.addParameter("credit", sickHistory.getCredit());
            }
            
            if (sickHistory.getDate() != null) {
                query.addParameter("date", sickHistory.getDate());
            }
            
            if (sickHistory.getDebit() != null) {
                query.addParameter("debit", sickHistory.getDebit());
            }
            
            if (sickHistory.getDescription() != null) {
                query.addParameter("description", sickHistory.getDescription());
            }
            
            if (sickHistory.getId() != null) {
                query.addParameter("id", sickHistory.getId());
            }
            
            if (sickHistory.getReceipt_id() != null) {
                query.addParameter("receipt_id", sickHistory.getReceipt_id());
            }
            
            if (sickHistory.getSick_id() != null) {
                query.addParameter("sick_id", sickHistory.getSick_id());
            }
            
            res = query.executeAndFetch(SickHistory.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<SickHistory> findByModel(SickHistory sickHistory, Connection con) {
        return this.findByModel(sickHistory, null, con);
    }
    
    @Override
    public List<SickHistory> findByModel(SickHistory sickHistory, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(sickHistory, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<SickHistory> findByModel(SickHistory sickHistory) {
        return this.findByModel(sickHistory, (List<String>) null);
    }
    
    @Override
    public SickHistory insert(SickHistory sickHistory, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into SICK_HISTORY ( " + 
                "ACCOUNT_STATE, " + 
                "AMOUNT, " + 
                "CREDIT, " + 
                "DATE, " + 
                "DEBIT, " + 
                "DESCRIPTION, " + 
                "ID, " + 
                "RECEIPT_ID, " + 
                "SICK_ID " + 
            ") " + 
            "values (" +
                ":account_state, " + 
                ":amount, " + 
                ":credit, " + 
                ":date, " + 
                ":debit, " + 
                ":description, " + 
                ":id, " + 
                ":receipt_id, " + 
                ":sick_id " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(sickHistory);

            key = query.executeUpdate().getKey();
        }
        

        logger.info("<< DB insert() - END");
        return sickHistory;
    }
    
    @Override
    public SickHistory insert(SickHistory sickHistory) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(sickHistory, con);
            con.commit();
            return sickHistory;
        }
    }
    
    @Override
    public SickHistory update(SickHistory sickHistory, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + sickHistory.getId() + "sick_id: " + sickHistory.getSick_id());
        
        String sql = "update SICK_HISTORY set ";
        
        if (! exclude_nulls || sickHistory.getAccount_state() != null) { 
            sql += "ACCOUNT_STATE = :account_state, ";
        }
        
        if (! exclude_nulls || sickHistory.getAmount() != null) { 
            sql += "AMOUNT = :amount, ";
        }
        
        if (! exclude_nulls || sickHistory.getCredit() != null) { 
            sql += "CREDIT = :credit, ";
        }
        
        if (! exclude_nulls || sickHistory.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || sickHistory.getDebit() != null) { 
            sql += "DEBIT = :debit, ";
        }
        
        if (! exclude_nulls || sickHistory.getDescription() != null) { 
            sql += "DESCRIPTION = :description, ";
        }
        
        if (! exclude_nulls || sickHistory.getReceipt_id() != null) { 
            sql += "RECEIPT_ID = :receipt_id, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "SICK_ID = :sick_id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || sickHistory.getAccount_state() != null) {
                query.addParameter("account_state", sickHistory.getAccount_state());
            }
            
            if (! exclude_nulls || sickHistory.getAmount() != null) {
                query.addParameter("amount", sickHistory.getAmount());
            }
            
            if (! exclude_nulls || sickHistory.getCredit() != null) {
                query.addParameter("credit", sickHistory.getCredit());
            }
            
            if (! exclude_nulls || sickHistory.getDate() != null) {
                query.addParameter("date", sickHistory.getDate());
            }
            
            if (! exclude_nulls || sickHistory.getDebit() != null) {
                query.addParameter("debit", sickHistory.getDebit());
            }
            
            if (! exclude_nulls || sickHistory.getDescription() != null) {
                query.addParameter("description", sickHistory.getDescription());
            }
            
            if (! exclude_nulls || sickHistory.getId() != null) {
                query.addParameter("id", sickHistory.getId());
            }
            
            if (! exclude_nulls || sickHistory.getReceipt_id() != null) {
                query.addParameter("receipt_id", sickHistory.getReceipt_id());
            }
            
            if (! exclude_nulls || sickHistory.getSick_id() != null) {
                query.addParameter("sick_id", sickHistory.getSick_id());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return sickHistory;
    }
    
    @Override
    public SickHistory update(SickHistory sickHistory, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(sickHistory, exclude_nulls, con);
            con.commit();
            return sickHistory;
        }
    }
    
    @Override
    public SickHistory save(SickHistory sickHistory, Connection con) {
        final Long id = sickHistory.getId();
        final String sick_id = sickHistory.getSick_id();

        final SickHistory sickHistory2 = this.findByIds(id, sick_id, null, con);
        
        if (sickHistory2 == null) {
            return this.insert(sickHistory, con);
        }
        return this.update(sickHistory, false, con);
    }
    
    @Override
    public SickHistory save(SickHistory sickHistory) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(sickHistory, con);
            con.commit();
            return sickHistory;
        }
    }
    
    @Override
    public void delete(Long id, String sick_id, Connection con) {
        logger.info("DB>> delete() - id: " + id + "sick_id: " + sick_id);
        
        String sql = "delete from SICK_HISTORY ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "SICK_ID = :sick_id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);
            query.addParameter("sick_id", sick_id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id, String sick_id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, sick_id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(SickHistory sickHistory, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from SICK_HISTORY ";
        sql += "where ";
        
        if (sickHistory.getAccount_state() != null) { 
            sql += "ACCOUNT_STATE = :account_state and ";
        }
        
        if (sickHistory.getAmount() != null) { 
            sql += "AMOUNT = :amount and ";
        }
        
        if (sickHistory.getCredit() != null) { 
            sql += "CREDIT = :credit and ";
        }
        
        if (sickHistory.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (sickHistory.getDebit() != null) { 
            sql += "DEBIT = :debit and ";
        }
        
        if (sickHistory.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (sickHistory.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (sickHistory.getReceipt_id() != null) { 
            sql += "RECEIPT_ID = :receipt_id and ";
        }
        
        if (sickHistory.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (sickHistory.getAccount_state() != null) {
                query.addParameter("account_state", sickHistory.getAccount_state());
            }
            
            if (sickHistory.getAmount() != null) {
                query.addParameter("amount", sickHistory.getAmount());
            }
            
            if (sickHistory.getCredit() != null) {
                query.addParameter("credit", sickHistory.getCredit());
            }
            
            if (sickHistory.getDate() != null) {
                query.addParameter("date", sickHistory.getDate());
            }
            
            if (sickHistory.getDebit() != null) {
                query.addParameter("debit", sickHistory.getDebit());
            }
            
            if (sickHistory.getDescription() != null) {
                query.addParameter("description", sickHistory.getDescription());
            }
            
            if (sickHistory.getId() != null) {
                query.addParameter("id", sickHistory.getId());
            }
            
            if (sickHistory.getReceipt_id() != null) {
                query.addParameter("receipt_id", sickHistory.getReceipt_id());
            }
            
            if (sickHistory.getSick_id() != null) {
                query.addParameter("sick_id", sickHistory.getSick_id());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(SickHistory sickHistory) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(sickHistory, con);
            con.commit();
        }
    }
}
