/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.GeneralSetting;


public interface GeneralSettingRepository {
    GeneralSetting findByPay_type(String pay_type, List<String> fields_to_ignore, Connection con);
    
    GeneralSetting findByPay_type(String pay_type, Connection con);
    
    GeneralSetting findByPay_type(String pay_type, List<String> fields_to_ignore);
    
    GeneralSetting findByPay_type(String pay_type);
    
    GeneralSetting insert(GeneralSetting generalSetting, Connection con);
    
    GeneralSetting insert(GeneralSetting generalSetting);
    
    GeneralSetting update(GeneralSetting generalSetting, boolean exclude_nulls, Connection con);
    
    GeneralSetting update(GeneralSetting generalSetting, boolean exclude_nulls);
    
    GeneralSetting save(GeneralSetting generalSetting, Connection con);
    
    GeneralSetting save(GeneralSetting generalSetting);
    
    List<GeneralSetting> findAll(List<String> fields_to_ignore, Connection con);
    
    List<GeneralSetting> findAll(Connection con);
    
    List<GeneralSetting> findAll(List<String> fields_to_ignore);
    
    List<GeneralSetting> findAll();
    
    List<GeneralSetting> findByModel(GeneralSetting generalSetting, List<String> fields_to_ignore, Connection con);
    
    List<GeneralSetting> findByModel(GeneralSetting generalSetting, Connection con);
    
    List<GeneralSetting> findByModel(GeneralSetting generalSetting, List<String> fields_to_ignore);
    
    List<GeneralSetting> findByModel(GeneralSetting generalSetting);
    
    void delete(String pay_type, Connection con);
    
    void delete(String pay_type);
    
    void deleteByModel(GeneralSetting generalSetting, Connection con);
    
    void deleteByModel(GeneralSetting generalSetting);
}
