/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.DispenseDaily;
import com.arc.utility.Sql2oUtility;


@Repository
public class DispenseDailyRepositoryImpl implements DispenseDailyRepository {
    private final static Logger logger = LoggerFactory.getLogger(DispenseDailyRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COUNT")) {
            res += "d.COUNT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "d.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DISPENSE_DATE")) {
            res += "d.DISPENSE_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DISPENSE_DAY")) {
            res += "d.DISPENSE_DAY, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DRUG_NAME")) {
            res += "d.DRUG_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "d.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "d.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "d.SICK_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_METHOD")) {
            res += "d.TREATMENT_METHOD, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public DispenseDaily findByIds(Long id, String sick_id, String date, String drug_name, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByIds() - id: " + id + "sick_id: " + sick_id + "date: " + date + "drug_name: " + drug_name);
        
        String sql = "select " + DispenseDailyRepositoryImpl.getSelectBase(fields_to_ignore) + "from DISPENSES_DAILY d ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "SICK_ID = :sick_id and "; 
        sql += "DATE = :date and "; 
        sql += "DRUG_NAME = :drug_name ";
        
        DispenseDaily res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);
            query.addParameter("sick_id", sick_id);
            query.addParameter("date", date);
            query.addParameter("drug_name", drug_name);

            res = query.executeAndFetchFirst(DispenseDaily.class);
        }
        
        logger.debug("<< DB getByIds() - END");
        return res;
    }
    
    @Override
    public DispenseDaily findByIds(Long id, String sick_id, String date, String drug_name, Connection con) {
        return this.findByIds(id, sick_id, date, drug_name, null, con);
    }
    
    @Override
    public DispenseDaily findByIds(Long id, String sick_id, String date, String drug_name, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByIds(id, sick_id, date, drug_name, fields_to_ignore, con);
        }
    }
    
    @Override
    public DispenseDaily findByIds(Long id, String sick_id, String date, String drug_name) {
        return this.findByIds(id, sick_id, date, drug_name, (List<String>) null);
    }
    
    @Override
    public List<DispenseDaily> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + DispenseDailyRepositoryImpl.getSelectBase(fields_to_ignore) + "from DISPENSES_DAILY d ";
        
        List<DispenseDaily> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(DispenseDaily.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<DispenseDaily> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<DispenseDaily> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<DispenseDaily> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<DispenseDaily> findByModel(DispenseDaily dispenseDaily, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + DispenseDailyRepositoryImpl.getSelectBase(fields_to_ignore) + "from DISPENSES_DAILY d ";
        sql += "where ";
        
        if (dispenseDaily.getCount() != null) { 
            sql += "COUNT = :count and ";
        }
        
        if (dispenseDaily.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (dispenseDaily.getDispense_date() != null) { 
            sql += "DISPENSE_DATE = :dispense_date and ";
        }
        
        if (dispenseDaily.getDispense_day() != null) { 
            sql += "DISPENSE_DAY = :dispense_day and ";
        }
        
        if (dispenseDaily.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (dispenseDaily.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (dispenseDaily.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (dispenseDaily.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (dispenseDaily.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<DispenseDaily> res;
        
        try (Query query = con.createQuery(sql)) {
            if (dispenseDaily.getCount() != null) {
                query.addParameter("count", dispenseDaily.getCount());
            }
            
            if (dispenseDaily.getDate() != null) {
                query.addParameter("date", dispenseDaily.getDate());
            }
            
            if (dispenseDaily.getDispense_date() != null) {
                query.addParameter("dispense_date", dispenseDaily.getDispense_date());
            }
            
            if (dispenseDaily.getDispense_day() != null) {
                query.addParameter("dispense_day", dispenseDaily.getDispense_day());
            }
            
            if (dispenseDaily.getDrug_name() != null) {
                query.addParameter("drug_name", dispenseDaily.getDrug_name());
            }
            
            if (dispenseDaily.getId() != null) {
                query.addParameter("id", dispenseDaily.getId());
            }
            
            if (dispenseDaily.getSick_id() != null) {
                query.addParameter("sick_id", dispenseDaily.getSick_id());
            }
            
            if (dispenseDaily.getSick_name() != null) {
                query.addParameter("sick_name", dispenseDaily.getSick_name());
            }
            
            if (dispenseDaily.getTreatment_method() != null) {
                query.addParameter("treatment_method", dispenseDaily.getTreatment_method());
            }
            
            res = query.executeAndFetch(DispenseDaily.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<DispenseDaily> findByModel(DispenseDaily dispenseDaily, Connection con) {
        return this.findByModel(dispenseDaily, null, con);
    }
    
    @Override
    public List<DispenseDaily> findByModel(DispenseDaily dispenseDaily, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(dispenseDaily, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<DispenseDaily> findByModel(DispenseDaily dispenseDaily) {
        return this.findByModel(dispenseDaily, (List<String>) null);
    }
    
    @Override
    public DispenseDaily insert(DispenseDaily dispenseDaily, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into DISPENSES_DAILY ( " + 
                "COUNT, " + 
                "DATE, " + 
                "DISPENSE_DATE, " + 
                "DISPENSE_DAY, " + 
                "DRUG_NAME, " + 
                "ID, " + 
                "SICK_ID, " + 
                "SICK_NAME, " + 
                "TREATMENT_METHOD " + 
            ") " + 
            "values (" +
                ":count, " + 
                ":date, " + 
                ":dispense_date, " + 
                ":dispense_day, " + 
                ":drug_name, " + 
                ":id, " + 
                ":sick_id, " + 
                ":sick_name, " + 
                ":treatment_method " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(dispenseDaily);

            key = query.executeUpdate().getKey();
        }
        

        logger.info("<< DB insert() - END");
        return dispenseDaily;
    }
    
    @Override
    public DispenseDaily insert(DispenseDaily dispenseDaily) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(dispenseDaily, con);
            con.commit();
            return dispenseDaily;
        }
    }
    
    @Override
    public DispenseDaily update(DispenseDaily dispenseDaily, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + dispenseDaily.getId() + "sick_id: " + dispenseDaily.getSick_id() + "date: " + dispenseDaily.getDate() + "drug_name: " + dispenseDaily.getDrug_name());
        
        String sql = "update DISPENSES_DAILY set ";
        
        if (! exclude_nulls || dispenseDaily.getCount() != null) { 
            sql += "COUNT = :count, ";
        }
        
        if (! exclude_nulls || dispenseDaily.getDispense_date() != null) { 
            sql += "DISPENSE_DATE = :dispense_date, ";
        }
        
        if (! exclude_nulls || dispenseDaily.getDispense_day() != null) { 
            sql += "DISPENSE_DAY = :dispense_day, ";
        }
        
        if (! exclude_nulls || dispenseDaily.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        if (! exclude_nulls || dispenseDaily.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "SICK_ID = :sick_id and "; 
        sql += "DATE = :date and "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || dispenseDaily.getCount() != null) {
                query.addParameter("count", dispenseDaily.getCount());
            }
            
            if (! exclude_nulls || dispenseDaily.getDate() != null) {
                query.addParameter("date", dispenseDaily.getDate());
            }
            
            if (! exclude_nulls || dispenseDaily.getDispense_date() != null) {
                query.addParameter("dispense_date", dispenseDaily.getDispense_date());
            }
            
            if (! exclude_nulls || dispenseDaily.getDispense_day() != null) {
                query.addParameter("dispense_day", dispenseDaily.getDispense_day());
            }
            
            if (! exclude_nulls || dispenseDaily.getDrug_name() != null) {
                query.addParameter("drug_name", dispenseDaily.getDrug_name());
            }
            
            if (! exclude_nulls || dispenseDaily.getId() != null) {
                query.addParameter("id", dispenseDaily.getId());
            }
            
            if (! exclude_nulls || dispenseDaily.getSick_id() != null) {
                query.addParameter("sick_id", dispenseDaily.getSick_id());
            }
            
            if (! exclude_nulls || dispenseDaily.getSick_name() != null) {
                query.addParameter("sick_name", dispenseDaily.getSick_name());
            }
            
            if (! exclude_nulls || dispenseDaily.getTreatment_method() != null) {
                query.addParameter("treatment_method", dispenseDaily.getTreatment_method());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return dispenseDaily;
    }
    
    @Override
    public DispenseDaily update(DispenseDaily dispenseDaily, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(dispenseDaily, exclude_nulls, con);
            con.commit();
            return dispenseDaily;
        }
    }
    
    @Override
    public DispenseDaily save(DispenseDaily dispenseDaily, Connection con) {
        final Long id = dispenseDaily.getId();
        final String sick_id = dispenseDaily.getSick_id();
        final String date = dispenseDaily.getDate();
        final String drug_name = dispenseDaily.getDrug_name();

        final DispenseDaily dispenseDaily2 = this.findByIds(id, sick_id, date, drug_name, null, con);
        
        if (dispenseDaily2 == null) {
            return this.insert(dispenseDaily, con);
        }
        return this.update(dispenseDaily, false, con);
    }
    
    @Override
    public DispenseDaily save(DispenseDaily dispenseDaily) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(dispenseDaily, con);
            con.commit();
            return dispenseDaily;
        }
    }
    
    @Override
    public void delete(Long id, String sick_id, String date, String drug_name, Connection con) {
        logger.info("DB>> delete() - id: " + id + "sick_id: " + sick_id + "date: " + date + "drug_name: " + drug_name);
        
        String sql = "delete from DISPENSES_DAILY ";
        sql += "where "; 
        sql += "ID = :id and "; 
        sql += "SICK_ID = :sick_id and "; 
        sql += "DATE = :date and "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);
            query.addParameter("sick_id", sick_id);
            query.addParameter("date", date);
            query.addParameter("drug_name", drug_name);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id, String sick_id, String date, String drug_name) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, sick_id, date, drug_name, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(DispenseDaily dispenseDaily, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from DISPENSES_DAILY ";
        sql += "where ";
        
        if (dispenseDaily.getCount() != null) { 
            sql += "COUNT = :count and ";
        }
        
        if (dispenseDaily.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (dispenseDaily.getDispense_date() != null) { 
            sql += "DISPENSE_DATE = :dispense_date and ";
        }
        
        if (dispenseDaily.getDispense_day() != null) { 
            sql += "DISPENSE_DAY = :dispense_day and ";
        }
        
        if (dispenseDaily.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (dispenseDaily.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (dispenseDaily.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (dispenseDaily.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (dispenseDaily.getTreatment_method() != null) { 
            sql += "TREATMENT_METHOD = :treatment_method and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (dispenseDaily.getCount() != null) {
                query.addParameter("count", dispenseDaily.getCount());
            }
            
            if (dispenseDaily.getDate() != null) {
                query.addParameter("date", dispenseDaily.getDate());
            }
            
            if (dispenseDaily.getDispense_date() != null) {
                query.addParameter("dispense_date", dispenseDaily.getDispense_date());
            }
            
            if (dispenseDaily.getDispense_day() != null) {
                query.addParameter("dispense_day", dispenseDaily.getDispense_day());
            }
            
            if (dispenseDaily.getDrug_name() != null) {
                query.addParameter("drug_name", dispenseDaily.getDrug_name());
            }
            
            if (dispenseDaily.getId() != null) {
                query.addParameter("id", dispenseDaily.getId());
            }
            
            if (dispenseDaily.getSick_id() != null) {
                query.addParameter("sick_id", dispenseDaily.getSick_id());
            }
            
            if (dispenseDaily.getSick_name() != null) {
                query.addParameter("sick_name", dispenseDaily.getSick_name());
            }
            
            if (dispenseDaily.getTreatment_method() != null) {
                query.addParameter("treatment_method", dispenseDaily.getTreatment_method());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(DispenseDaily dispenseDaily) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(dispenseDaily, con);
            con.commit();
        }
    }
}
