/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.ActionLog;


public interface ActionLogRepository {
    ActionLog findById(Long id, List<String> fields_to_ignore, Connection con);
    
    ActionLog findById(Long id, Connection con);
    
    ActionLog findById(Long id, List<String> fields_to_ignore);
    
    ActionLog findById(Long id);
    
    ActionLog insert(ActionLog actionLog, Connection con);
    
    ActionLog insert(ActionLog actionLog);
    
    ActionLog update(ActionLog actionLog, boolean exclude_nulls, Connection con);
    
    ActionLog update(ActionLog actionLog, boolean exclude_nulls);
    
    ActionLog save(ActionLog actionLog, Connection con);
    
    ActionLog save(ActionLog actionLog);
    
    List<ActionLog> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ActionLog> findAll(Connection con);
    
    List<ActionLog> findAll(List<String> fields_to_ignore);
    
    List<ActionLog> findAll();
    
    List<ActionLog> findByModel(ActionLog actionLog, List<String> fields_to_ignore, Connection con);
    
    List<ActionLog> findByModel(ActionLog actionLog, Connection con);
    
    List<ActionLog> findByModel(ActionLog actionLog, List<String> fields_to_ignore);
    
    List<ActionLog> findByModel(ActionLog actionLog);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(ActionLog actionLog, Connection con);
    
    void deleteByModel(ActionLog actionLog);
}
