/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.Interview;


public interface InterviewRepository {
    Interview findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    Interview findByCode(Long code, Connection con);
    
    Interview findByCode(Long code, List<String> fields_to_ignore);
    
    Interview findByCode(Long code);
    
    Interview insert(Interview interview, Connection con);
    
    Interview insert(Interview interview);
    
    Interview update(Interview interview, boolean exclude_nulls, Connection con);
    
    Interview update(Interview interview, boolean exclude_nulls);
    
    Interview save(Interview interview, Connection con);
    
    Interview save(Interview interview);
    
    List<Interview> findAll(List<String> fields_to_ignore, Connection con);
    
    List<Interview> findAll(Connection con);
    
    List<Interview> findAll(List<String> fields_to_ignore);
    
    List<Interview> findAll();
    
    List<Interview> findByModel(Interview interview, List<String> fields_to_ignore, Connection con);
    
    List<Interview> findByModel(Interview interview, Connection con);
    
    List<Interview> findByModel(Interview interview, List<String> fields_to_ignore);
    
    List<Interview> findByModel(Interview interview);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(Interview interview, Connection con);
    
    void deleteByModel(Interview interview);
}
