/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.ExpenseTypeAggregator;
import com.arc.model.ExpenseType;
import com.arc.repository.ExpenseTypeRepository;


@Service
public class ExpenseTypeServiceImpl implements ExpenseTypeService {
    @Autowired
    private ExpenseTypeRepository expenseTypeRepository;
    
    private ExpenseTypeAggregator enrich(ExpenseType expenseType) {
        ExpenseTypeAggregator expenseTypeAggregator = null;
        
        if (expenseType != null) {
            expenseTypeAggregator = new ExpenseTypeAggregator();
            
            expenseTypeAggregator.setExpenseType(expenseType);
        }
        
        return expenseTypeAggregator;
    }
    
    private List<ExpenseTypeAggregator> enrich(List<ExpenseType> expenseTypes) {
        final List<ExpenseTypeAggregator> expenseTypeAggregators = new ArrayList<>();
        
        if (expenseTypes != null) {
            for (ExpenseType expenseType: expenseTypes) {
                expenseTypeAggregators.add(this.enrich(expenseType));
            }
        }
        
        return expenseTypeAggregators;
    }
    
    @Override
    public List<ExpenseTypeAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findAll(Connection con) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findAll(con);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findAll(List<String> fields_to_ignore) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findAll(fields_to_ignore);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findAll() {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findAll();
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType, List<String> fields_to_ignore, Connection con) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findByModel(expenseType, fields_to_ignore, con);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType, Connection con) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findByModel(expenseType, con);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType, List<String> fields_to_ignore) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findByModel(expenseType, fields_to_ignore);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType) {
        final List<ExpenseType> expenseTypes = this.expenseTypeRepository.findByModel(expenseType);
        
        return this.enrich(expenseTypes);
    }
    
    @Override
    public ExpenseTypeAggregator findById(Long id, List<String> fields_to_ignore, Connection con) {
        final ExpenseType expenseType = this.expenseTypeRepository.findById(id, fields_to_ignore, con);
        
        return this.enrich(expenseType);
    }
    
    @Override
    public ExpenseTypeAggregator findById(Long id, Connection con) {
        final ExpenseType expenseType = this.expenseTypeRepository.findById(id, con);
        
        return this.enrich(expenseType);
    }
    
    @Override
    public ExpenseTypeAggregator findById(Long id, List<String> fields_to_ignore) {
        final ExpenseType expenseType = this.expenseTypeRepository.findById(id, fields_to_ignore);
        
        return this.enrich(expenseType);
    }
    
    @Override
    public ExpenseTypeAggregator findById(Long id) {
        final ExpenseType expenseType = this.expenseTypeRepository.findById(id);
        
        return this.enrich(expenseType);
    }
    
    @Override
    public ExpenseType insert(ExpenseType expenseType, Connection con) {
        return this.expenseTypeRepository.insert(expenseType, con);
    }
    
    @Override
    public ExpenseType insert(ExpenseType expenseType) {
        return this.expenseTypeRepository.insert(expenseType);
    }
    
    @Override
    public ExpenseType update(ExpenseType expenseType, boolean exclude_nulls, Connection con) {
        return this.expenseTypeRepository.update(expenseType, exclude_nulls, con);
    }
    
    @Override
    public ExpenseType update(ExpenseType expenseType, boolean exclude_nulls) {
        return this.expenseTypeRepository.update(expenseType, exclude_nulls);
    }
    
    @Override
    public ExpenseType save(ExpenseType expenseType, Connection con) {
        return this.expenseTypeRepository.save(expenseType, con);
    }
    
    @Override
    public ExpenseType save(ExpenseType expenseType) {
        return this.expenseTypeRepository.save(expenseType);
    }
    
    @Override
    public void delete(Long id, Connection con) {
        this.expenseTypeRepository.delete(id, con);
    }
    
    @Override
    public void delete(Long id) {
        this.expenseTypeRepository.delete(id);
    }
    
    @Override
    public void deleteByModel(ExpenseType expenseType, Connection con) {
        this.expenseTypeRepository.deleteByModel(expenseType, con);
    }
    
    @Override
    public void deleteByModel(ExpenseType expenseType) {
        this.expenseTypeRepository.deleteByModel(expenseType);
    }
}
