/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.PrescriptionReal;
import com.arc.utility.Sql2oUtility;


@Repository
public class PrescriptionRealRepositoryImpl implements PrescriptionRealRepository {
    private final static Logger logger = LoggerFactory.getLogger(PrescriptionRealRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CODE")) {
            res += "p.CODE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "p.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DOCTOR_NAME")) {
            res += "p.DOCTOR_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("PRESCRIPTION_TEXT")) {
            res += "p.PRESCRIPTION_TEXT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "p.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "p.SICK_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TEST")) {
            res += "p.TEST, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_DATE")) {
            res += "p.TREATMENT_DATE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public PrescriptionReal findByCode(Long code, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByCode() - code: " + code);
        
        String sql = "select " + PrescriptionRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from PRESCRIPTIONS_REAL p ";
        sql += "where "; 
        sql += "CODE = :code ";
        
        PrescriptionReal res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("code", code);

            res = query.executeAndFetchFirst(PrescriptionReal.class);
        }
        
        logger.debug("<< DB getByCode() - END");
        return res;
    }
    
    @Override
    public PrescriptionReal findByCode(Long code, Connection con) {
        return this.findByCode(code, null, con);
    }
    
    @Override
    public PrescriptionReal findByCode(Long code, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByCode(code, fields_to_ignore, con);
        }
    }
    
    @Override
    public PrescriptionReal findByCode(Long code) {
        return this.findByCode(code, (List<String>) null);
    }
    
    @Override
    public List<PrescriptionReal> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + PrescriptionRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from PRESCRIPTIONS_REAL p ";
        
        List<PrescriptionReal> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(PrescriptionReal.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<PrescriptionReal> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<PrescriptionReal> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<PrescriptionReal> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<PrescriptionReal> findByModel(PrescriptionReal prescriptionReal, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + PrescriptionRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from PRESCRIPTIONS_REAL p ";
        sql += "where ";
        
        if (prescriptionReal.getCode() != null) { 
            sql += "CODE = :code and ";
        }
        
        if (prescriptionReal.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (prescriptionReal.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name and ";
        }
        
        if (prescriptionReal.getPrescription_text() != null) { 
            sql += "PRESCRIPTION_TEXT = :prescription_text and ";
        }
        
        if (prescriptionReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (prescriptionReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (prescriptionReal.getTest() != null) { 
            sql += "TEST = :test and ";
        }
        
        if (prescriptionReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<PrescriptionReal> res;
        
        try (Query query = con.createQuery(sql)) {
            if (prescriptionReal.getCode() != null) {
                query.addParameter("code", prescriptionReal.getCode());
            }
            
            if (prescriptionReal.getDate() != null) {
                query.addParameter("date", prescriptionReal.getDate());
            }
            
            if (prescriptionReal.getDoctor_name() != null) {
                query.addParameter("doctor_name", prescriptionReal.getDoctor_name());
            }
            
            if (prescriptionReal.getPrescription_text() != null) {
                query.addParameter("prescription_text", prescriptionReal.getPrescription_text());
            }
            
            if (prescriptionReal.getSick_id() != null) {
                query.addParameter("sick_id", prescriptionReal.getSick_id());
            }
            
            if (prescriptionReal.getSick_name() != null) {
                query.addParameter("sick_name", prescriptionReal.getSick_name());
            }
            
            if (prescriptionReal.getTest() != null) {
                query.addParameter("test", prescriptionReal.getTest());
            }
            
            if (prescriptionReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", prescriptionReal.getTreatment_date());
            }
            
            res = query.executeAndFetch(PrescriptionReal.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<PrescriptionReal> findByModel(PrescriptionReal prescriptionReal, Connection con) {
        return this.findByModel(prescriptionReal, null, con);
    }
    
    @Override
    public List<PrescriptionReal> findByModel(PrescriptionReal prescriptionReal, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(prescriptionReal, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<PrescriptionReal> findByModel(PrescriptionReal prescriptionReal) {
        return this.findByModel(prescriptionReal, (List<String>) null);
    }
    
    @Override
    public PrescriptionReal insert(PrescriptionReal prescriptionReal, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into PRESCRIPTIONS_REAL ( " + 
                "CODE, " + 
                "DATE, " + 
                "DOCTOR_NAME, " + 
                "PRESCRIPTION_TEXT, " + 
                "SICK_ID, " + 
                "SICK_NAME, " + 
                "TEST, " + 
                "TREATMENT_DATE " + 
            ") " + 
            "values (" +
                ":code, " + 
                ":date, " + 
                ":doctor_name, " + 
                ":prescription_text, " + 
                ":sick_id, " + 
                ":sick_name, " + 
                ":test, " + 
                ":treatment_date " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(prescriptionReal);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("PRESCRIPTIONS_REAL", "CODE", con, key, Long.class);
        prescriptionReal.setCode(res);
        logger.info("<< DB insert() - END");
        return prescriptionReal;
    }
    
    @Override
    public PrescriptionReal insert(PrescriptionReal prescriptionReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(prescriptionReal, con);
            con.commit();
            return prescriptionReal;
        }
    }
    
    @Override
    public PrescriptionReal update(PrescriptionReal prescriptionReal, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - code: " + prescriptionReal.getCode());
        
        String sql = "update PRESCRIPTIONS_REAL set ";
        
        if (! exclude_nulls || prescriptionReal.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || prescriptionReal.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name, ";
        }
        
        if (! exclude_nulls || prescriptionReal.getPrescription_text() != null) { 
            sql += "PRESCRIPTION_TEXT = :prescription_text, ";
        }
        
        if (! exclude_nulls || prescriptionReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || prescriptionReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        if (! exclude_nulls || prescriptionReal.getTest() != null) { 
            sql += "TEST = :test, ";
        }
        
        if (! exclude_nulls || prescriptionReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "CODE = :code ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || prescriptionReal.getCode() != null) {
                query.addParameter("code", prescriptionReal.getCode());
            }
            
            if (! exclude_nulls || prescriptionReal.getDate() != null) {
                query.addParameter("date", prescriptionReal.getDate());
            }
            
            if (! exclude_nulls || prescriptionReal.getDoctor_name() != null) {
                query.addParameter("doctor_name", prescriptionReal.getDoctor_name());
            }
            
            if (! exclude_nulls || prescriptionReal.getPrescription_text() != null) {
                query.addParameter("prescription_text", prescriptionReal.getPrescription_text());
            }
            
            if (! exclude_nulls || prescriptionReal.getSick_id() != null) {
                query.addParameter("sick_id", prescriptionReal.getSick_id());
            }
            
            if (! exclude_nulls || prescriptionReal.getSick_name() != null) {
                query.addParameter("sick_name", prescriptionReal.getSick_name());
            }
            
            if (! exclude_nulls || prescriptionReal.getTest() != null) {
                query.addParameter("test", prescriptionReal.getTest());
            }
            
            if (! exclude_nulls || prescriptionReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", prescriptionReal.getTreatment_date());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return prescriptionReal;
    }
    
    @Override
    public PrescriptionReal update(PrescriptionReal prescriptionReal, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(prescriptionReal, exclude_nulls, con);
            con.commit();
            return prescriptionReal;
        }
    }
    
    @Override
    public PrescriptionReal save(PrescriptionReal prescriptionReal, Connection con) {
        final Long code = prescriptionReal.getCode();

        final PrescriptionReal prescriptionReal2 = this.findByCode(code, null, con);
        
        if (prescriptionReal2 == null) {
            return this.insert(prescriptionReal, con);
        }
        return this.update(prescriptionReal, false, con);
    }
    
    @Override
    public PrescriptionReal save(PrescriptionReal prescriptionReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(prescriptionReal, con);
            con.commit();
            return prescriptionReal;
        }
    }
    
    @Override
    public void delete(Long code, Connection con) {
        logger.info("DB>> delete() - code: " + code);
        
        String sql = "delete from PRESCRIPTIONS_REAL ";
        sql += "where "; 
        sql += "CODE = :code ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("code", code);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long code) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(code, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(PrescriptionReal prescriptionReal, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from PRESCRIPTIONS_REAL ";
        sql += "where ";
        
        if (prescriptionReal.getCode() != null) { 
            sql += "CODE = :code and ";
        }
        
        if (prescriptionReal.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (prescriptionReal.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name and ";
        }
        
        if (prescriptionReal.getPrescription_text() != null) { 
            sql += "PRESCRIPTION_TEXT = :prescription_text and ";
        }
        
        if (prescriptionReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (prescriptionReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (prescriptionReal.getTest() != null) { 
            sql += "TEST = :test and ";
        }
        
        if (prescriptionReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (prescriptionReal.getCode() != null) {
                query.addParameter("code", prescriptionReal.getCode());
            }
            
            if (prescriptionReal.getDate() != null) {
                query.addParameter("date", prescriptionReal.getDate());
            }
            
            if (prescriptionReal.getDoctor_name() != null) {
                query.addParameter("doctor_name", prescriptionReal.getDoctor_name());
            }
            
            if (prescriptionReal.getPrescription_text() != null) {
                query.addParameter("prescription_text", prescriptionReal.getPrescription_text());
            }
            
            if (prescriptionReal.getSick_id() != null) {
                query.addParameter("sick_id", prescriptionReal.getSick_id());
            }
            
            if (prescriptionReal.getSick_name() != null) {
                query.addParameter("sick_name", prescriptionReal.getSick_name());
            }
            
            if (prescriptionReal.getTest() != null) {
                query.addParameter("test", prescriptionReal.getTest());
            }
            
            if (prescriptionReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", prescriptionReal.getTreatment_date());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(PrescriptionReal prescriptionReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(prescriptionReal, con);
            con.commit();
        }
    }
}
