USE [master]
GO

/****** Object:  Database [ARC_DB]    Script Date: 2020-09-28 12:32:03 PM ******/
CREATE DATABASE [ARC_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ARC_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ARC_DB.mdf' , SIZE = 176128KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ARC_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ARC_DB_log.ldf' , SIZE = 568896KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ARC_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ARC_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ARC_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ARC_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ARC_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ARC_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ARC_DB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ARC_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ARC_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ARC_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ARC_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ARC_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ARC_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ARC_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ARC_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ARC_DB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ARC_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ARC_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ARC_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ARC_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ARC_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ARC_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ARC_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ARC_DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ARC_DB] SET  MULTI_USER 
GO

ALTER DATABASE [ARC_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ARC_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ARC_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ARC_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ARC_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ARC_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ARC_DB] SET  READ_WRITE 
GO


