/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.MapBtoG;


public class MapBtoGAggregator {
    private MapBtoG mapBtoG;
    
    public MapBtoG getMapBtoG() {
        return this.mapBtoG;
    }
    
    public void setMapBtoG(MapBtoG mapBtoG) {
        this.mapBtoG = mapBtoG;
    }
}
