/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.ClinicInfoAggregator;
import com.arc.model.ClinicInfo;


public interface ClinicInfoService {
    ClinicInfoAggregator findByName(String name, List<String> fields_to_ignore, Connection con);
    
    ClinicInfoAggregator findByName(String name, Connection con);
    
    ClinicInfoAggregator findByName(String name, List<String> fields_to_ignore);
    
    ClinicInfoAggregator findByName(String name);
    
    ClinicInfo insert(ClinicInfo clinicInfo, Connection con);
    
    ClinicInfo insert(ClinicInfo clinicInfo);
    
    ClinicInfo update(ClinicInfo clinicInfo, boolean exclude_nulls, Connection con);
    
    ClinicInfo update(ClinicInfo clinicInfo, boolean exclude_nulls);
    
    ClinicInfo save(ClinicInfo clinicInfo, Connection con);
    
    ClinicInfo save(ClinicInfo clinicInfo);
    
    List<ClinicInfoAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ClinicInfoAggregator> findAll(Connection con);
    
    List<ClinicInfoAggregator> findAll(List<String> fields_to_ignore);
    
    List<ClinicInfoAggregator> findAll();
    
    List<ClinicInfoAggregator> findByModel(ClinicInfo clinicInfo, List<String> fields_to_ignore, Connection con);
    
    List<ClinicInfoAggregator> findByModel(ClinicInfo clinicInfo, Connection con);
    
    List<ClinicInfoAggregator> findByModel(ClinicInfo clinicInfo, List<String> fields_to_ignore);
    
    List<ClinicInfoAggregator> findByModel(ClinicInfo clinicInfo);
    
    void delete(String name, Connection con);
    
    void delete(String name);
    
    void deleteByModel(ClinicInfo clinicInfo, Connection con);
    
    void deleteByModel(ClinicInfo clinicInfo);
}
