/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.DispensedItem;


public interface DispensedItemRepository {
    DispensedItem findByIds(Long id, String drug_name, List<String> fields_to_ignore, Connection con);
    
    DispensedItem findByIds(Long id, String drug_name, Connection con);
    
    DispensedItem findByIds(Long id, String drug_name, List<String> fields_to_ignore);
    
    DispensedItem findByIds(Long id, String drug_name);
    
    DispensedItem insert(DispensedItem dispensedItem, Connection con);
    
    DispensedItem insert(DispensedItem dispensedItem);
    
    DispensedItem update(DispensedItem dispensedItem, boolean exclude_nulls, Connection con);
    
    DispensedItem update(DispensedItem dispensedItem, boolean exclude_nulls);
    
    DispensedItem save(DispensedItem dispensedItem, Connection con);
    
    DispensedItem save(DispensedItem dispensedItem);
    
    List<DispensedItem> findAll(List<String> fields_to_ignore, Connection con);
    
    List<DispensedItem> findAll(Connection con);
    
    List<DispensedItem> findAll(List<String> fields_to_ignore);
    
    List<DispensedItem> findAll();
    
    List<DispensedItem> findByModel(DispensedItem dispensedItem, List<String> fields_to_ignore, Connection con);
    
    List<DispensedItem> findByModel(DispensedItem dispensedItem, Connection con);
    
    List<DispensedItem> findByModel(DispensedItem dispensedItem, List<String> fields_to_ignore);
    
    List<DispensedItem> findByModel(DispensedItem dispensedItem);
    
    void delete(Long id, String drug_name, Connection con);
    
    void delete(Long id, String drug_name);
    
    void deleteByModel(DispensedItem dispensedItem, Connection con);
    
    void deleteByModel(DispensedItem dispensedItem);
}
