/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.DepotRealHistoryAggregator;
import com.arc.model.DepotRealHistory;


public interface DepotRealHistoryService {
    DepotRealHistoryAggregator findById(Long id, List<String> fields_to_ignore, Connection con);
    
    DepotRealHistoryAggregator findById(Long id, Connection con);
    
    DepotRealHistoryAggregator findById(Long id, List<String> fields_to_ignore);
    
    DepotRealHistoryAggregator findById(Long id);
    
    DepotRealHistory insert(DepotRealHistory depotRealHistory, Connection con);
    
    DepotRealHistory insert(DepotRealHistory depotRealHistory);
    
    DepotRealHistory update(DepotRealHistory depotRealHistory, boolean exclude_nulls, Connection con);
    
    DepotRealHistory update(DepotRealHistory depotRealHistory, boolean exclude_nulls);
    
    DepotRealHistory save(DepotRealHistory depotRealHistory, Connection con);
    
    DepotRealHistory save(DepotRealHistory depotRealHistory);
    
    List<DepotRealHistoryAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<DepotRealHistoryAggregator> findAll(Connection con);
    
    List<DepotRealHistoryAggregator> findAll(List<String> fields_to_ignore);
    
    List<DepotRealHistoryAggregator> findAll();
    
    List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory, List<String> fields_to_ignore, Connection con);
    
    List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory, Connection con);
    
    List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory, List<String> fields_to_ignore);
    
    List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(DepotRealHistory depotRealHistory, Connection con);
    
    void deleteByModel(DepotRealHistory depotRealHistory);
}
