/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Expense;


public class ExpenseAggregator {
    private Expense expense;
    
    public Expense getExpense() {
        return this.expense;
    }
    
    public void setExpense(Expense expense) {
        this.expense = expense;
    }
}
