/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.model;



public class Promotions {
    private Integer end_range;
    private Long id;
    private Integer promotion_percent;
    private Integer start_range;
    
    
    public Integer getEnd_range() {
        return this.end_range;
    }
    
    public void setEnd_range(Integer end_range) {
        this.end_range = end_range;
    }
    
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    public Integer getPromotion_percent() {
        return this.promotion_percent;
    }
    
    public void setPromotion_percent(Integer promotion_percent) {
        this.promotion_percent = promotion_percent;
    }
    
    public Integer getStart_range() {
        return this.start_range;
    }
    
    public void setStart_range(Integer start_range) {
        this.start_range = start_range;
    }
}
