/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository;

import java.util.List;

import org.sql2o.Connection;

import com.arc.model.MapBtoG;


public interface MapBtoGRepository {
    MapBtoG findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    MapBtoG findByCode(Long code, Connection con);
    
    MapBtoG findByCode(Long code, List<String> fields_to_ignore);
    
    MapBtoG findByCode(Long code);
    
    MapBtoG insert(MapBtoG mapBtoG, Connection con);
    
    MapBtoG insert(MapBtoG mapBtoG);
    
    MapBtoG update(MapBtoG mapBtoG, boolean exclude_nulls, Connection con);
    
    MapBtoG update(MapBtoG mapBtoG, boolean exclude_nulls);
    
    MapBtoG save(MapBtoG mapBtoG, Connection con);
    
    MapBtoG save(MapBtoG mapBtoG);
    
    List<MapBtoG> findAll(List<String> fields_to_ignore, Connection con);
    
    List<MapBtoG> findAll(Connection con);
    
    List<MapBtoG> findAll(List<String> fields_to_ignore);
    
    List<MapBtoG> findAll();
    
    List<MapBtoG> findByModel(MapBtoG mapBtoG, List<String> fields_to_ignore, Connection con);
    
    List<MapBtoG> findByModel(MapBtoG mapBtoG, Connection con);
    
    List<MapBtoG> findByModel(MapBtoG mapBtoG, List<String> fields_to_ignore);
    
    List<MapBtoG> findByModel(MapBtoG mapBtoG);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(MapBtoG mapBtoG, Connection con);
    
    void deleteByModel(MapBtoG mapBtoG);
}
