/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Sample;


public class SampleAggregator {
    private Sample sample;
    
    public Sample getSample() {
        return this.sample;
    }
    
    public void setSample(Sample sample) {
        this.sample = sample;
    }
}
