/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.RecordSnapshots;


public class RecordSnapshotsAggregator {
    private RecordSnapshots recordSnapshots;
    
    public RecordSnapshots getRecordSnapshots() {
        return this.recordSnapshots;
    }
    
    public void setRecordSnapshots(RecordSnapshots recordSnapshots) {
        this.recordSnapshots = recordSnapshots;
    }
}
