/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Sick;


public class SickAggregator {
    private Sick sick;
    
    public Sick getSick() {
        return this.sick;
    }
    
    public void setSick(Sick sick) {
        this.sick = sick;
    }
}
