/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service.imp;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.ContactAggregator;
import com.arc.model.Contact;
import com.arc.repository.ContactRepository;
import com.arc.service.ContactService;


@Service
public class ContactServiceImpl implements ContactService {
    @Autowired
    private ContactRepository contactRepository;
    
    private ContactAggregator enrich(Contact contact) {
        ContactAggregator contactAggregator = null;
        
        if (contact != null) {
            contactAggregator = new ContactAggregator();
            
            contactAggregator.setContact(contact);
        }
        
        return contactAggregator;
    }
    
    private List<ContactAggregator> enrich(List<Contact> contacts) {
        final List<ContactAggregator> contactAggregators = new ArrayList<>();
        
        if (contacts != null) {
            for (Contact contact: contacts) {
                contactAggregators.add(this.enrich(contact));
            }
        }
        
        return contactAggregators;
    }
    
    @Override
    public List<ContactAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<Contact> contacts = this.contactRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findAll(Connection con) {
        final List<Contact> contacts = this.contactRepository.findAll(con);
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findAll(List<String> fields_to_ignore) {
        final List<Contact> contacts = this.contactRepository.findAll(fields_to_ignore);
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findAll() {
        final List<Contact> contacts = this.contactRepository.findAll();
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findByModel(Contact contact, List<String> fields_to_ignore, Connection con) {
        final List<Contact> contacts = this.contactRepository.findByModel(contact, fields_to_ignore, con);
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findByModel(Contact contact, Connection con) {
        final List<Contact> contacts = this.contactRepository.findByModel(contact, con);
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findByModel(Contact contact, List<String> fields_to_ignore) {
        final List<Contact> contacts = this.contactRepository.findByModel(contact, fields_to_ignore);
        
        return this.enrich(contacts);
    }
    
    @Override
    public List<ContactAggregator> findByModel(Contact contact) {
        final List<Contact> contacts = this.contactRepository.findByModel(contact);
        
        return this.enrich(contacts);
    }
    
    @Override
    public ContactAggregator findById(String id, List<String> fields_to_ignore, Connection con) {
        final Contact contact = this.contactRepository.findById(id, fields_to_ignore, con);
        
        return this.enrich(contact);
    }
    
    @Override
    public ContactAggregator findById(String id, Connection con) {
        final Contact contact = this.contactRepository.findById(id, con);
        
        return this.enrich(contact);
    }
    
    @Override
    public ContactAggregator findById(String id, List<String> fields_to_ignore) {
        final Contact contact = this.contactRepository.findById(id, fields_to_ignore);
        
        return this.enrich(contact);
    }
    
    @Override
    public ContactAggregator findById(String id) {
        final Contact contact = this.contactRepository.findById(id);
        
        return this.enrich(contact);
    }
    
    @Override
    public Contact insert(Contact contact, Connection con) {
        return this.contactRepository.insert(contact, con);
    }
    
    @Override
    public Contact insert(Contact contact) {
        return this.contactRepository.insert(contact);
    }
    
    @Override
    public Contact update(Contact contact, boolean exclude_nulls, Connection con) {
        return this.contactRepository.update(contact, exclude_nulls, con);
    }
    
    @Override
    public Contact update(Contact contact, boolean exclude_nulls) {
        return this.contactRepository.update(contact, exclude_nulls);
    }
    
    @Override
    public Contact save(Contact contact, Connection con) {
        return this.contactRepository.save(contact, con);
    }
    
    @Override
    public Contact save(Contact contact) {
        return this.contactRepository.save(contact);
    }
    
    @Override
    public void delete(String id, Connection con) {
        this.contactRepository.delete(id, con);
    }
    
    @Override
    public void delete(String id) {
        this.contactRepository.delete(id);
    }
    
    @Override
    public void deleteByModel(Contact contact, Connection con) {
        this.contactRepository.deleteByModel(contact, con);
    }
    
    @Override
    public void deleteByModel(Contact contact) {
        this.contactRepository.deleteByModel(contact);
    }
}
