/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service.imp;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.DepotRealHistoryAggregator;
import com.arc.model.DepotRealHistory;
import com.arc.repository.DepotRealHistoryRepository;
import com.arc.service.DepotRealHistoryService;


@Service
public class DepotRealHistoryServiceImpl implements DepotRealHistoryService {
    @Autowired
    private DepotRealHistoryRepository depotRealHistoryRepository;
    
    private DepotRealHistoryAggregator enrich(DepotRealHistory depotRealHistory) {
        DepotRealHistoryAggregator depotRealHistoryAggregator = null;
        
        if (depotRealHistory != null) {
            depotRealHistoryAggregator = new DepotRealHistoryAggregator();
            
            depotRealHistoryAggregator.setDepotRealHistory(depotRealHistory);
        }
        
        return depotRealHistoryAggregator;
    }
    
    private List<DepotRealHistoryAggregator> enrich(List<DepotRealHistory> depotRealHistorys) {
        final List<DepotRealHistoryAggregator> depotRealHistoryAggregators = new ArrayList<>();
        
        if (depotRealHistorys != null) {
            for (DepotRealHistory depotRealHistory: depotRealHistorys) {
                depotRealHistoryAggregators.add(this.enrich(depotRealHistory));
            }
        }
        
        return depotRealHistoryAggregators;
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findAll(Connection con) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findAll(con);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findAll(List<String> fields_to_ignore) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findAll(fields_to_ignore);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findAll() {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findAll();
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory, List<String> fields_to_ignore, Connection con) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findByModel(depotRealHistory, fields_to_ignore, con);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory, Connection con) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findByModel(depotRealHistory, con);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory, List<String> fields_to_ignore) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findByModel(depotRealHistory, fields_to_ignore);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public List<DepotRealHistoryAggregator> findByModel(DepotRealHistory depotRealHistory) {
        final List<DepotRealHistory> depotRealHistorys = this.depotRealHistoryRepository.findByModel(depotRealHistory);
        
        return this.enrich(depotRealHistorys);
    }
    
    @Override
    public DepotRealHistoryAggregator findById(Long id, List<String> fields_to_ignore, Connection con) {
        final DepotRealHistory depotRealHistory = this.depotRealHistoryRepository.findById(id, fields_to_ignore, con);
        
        return this.enrich(depotRealHistory);
    }
    
    @Override
    public DepotRealHistoryAggregator findById(Long id, Connection con) {
        final DepotRealHistory depotRealHistory = this.depotRealHistoryRepository.findById(id, con);
        
        return this.enrich(depotRealHistory);
    }
    
    @Override
    public DepotRealHistoryAggregator findById(Long id, List<String> fields_to_ignore) {
        final DepotRealHistory depotRealHistory = this.depotRealHistoryRepository.findById(id, fields_to_ignore);
        
        return this.enrich(depotRealHistory);
    }
    
    @Override
    public DepotRealHistoryAggregator findById(Long id) {
        final DepotRealHistory depotRealHistory = this.depotRealHistoryRepository.findById(id);
        
        return this.enrich(depotRealHistory);
    }
    
    @Override
    public DepotRealHistory insert(DepotRealHistory depotRealHistory, Connection con) {
        return this.depotRealHistoryRepository.insert(depotRealHistory, con);
    }
    
    @Override
    public DepotRealHistory insert(DepotRealHistory depotRealHistory) {
        return this.depotRealHistoryRepository.insert(depotRealHistory);
    }
    
    @Override
    public DepotRealHistory update(DepotRealHistory depotRealHistory, boolean exclude_nulls, Connection con) {
        return this.depotRealHistoryRepository.update(depotRealHistory, exclude_nulls, con);
    }
    
    @Override
    public DepotRealHistory update(DepotRealHistory depotRealHistory, boolean exclude_nulls) {
        return this.depotRealHistoryRepository.update(depotRealHistory, exclude_nulls);
    }
    
    @Override
    public DepotRealHistory save(DepotRealHistory depotRealHistory, Connection con) {
        return this.depotRealHistoryRepository.save(depotRealHistory, con);
    }
    
    @Override
    public DepotRealHistory save(DepotRealHistory depotRealHistory) {
        return this.depotRealHistoryRepository.save(depotRealHistory);
    }
    
    @Override
    public void delete(Long id, Connection con) {
        this.depotRealHistoryRepository.delete(id, con);
    }
    
    @Override
    public void delete(Long id) {
        this.depotRealHistoryRepository.delete(id);
    }
    
    @Override
    public void deleteByModel(DepotRealHistory depotRealHistory, Connection con) {
        this.depotRealHistoryRepository.deleteByModel(depotRealHistory, con);
    }
    
    @Override
    public void deleteByModel(DepotRealHistory depotRealHistory) {
        this.depotRealHistoryRepository.deleteByModel(depotRealHistory);
    }
}
