/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service.imp;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.PaymentRealAggregator;
import com.arc.model.PaymentReal;
import com.arc.repository.PaymentRealRepository;
import com.arc.service.PaymentRealService;


@Service
public class PaymentRealServiceImpl implements PaymentRealService {
    @Autowired
    private PaymentRealRepository paymentRealRepository;
    
    private PaymentRealAggregator enrich(PaymentReal paymentReal) {
        PaymentRealAggregator paymentRealAggregator = null;
        
        if (paymentReal != null) {
            paymentRealAggregator = new PaymentRealAggregator();
            
            paymentRealAggregator.setPaymentReal(paymentReal);
        }
        
        return paymentRealAggregator;
    }
    
    private List<PaymentRealAggregator> enrich(List<PaymentReal> paymentReals) {
        final List<PaymentRealAggregator> paymentRealAggregators = new ArrayList<>();
        
        if (paymentReals != null) {
            for (PaymentReal paymentReal: paymentReals) {
                paymentRealAggregators.add(this.enrich(paymentReal));
            }
        }
        
        return paymentRealAggregators;
    }
    
    @Override
    public List<PaymentRealAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findAll(Connection con) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findAll(con);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findAll(List<String> fields_to_ignore) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findAll(fields_to_ignore);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findAll() {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findAll();
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findByModel(PaymentReal paymentReal, List<String> fields_to_ignore, Connection con) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findByModel(paymentReal, fields_to_ignore, con);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findByModel(PaymentReal paymentReal, Connection con) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findByModel(paymentReal, con);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findByModel(PaymentReal paymentReal, List<String> fields_to_ignore) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findByModel(paymentReal, fields_to_ignore);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public List<PaymentRealAggregator> findByModel(PaymentReal paymentReal) {
        final List<PaymentReal> paymentReals = this.paymentRealRepository.findByModel(paymentReal);
        
        return this.enrich(paymentReals);
    }
    
    @Override
    public PaymentRealAggregator findById(String id, List<String> fields_to_ignore, Connection con) {
        final PaymentReal paymentReal = this.paymentRealRepository.findById(id, fields_to_ignore, con);
        
        return this.enrich(paymentReal);
    }
    
    @Override
    public PaymentRealAggregator findById(String id, Connection con) {
        final PaymentReal paymentReal = this.paymentRealRepository.findById(id, con);
        
        return this.enrich(paymentReal);
    }
    
    @Override
    public PaymentRealAggregator findById(String id, List<String> fields_to_ignore) {
        final PaymentReal paymentReal = this.paymentRealRepository.findById(id, fields_to_ignore);
        
        return this.enrich(paymentReal);
    }
    
    @Override
    public PaymentRealAggregator findById(String id) {
        final PaymentReal paymentReal = this.paymentRealRepository.findById(id);
        
        return this.enrich(paymentReal);
    }
    
    @Override
    public PaymentReal insert(PaymentReal paymentReal, Connection con) {
        return this.paymentRealRepository.insert(paymentReal, con);
    }
    
    @Override
    public PaymentReal insert(PaymentReal paymentReal) {
        return this.paymentRealRepository.insert(paymentReal);
    }
    
    @Override
    public PaymentReal update(PaymentReal paymentReal, boolean exclude_nulls, Connection con) {
        return this.paymentRealRepository.update(paymentReal, exclude_nulls, con);
    }
    
    @Override
    public PaymentReal update(PaymentReal paymentReal, boolean exclude_nulls) {
        return this.paymentRealRepository.update(paymentReal, exclude_nulls);
    }
    
    @Override
    public PaymentReal save(PaymentReal paymentReal, Connection con) {
        return this.paymentRealRepository.save(paymentReal, con);
    }
    
    @Override
    public PaymentReal save(PaymentReal paymentReal) {
        return this.paymentRealRepository.save(paymentReal);
    }
    
    @Override
    public void delete(String id, Connection con) {
        this.paymentRealRepository.delete(id, con);
    }
    
    @Override
    public void delete(String id) {
        this.paymentRealRepository.delete(id);
    }
    
    @Override
    public void deleteByModel(PaymentReal paymentReal, Connection con) {
        this.paymentRealRepository.deleteByModel(paymentReal, con);
    }
    
    @Override
    public void deleteByModel(PaymentReal paymentReal) {
        this.paymentRealRepository.deleteByModel(paymentReal);
    }
}
