/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service.imp;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.SickHistoryRealAggregator;
import com.arc.model.SickHistoryReal;
import com.arc.repository.SickHistoryRealRepository;
import com.arc.service.SickHistoryRealService;


@Service
public class SickHistoryRealServiceImpl implements SickHistoryRealService {
    @Autowired
    private SickHistoryRealRepository sickHistoryRealRepository;
    
    private SickHistoryRealAggregator enrich(SickHistoryReal sickHistoryReal) {
        SickHistoryRealAggregator sickHistoryRealAggregator = null;
        
        if (sickHistoryReal != null) {
            sickHistoryRealAggregator = new SickHistoryRealAggregator();
            
            sickHistoryRealAggregator.setSickHistoryReal(sickHistoryReal);
        }
        
        return sickHistoryRealAggregator;
    }
    
    private List<SickHistoryRealAggregator> enrich(List<SickHistoryReal> sickHistoryReals) {
        final List<SickHistoryRealAggregator> sickHistoryRealAggregators = new ArrayList<>();
        
        if (sickHistoryReals != null) {
            for (SickHistoryReal sickHistoryReal: sickHistoryReals) {
                sickHistoryRealAggregators.add(this.enrich(sickHistoryReal));
            }
        }
        
        return sickHistoryRealAggregators;
    }
    
    @Override
    public List<SickHistoryRealAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findAll(Connection con) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findAll(con);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findAll(List<String> fields_to_ignore) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findAll(fields_to_ignore);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findAll() {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findAll();
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal, List<String> fields_to_ignore, Connection con) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findByModel(sickHistoryReal, fields_to_ignore, con);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal, Connection con) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findByModel(sickHistoryReal, con);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal, List<String> fields_to_ignore) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findByModel(sickHistoryReal, fields_to_ignore);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal) {
        final List<SickHistoryReal> sickHistoryReals = this.sickHistoryRealRepository.findByModel(sickHistoryReal);
        
        return this.enrich(sickHistoryReals);
    }
    
    @Override
    public SickHistoryRealAggregator findByIds(Long id, String sick_id, List<String> fields_to_ignore, Connection con) {
        final SickHistoryReal sickHistoryReal = this.sickHistoryRealRepository.findByIds(id, sick_id, fields_to_ignore, con);
        
        return this.enrich(sickHistoryReal);
    }
    
    @Override
    public SickHistoryRealAggregator findByIds(Long id, String sick_id, Connection con) {
        final SickHistoryReal sickHistoryReal = this.sickHistoryRealRepository.findByIds(id, sick_id, con);
        
        return this.enrich(sickHistoryReal);
    }
    
    @Override
    public SickHistoryRealAggregator findByIds(Long id, String sick_id, List<String> fields_to_ignore) {
        final SickHistoryReal sickHistoryReal = this.sickHistoryRealRepository.findByIds(id, sick_id, fields_to_ignore);
        
        return this.enrich(sickHistoryReal);
    }
    
    @Override
    public SickHistoryRealAggregator findByIds(Long id, String sick_id) {
        final SickHistoryReal sickHistoryReal = this.sickHistoryRealRepository.findByIds(id, sick_id);
        
        return this.enrich(sickHistoryReal);
    }
    
    @Override
    public SickHistoryReal insert(SickHistoryReal sickHistoryReal, Connection con) {
        return this.sickHistoryRealRepository.insert(sickHistoryReal, con);
    }
    
    @Override
    public SickHistoryReal insert(SickHistoryReal sickHistoryReal) {
        return this.sickHistoryRealRepository.insert(sickHistoryReal);
    }
    
    @Override
    public SickHistoryReal update(SickHistoryReal sickHistoryReal, boolean exclude_nulls, Connection con) {
        return this.sickHistoryRealRepository.update(sickHistoryReal, exclude_nulls, con);
    }
    
    @Override
    public SickHistoryReal update(SickHistoryReal sickHistoryReal, boolean exclude_nulls) {
        return this.sickHistoryRealRepository.update(sickHistoryReal, exclude_nulls);
    }
    
    @Override
    public SickHistoryReal save(SickHistoryReal sickHistoryReal, Connection con) {
        return this.sickHistoryRealRepository.save(sickHistoryReal, con);
    }
    
    @Override
    public SickHistoryReal save(SickHistoryReal sickHistoryReal) {
        return this.sickHistoryRealRepository.save(sickHistoryReal);
    }
    
    @Override
    public void delete(Long id, String sick_id, Connection con) {
        this.sickHistoryRealRepository.delete(id, sick_id, con);
    }
    
    @Override
    public void delete(Long id, String sick_id) {
        this.sickHistoryRealRepository.delete(id, sick_id);
    }
    
    @Override
    public void deleteByModel(SickHistoryReal sickHistoryReal, Connection con) {
        this.sickHistoryRealRepository.deleteByModel(sickHistoryReal, con);
    }
    
    @Override
    public void deleteByModel(SickHistoryReal sickHistoryReal) {
        this.sickHistoryRealRepository.deleteByModel(sickHistoryReal);
    }
}
