/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service.imp;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.SickHistoryAggregator;
import com.arc.model.SickHistory;
import com.arc.repository.SickHistoryRepository;
import com.arc.service.SickHistoryService;


@Service
public class SickHistoryServiceImpl implements SickHistoryService {
    @Autowired
    private SickHistoryRepository sickHistoryRepository;
    
    private SickHistoryAggregator enrich(SickHistory sickHistory) {
        SickHistoryAggregator sickHistoryAggregator = null;
        
        if (sickHistory != null) {
            sickHistoryAggregator = new SickHistoryAggregator();
            
            sickHistoryAggregator.setSickHistory(sickHistory);
        }
        
        return sickHistoryAggregator;
    }
    
    private List<SickHistoryAggregator> enrich(List<SickHistory> sickHistorys) {
        final List<SickHistoryAggregator> sickHistoryAggregators = new ArrayList<>();
        
        if (sickHistorys != null) {
            for (SickHistory sickHistory: sickHistorys) {
                sickHistoryAggregators.add(this.enrich(sickHistory));
            }
        }
        
        return sickHistoryAggregators;
    }
    
    @Override
    public List<SickHistoryAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findAll(Connection con) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findAll(con);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findAll(List<String> fields_to_ignore) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findAll(fields_to_ignore);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findAll() {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findAll();
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findByModel(SickHistory sickHistory, List<String> fields_to_ignore, Connection con) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findByModel(sickHistory, fields_to_ignore, con);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findByModel(SickHistory sickHistory, Connection con) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findByModel(sickHistory, con);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findByModel(SickHistory sickHistory, List<String> fields_to_ignore) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findByModel(sickHistory, fields_to_ignore);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public List<SickHistoryAggregator> findByModel(SickHistory sickHistory) {
        final List<SickHistory> sickHistorys = this.sickHistoryRepository.findByModel(sickHistory);
        
        return this.enrich(sickHistorys);
    }
    
    @Override
    public SickHistoryAggregator findByIds(Long id, String sick_id, List<String> fields_to_ignore, Connection con) {
        final SickHistory sickHistory = this.sickHistoryRepository.findByIds(id, sick_id, fields_to_ignore, con);
        
        return this.enrich(sickHistory);
    }
    
    @Override
    public SickHistoryAggregator findByIds(Long id, String sick_id, Connection con) {
        final SickHistory sickHistory = this.sickHistoryRepository.findByIds(id, sick_id, con);
        
        return this.enrich(sickHistory);
    }
    
    @Override
    public SickHistoryAggregator findByIds(Long id, String sick_id, List<String> fields_to_ignore) {
        final SickHistory sickHistory = this.sickHistoryRepository.findByIds(id, sick_id, fields_to_ignore);
        
        return this.enrich(sickHistory);
    }
    
    @Override
    public SickHistoryAggregator findByIds(Long id, String sick_id) {
        final SickHistory sickHistory = this.sickHistoryRepository.findByIds(id, sick_id);
        
        return this.enrich(sickHistory);
    }
    
    @Override
    public SickHistory insert(SickHistory sickHistory, Connection con) {
        return this.sickHistoryRepository.insert(sickHistory, con);
    }
    
    @Override
    public SickHistory insert(SickHistory sickHistory) {
        return this.sickHistoryRepository.insert(sickHistory);
    }
    
    @Override
    public SickHistory update(SickHistory sickHistory, boolean exclude_nulls, Connection con) {
        return this.sickHistoryRepository.update(sickHistory, exclude_nulls, con);
    }
    
    @Override
    public SickHistory update(SickHistory sickHistory, boolean exclude_nulls) {
        return this.sickHistoryRepository.update(sickHistory, exclude_nulls);
    }
    
    @Override
    public SickHistory save(SickHistory sickHistory, Connection con) {
        return this.sickHistoryRepository.save(sickHistory, con);
    }
    
    @Override
    public SickHistory save(SickHistory sickHistory) {
        return this.sickHistoryRepository.save(sickHistory);
    }
    
    @Override
    public void delete(Long id, String sick_id, Connection con) {
        this.sickHistoryRepository.delete(id, sick_id, con);
    }
    
    @Override
    public void delete(Long id, String sick_id) {
        this.sickHistoryRepository.delete(id, sick_id);
    }
    
    @Override
    public void deleteByModel(SickHistory sickHistory, Connection con) {
        this.sickHistoryRepository.deleteByModel(sickHistory, con);
    }
    
    @Override
    public void deleteByModel(SickHistory sickHistory) {
        this.sickHistoryRepository.deleteByModel(sickHistory);
    }
}
