/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.AssessmentAggregator;
import com.arc.model.Assessment;


public interface AssessmentService {
    AssessmentAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    AssessmentAggregator findByCode(Long code, Connection con);
    
    AssessmentAggregator findByCode(Long code, List<String> fields_to_ignore);
    
    AssessmentAggregator findByCode(Long code);
    
    Assessment insert(Assessment assessment, Connection con);
    
    Assessment insert(Assessment assessment);
    
    Assessment update(Assessment assessment, boolean exclude_nulls, Connection con);
    
    Assessment update(Assessment assessment, boolean exclude_nulls);
    
    Assessment save(Assessment assessment, Connection con);
    
    Assessment save(Assessment assessment);
    
    List<AssessmentAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<AssessmentAggregator> findAll(Connection con);
    
    List<AssessmentAggregator> findAll(List<String> fields_to_ignore);
    
    List<AssessmentAggregator> findAll();
    
    List<AssessmentAggregator> findByModel(Assessment assessment, List<String> fields_to_ignore, Connection con);
    
    List<AssessmentAggregator> findByModel(Assessment assessment, Connection con);
    
    List<AssessmentAggregator> findByModel(Assessment assessment, List<String> fields_to_ignore);
    
    List<AssessmentAggregator> findByModel(Assessment assessment);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(Assessment assessment, Connection con);
    
    void deleteByModel(Assessment assessment);
}
