/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.ExpenseTypeAggregator;
import com.arc.model.ExpenseType;


public interface ExpenseTypeService {
    ExpenseTypeAggregator findById(Long id, List<String> fields_to_ignore, Connection con);
    
    ExpenseTypeAggregator findById(Long id, Connection con);
    
    ExpenseTypeAggregator findById(Long id, List<String> fields_to_ignore);
    
    ExpenseTypeAggregator findById(Long id);
    
    ExpenseType insert(ExpenseType expenseType, Connection con);
    
    ExpenseType insert(ExpenseType expenseType);
    
    ExpenseType update(ExpenseType expenseType, boolean exclude_nulls, Connection con);
    
    ExpenseType update(ExpenseType expenseType, boolean exclude_nulls);
    
    ExpenseType save(ExpenseType expenseType, Connection con);
    
    ExpenseType save(ExpenseType expenseType);
    
    List<ExpenseTypeAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ExpenseTypeAggregator> findAll(Connection con);
    
    List<ExpenseTypeAggregator> findAll(List<String> fields_to_ignore);
    
    List<ExpenseTypeAggregator> findAll();
    
    List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType, List<String> fields_to_ignore, Connection con);
    
    List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType, Connection con);
    
    List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType, List<String> fields_to_ignore);
    
    List<ExpenseTypeAggregator> findByModel(ExpenseType expenseType);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(ExpenseType expenseType, Connection con);
    
    void deleteByModel(ExpenseType expenseType);
}
