/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.GeneralSettingAggregator;
import com.arc.model.GeneralSetting;


public interface GeneralSettingService {
    GeneralSettingAggregator findByPay_type(String pay_type, List<String> fields_to_ignore, Connection con);
    
    GeneralSettingAggregator findByPay_type(String pay_type, Connection con);
    
    GeneralSettingAggregator findByPay_type(String pay_type, List<String> fields_to_ignore);
    
    GeneralSettingAggregator findByPay_type(String pay_type);
    
    GeneralSetting insert(GeneralSetting generalSetting, Connection con);
    
    GeneralSetting insert(GeneralSetting generalSetting);
    
    GeneralSetting update(GeneralSetting generalSetting, boolean exclude_nulls, Connection con);
    
    GeneralSetting update(GeneralSetting generalSetting, boolean exclude_nulls);
    
    GeneralSetting save(GeneralSetting generalSetting, Connection con);
    
    GeneralSetting save(GeneralSetting generalSetting);
    
    List<GeneralSettingAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<GeneralSettingAggregator> findAll(Connection con);
    
    List<GeneralSettingAggregator> findAll(List<String> fields_to_ignore);
    
    List<GeneralSettingAggregator> findAll();
    
    List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting, List<String> fields_to_ignore, Connection con);
    
    List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting, Connection con);
    
    List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting, List<String> fields_to_ignore);
    
    List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting);
    
    void delete(String pay_type, Connection con);
    
    void delete(String pay_type);
    
    void deleteByModel(GeneralSetting generalSetting, Connection con);
    
    void deleteByModel(GeneralSetting generalSetting);
}
