/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.GeneralSettingAggregator;
import com.arc.model.GeneralSetting;
import com.arc.repository.GeneralSettingRepository;


@Service
public class GeneralSettingServiceImpl implements GeneralSettingService {
    @Autowired
    private GeneralSettingRepository generalSettingRepository;
    
    private GeneralSettingAggregator enrich(GeneralSetting generalSetting) {
        GeneralSettingAggregator generalSettingAggregator = null;
        
        if (generalSetting != null) {
            generalSettingAggregator = new GeneralSettingAggregator();
            
            generalSettingAggregator.setGeneralSetting(generalSetting);
        }
        
        return generalSettingAggregator;
    }
    
    private List<GeneralSettingAggregator> enrich(List<GeneralSetting> generalSettings) {
        final List<GeneralSettingAggregator> generalSettingAggregators = new ArrayList<>();
        
        if (generalSettings != null) {
            for (GeneralSetting generalSetting: generalSettings) {
                generalSettingAggregators.add(this.enrich(generalSetting));
            }
        }
        
        return generalSettingAggregators;
    }
    
    @Override
    public List<GeneralSettingAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findAll(Connection con) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findAll(con);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findAll(List<String> fields_to_ignore) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findAll(fields_to_ignore);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findAll() {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findAll();
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting, List<String> fields_to_ignore, Connection con) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findByModel(generalSetting, fields_to_ignore, con);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting, Connection con) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findByModel(generalSetting, con);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting, List<String> fields_to_ignore) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findByModel(generalSetting, fields_to_ignore);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public List<GeneralSettingAggregator> findByModel(GeneralSetting generalSetting) {
        final List<GeneralSetting> generalSettings = this.generalSettingRepository.findByModel(generalSetting);
        
        return this.enrich(generalSettings);
    }
    
    @Override
    public GeneralSettingAggregator findByPay_type(String pay_type, List<String> fields_to_ignore, Connection con) {
        final GeneralSetting generalSetting = this.generalSettingRepository.findByPay_type(pay_type, fields_to_ignore, con);
        
        return this.enrich(generalSetting);
    }
    
    @Override
    public GeneralSettingAggregator findByPay_type(String pay_type, Connection con) {
        final GeneralSetting generalSetting = this.generalSettingRepository.findByPay_type(pay_type, con);
        
        return this.enrich(generalSetting);
    }
    
    @Override
    public GeneralSettingAggregator findByPay_type(String pay_type, List<String> fields_to_ignore) {
        final GeneralSetting generalSetting = this.generalSettingRepository.findByPay_type(pay_type, fields_to_ignore);
        
        return this.enrich(generalSetting);
    }
    
    @Override
    public GeneralSettingAggregator findByPay_type(String pay_type) {
        final GeneralSetting generalSetting = this.generalSettingRepository.findByPay_type(pay_type);
        
        return this.enrich(generalSetting);
    }
    
    @Override
    public GeneralSetting insert(GeneralSetting generalSetting, Connection con) {
        return this.generalSettingRepository.insert(generalSetting, con);
    }
    
    @Override
    public GeneralSetting insert(GeneralSetting generalSetting) {
        return this.generalSettingRepository.insert(generalSetting);
    }
    
    @Override
    public GeneralSetting update(GeneralSetting generalSetting, boolean exclude_nulls, Connection con) {
        return this.generalSettingRepository.update(generalSetting, exclude_nulls, con);
    }
    
    @Override
    public GeneralSetting update(GeneralSetting generalSetting, boolean exclude_nulls) {
        return this.generalSettingRepository.update(generalSetting, exclude_nulls);
    }
    
    @Override
    public GeneralSetting save(GeneralSetting generalSetting, Connection con) {
        return this.generalSettingRepository.save(generalSetting, con);
    }
    
    @Override
    public GeneralSetting save(GeneralSetting generalSetting) {
        return this.generalSettingRepository.save(generalSetting);
    }
    
    @Override
    public void delete(String pay_type, Connection con) {
        this.generalSettingRepository.delete(pay_type, con);
    }
    
    @Override
    public void delete(String pay_type) {
        this.generalSettingRepository.delete(pay_type);
    }
    
    @Override
    public void deleteByModel(GeneralSetting generalSetting, Connection con) {
        this.generalSettingRepository.deleteByModel(generalSetting, con);
    }
    
    @Override
    public void deleteByModel(GeneralSetting generalSetting) {
        this.generalSettingRepository.deleteByModel(generalSetting);
    }
}
