/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.InterviewAggregator;
import com.arc.model.Interview;


public interface InterviewService {
    InterviewAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    InterviewAggregator findByCode(Long code, Connection con);
    
    InterviewAggregator findByCode(Long code, List<String> fields_to_ignore);
    
    InterviewAggregator findByCode(Long code);
    
    Interview insert(Interview interview, Connection con);
    
    Interview insert(Interview interview);
    
    Interview update(Interview interview, boolean exclude_nulls, Connection con);
    
    Interview update(Interview interview, boolean exclude_nulls);
    
    Interview save(Interview interview, Connection con);
    
    Interview save(Interview interview);
    
    List<InterviewAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<InterviewAggregator> findAll(Connection con);
    
    List<InterviewAggregator> findAll(List<String> fields_to_ignore);
    
    List<InterviewAggregator> findAll();
    
    List<InterviewAggregator> findByModel(Interview interview, List<String> fields_to_ignore, Connection con);
    
    List<InterviewAggregator> findByModel(Interview interview, Connection con);
    
    List<InterviewAggregator> findByModel(Interview interview, List<String> fields_to_ignore);
    
    List<InterviewAggregator> findByModel(Interview interview);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(Interview interview, Connection con);
    
    void deleteByModel(Interview interview);
}
