/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.MapAAggregator;
import com.arc.model.MapA;


public interface MapAService {
    MapAAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    MapAAggregator findByCode(Long code, Connection con);
    
    MapAAggregator findByCode(Long code, List<String> fields_to_ignore);
    
    MapAAggregator findByCode(Long code);
    
    MapA insert(MapA mapA, Connection con);
    
    MapA insert(MapA mapA);
    
    MapA update(MapA mapA, boolean exclude_nulls, Connection con);
    
    MapA update(MapA mapA, boolean exclude_nulls);
    
    MapA save(MapA mapA, Connection con);
    
    MapA save(MapA mapA);
    
    List<MapAAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<MapAAggregator> findAll(Connection con);
    
    List<MapAAggregator> findAll(List<String> fields_to_ignore);
    
    List<MapAAggregator> findAll();
    
    List<MapAAggregator> findByModel(MapA mapA, List<String> fields_to_ignore, Connection con);
    
    List<MapAAggregator> findByModel(MapA mapA, Connection con);
    
    List<MapAAggregator> findByModel(MapA mapA, List<String> fields_to_ignore);
    
    List<MapAAggregator> findByModel(MapA mapA);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(MapA mapA, Connection con);
    
    void deleteByModel(MapA mapA);
}
