/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.MapHistoryAggregator;
import com.arc.model.MapHistory;


public interface MapHistoryService {
    MapHistoryAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con);
    
    MapHistoryAggregator findByCode(Long code, Connection con);
    
    MapHistoryAggregator findByCode(Long code, List<String> fields_to_ignore);
    
    MapHistoryAggregator findByCode(Long code);
    
    MapHistory insert(MapHistory mapHistory, Connection con);
    
    MapHistory insert(MapHistory mapHistory);
    
    MapHistory update(MapHistory mapHistory, boolean exclude_nulls, Connection con);
    
    MapHistory update(MapHistory mapHistory, boolean exclude_nulls);
    
    MapHistory save(MapHistory mapHistory, Connection con);
    
    MapHistory save(MapHistory mapHistory);
    
    List<MapHistoryAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<MapHistoryAggregator> findAll(Connection con);
    
    List<MapHistoryAggregator> findAll(List<String> fields_to_ignore);
    
    List<MapHistoryAggregator> findAll();
    
    List<MapHistoryAggregator> findByModel(MapHistory mapHistory, List<String> fields_to_ignore, Connection con);
    
    List<MapHistoryAggregator> findByModel(MapHistory mapHistory, Connection con);
    
    List<MapHistoryAggregator> findByModel(MapHistory mapHistory, List<String> fields_to_ignore);
    
    List<MapHistoryAggregator> findByModel(MapHistory mapHistory);
    
    void delete(Long code, Connection con);
    
    void delete(Long code);
    
    void deleteByModel(MapHistory mapHistory, Connection con);
    
    void deleteByModel(MapHistory mapHistory);
}
