/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.ReceiptsAggregator;
import com.arc.model.Receipts;


public interface ReceiptsService {
    ReceiptsAggregator findById(Long id, List<String> fields_to_ignore, Connection con);
    
    ReceiptsAggregator findById(Long id, Connection con);
    
    ReceiptsAggregator findById(Long id, List<String> fields_to_ignore);
    
    ReceiptsAggregator findById(Long id);
    
    Receipts insert(Receipts receipts, Connection con);
    
    Receipts insert(Receipts receipts);
    
    Receipts update(Receipts receipts, boolean exclude_nulls, Connection con);
    
    Receipts update(Receipts receipts, boolean exclude_nulls);
    
    Receipts save(Receipts receipts, Connection con);
    
    Receipts save(Receipts receipts);
    
    List<ReceiptsAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ReceiptsAggregator> findAll(Connection con);
    
    List<ReceiptsAggregator> findAll(List<String> fields_to_ignore);
    
    List<ReceiptsAggregator> findAll();
    
    List<ReceiptsAggregator> findByModel(Receipts receipts, List<String> fields_to_ignore, Connection con);
    
    List<ReceiptsAggregator> findByModel(Receipts receipts, Connection con);
    
    List<ReceiptsAggregator> findByModel(Receipts receipts, List<String> fields_to_ignore);
    
    List<ReceiptsAggregator> findByModel(Receipts receipts);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(Receipts receipts, Connection con);
    
    void deleteByModel(Receipts receipts);
}
