/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.SampleAggregator;
import com.arc.model.Sample;


public interface SampleService {
    SampleAggregator findByContext(String context, List<String> fields_to_ignore, Connection con);
    
    SampleAggregator findByContext(String context, Connection con);
    
    SampleAggregator findByContext(String context, List<String> fields_to_ignore);
    
    SampleAggregator findByContext(String context);
    
    Sample insert(Sample sample, Connection con);
    
    Sample insert(Sample sample);
    
    Sample update(Sample sample, boolean exclude_nulls, Connection con);
    
    Sample update(Sample sample, boolean exclude_nulls);
    
    Sample save(Sample sample, Connection con);
    
    Sample save(Sample sample);
    
    List<SampleAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<SampleAggregator> findAll(Connection con);
    
    List<SampleAggregator> findAll(List<String> fields_to_ignore);
    
    List<SampleAggregator> findAll();
    
    List<SampleAggregator> findByModel(Sample sample, List<String> fields_to_ignore, Connection con);
    
    List<SampleAggregator> findByModel(Sample sample, Connection con);
    
    List<SampleAggregator> findByModel(Sample sample, List<String> fields_to_ignore);
    
    List<SampleAggregator> findByModel(Sample sample);
    
    void delete(String context, Connection con);
    
    void delete(String context);
    
    void deleteByModel(Sample sample, Connection con);
    
    void deleteByModel(Sample sample);
}
