/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.SickHistoryRealAggregator;
import com.arc.model.SickHistoryReal;


public interface SickHistoryRealService {
    SickHistoryRealAggregator findByIds(Long id, String sick_id, List<String> fields_to_ignore, Connection con);
    
    SickHistoryRealAggregator findByIds(Long id, String sick_id, Connection con);
    
    SickHistoryRealAggregator findByIds(Long id, String sick_id, List<String> fields_to_ignore);
    
    SickHistoryRealAggregator findByIds(Long id, String sick_id);
    
    SickHistoryReal insert(SickHistoryReal sickHistoryReal, Connection con);
    
    SickHistoryReal insert(SickHistoryReal sickHistoryReal);
    
    SickHistoryReal update(SickHistoryReal sickHistoryReal, boolean exclude_nulls, Connection con);
    
    SickHistoryReal update(SickHistoryReal sickHistoryReal, boolean exclude_nulls);
    
    SickHistoryReal save(SickHistoryReal sickHistoryReal, Connection con);
    
    SickHistoryReal save(SickHistoryReal sickHistoryReal);
    
    List<SickHistoryRealAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<SickHistoryRealAggregator> findAll(Connection con);
    
    List<SickHistoryRealAggregator> findAll(List<String> fields_to_ignore);
    
    List<SickHistoryRealAggregator> findAll();
    
    List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal, List<String> fields_to_ignore, Connection con);
    
    List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal, Connection con);
    
    List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal, List<String> fields_to_ignore);
    
    List<SickHistoryRealAggregator> findByModel(SickHistoryReal sickHistoryReal);
    
    void delete(Long id, String sick_id, Connection con);
    
    void delete(Long id, String sick_id);
    
    void deleteByModel(SickHistoryReal sickHistoryReal, Connection con);
    
    void deleteByModel(SickHistoryReal sickHistoryReal);
}
