/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.sql2o.Connection;

import com.arc.aggregator.TestRealAggregator;
import com.arc.model.TestReal;
import com.arc.repository.TestRealRepository;


@Service
public class TestRealServiceImpl implements TestRealService {
    @Autowired
    private TestRealRepository testRealRepository;
    
    private TestRealAggregator enrich(TestReal testReal) {
        TestRealAggregator testRealAggregator = null;
        
        if (testReal != null) {
            testRealAggregator = new TestRealAggregator();
            
            testRealAggregator.setTestReal(testReal);
        }
        
        return testRealAggregator;
    }
    
    private List<TestRealAggregator> enrich(List<TestReal> testReals) {
        final List<TestRealAggregator> testRealAggregators = new ArrayList<>();
        
        if (testReals != null) {
            for (TestReal testReal: testReals) {
                testRealAggregators.add(this.enrich(testReal));
            }
        }
        
        return testRealAggregators;
    }
    
    @Override
    public List<TestRealAggregator> findAll(List<String> fields_to_ignore, Connection con) {
        final List<TestReal> testReals = this.testRealRepository.findAll(fields_to_ignore, con);
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findAll(Connection con) {
        final List<TestReal> testReals = this.testRealRepository.findAll(con);
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findAll(List<String> fields_to_ignore) {
        final List<TestReal> testReals = this.testRealRepository.findAll(fields_to_ignore);
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findAll() {
        final List<TestReal> testReals = this.testRealRepository.findAll();
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findByModel(TestReal testReal, List<String> fields_to_ignore, Connection con) {
        final List<TestReal> testReals = this.testRealRepository.findByModel(testReal, fields_to_ignore, con);
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findByModel(TestReal testReal, Connection con) {
        final List<TestReal> testReals = this.testRealRepository.findByModel(testReal, con);
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findByModel(TestReal testReal, List<String> fields_to_ignore) {
        final List<TestReal> testReals = this.testRealRepository.findByModel(testReal, fields_to_ignore);
        
        return this.enrich(testReals);
    }
    
    @Override
    public List<TestRealAggregator> findByModel(TestReal testReal) {
        final List<TestReal> testReals = this.testRealRepository.findByModel(testReal);
        
        return this.enrich(testReals);
    }
    
    @Override
    public TestRealAggregator findByCode(Long code, List<String> fields_to_ignore, Connection con) {
        final TestReal testReal = this.testRealRepository.findByCode(code, fields_to_ignore, con);
        
        return this.enrich(testReal);
    }
    
    @Override
    public TestRealAggregator findByCode(Long code, Connection con) {
        final TestReal testReal = this.testRealRepository.findByCode(code, con);
        
        return this.enrich(testReal);
    }
    
    @Override
    public TestRealAggregator findByCode(Long code, List<String> fields_to_ignore) {
        final TestReal testReal = this.testRealRepository.findByCode(code, fields_to_ignore);
        
        return this.enrich(testReal);
    }
    
    @Override
    public TestRealAggregator findByCode(Long code) {
        final TestReal testReal = this.testRealRepository.findByCode(code);
        
        return this.enrich(testReal);
    }
    
    @Override
    public TestReal insert(TestReal testReal, Connection con) {
        return this.testRealRepository.insert(testReal, con);
    }
    
    @Override
    public TestReal insert(TestReal testReal) {
        return this.testRealRepository.insert(testReal);
    }
    
    @Override
    public TestReal update(TestReal testReal, boolean exclude_nulls, Connection con) {
        return this.testRealRepository.update(testReal, exclude_nulls, con);
    }
    
    @Override
    public TestReal update(TestReal testReal, boolean exclude_nulls) {
        return this.testRealRepository.update(testReal, exclude_nulls);
    }
    
    @Override
    public TestReal save(TestReal testReal, Connection con) {
        return this.testRealRepository.save(testReal, con);
    }
    
    @Override
    public TestReal save(TestReal testReal) {
        return this.testRealRepository.save(testReal);
    }
    
    @Override
    public void delete(Long code, Connection con) {
        this.testRealRepository.delete(code, con);
    }
    
    @Override
    public void delete(Long code) {
        this.testRealRepository.delete(code);
    }
    
    @Override
    public void deleteByModel(TestReal testReal, Connection con) {
        this.testRealRepository.deleteByModel(testReal, con);
    }
    
    @Override
    public void deleteByModel(TestReal testReal) {
        this.testRealRepository.deleteByModel(testReal);
    }
}
