/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.TrackingRealAggregator;
import com.arc.model.TrackingReal;


public interface TrackingRealService {
    TrackingRealAggregator findById(Long id, List<String> fields_to_ignore, Connection con);
    
    TrackingRealAggregator findById(Long id, Connection con);
    
    TrackingRealAggregator findById(Long id, List<String> fields_to_ignore);
    
    TrackingRealAggregator findById(Long id);
    
    TrackingReal insert(TrackingReal trackingReal, Connection con);
    
    TrackingReal insert(TrackingReal trackingReal);
    
    TrackingReal update(TrackingReal trackingReal, boolean exclude_nulls, Connection con);
    
    TrackingReal update(TrackingReal trackingReal, boolean exclude_nulls);
    
    TrackingReal save(TrackingReal trackingReal, Connection con);
    
    TrackingReal save(TrackingReal trackingReal);
    
    List<TrackingRealAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<TrackingRealAggregator> findAll(Connection con);
    
    List<TrackingRealAggregator> findAll(List<String> fields_to_ignore);
    
    List<TrackingRealAggregator> findAll();
    
    List<TrackingRealAggregator> findByModel(TrackingReal trackingReal, List<String> fields_to_ignore, Connection con);
    
    List<TrackingRealAggregator> findByModel(TrackingReal trackingReal, Connection con);
    
    List<TrackingRealAggregator> findByModel(TrackingReal trackingReal, List<String> fields_to_ignore);
    
    List<TrackingRealAggregator> findByModel(TrackingReal trackingReal);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(TrackingReal trackingReal, Connection con);
    
    void deleteByModel(TrackingReal trackingReal);
}
