/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.TrackingAggregator;
import com.arc.model.Tracking;


public interface TrackingService {
    TrackingAggregator findById(Long id, List<String> fields_to_ignore, Connection con);
    
    TrackingAggregator findById(Long id, Connection con);
    
    TrackingAggregator findById(Long id, List<String> fields_to_ignore);
    
    TrackingAggregator findById(Long id);
    
    Tracking insert(Tracking tracking, Connection con);
    
    Tracking insert(Tracking tracking);
    
    Tracking update(Tracking tracking, boolean exclude_nulls, Connection con);
    
    Tracking update(Tracking tracking, boolean exclude_nulls);
    
    Tracking save(Tracking tracking, Connection con);
    
    Tracking save(Tracking tracking);
    
    List<TrackingAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<TrackingAggregator> findAll(Connection con);
    
    List<TrackingAggregator> findAll(List<String> fields_to_ignore);
    
    List<TrackingAggregator> findAll();
    
    List<TrackingAggregator> findByModel(Tracking tracking, List<String> fields_to_ignore, Connection con);
    
    List<TrackingAggregator> findByModel(Tracking tracking, Connection con);
    
    List<TrackingAggregator> findByModel(Tracking tracking, List<String> fields_to_ignore);
    
    List<TrackingAggregator> findByModel(Tracking tracking);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(Tracking tracking, Connection con);
    
    void deleteByModel(Tracking tracking);
}
