/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.ActionLog;
import com.arc.repository.ActionLogRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class ActionLogRepositoryImpl implements ActionLogRepository {
    private final static Logger logger = LoggerFactory.getLogger(ActionLogRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "a.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DESCRIPTION")) {
            res += "a.DESCRIPTION, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "a.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TIME")) {
            res += "a.TIME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("USERNAME")) {
            res += "a.USERNAME, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public ActionLog findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + ActionLogRepositoryImpl.getSelectBase(fields_to_ignore) + "from ACTION_LOGS a ";
        sql += "where "; 
        sql += "ID = :id ";
        
        ActionLog res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(ActionLog.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public ActionLog findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public ActionLog findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public ActionLog findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<ActionLog> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + ActionLogRepositoryImpl.getSelectBase(fields_to_ignore) + "from ACTION_LOGS a ";
        
        List<ActionLog> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(ActionLog.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<ActionLog> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<ActionLog> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<ActionLog> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<ActionLog> findByModel(ActionLog actionLog, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + ActionLogRepositoryImpl.getSelectBase(fields_to_ignore) + "from ACTION_LOGS a ";
        sql += "where ";
        
        if (actionLog.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (actionLog.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (actionLog.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (actionLog.getTime() != null) { 
            sql += "TIME = :time and ";
        }
        
        if (actionLog.getUsername() != null) { 
            sql += "USERNAME = :username and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<ActionLog> res;
        
        try (Query query = con.createQuery(sql)) {
            if (actionLog.getDate() != null) {
                query.addParameter("date", actionLog.getDate());
            }
            
            if (actionLog.getDescription() != null) {
                query.addParameter("description", actionLog.getDescription());
            }
            
            if (actionLog.getId() != null) {
                query.addParameter("id", actionLog.getId());
            }
            
            if (actionLog.getTime() != null) {
                query.addParameter("time", actionLog.getTime());
            }
            
            if (actionLog.getUsername() != null) {
                query.addParameter("username", actionLog.getUsername());
            }
            
            res = query.executeAndFetch(ActionLog.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<ActionLog> findByModel(ActionLog actionLog, Connection con) {
        return this.findByModel(actionLog, null, con);
    }
    
    @Override
    public List<ActionLog> findByModel(ActionLog actionLog, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(actionLog, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<ActionLog> findByModel(ActionLog actionLog) {
        return this.findByModel(actionLog, (List<String>) null);
    }
    
    @Override
    public ActionLog insert(ActionLog actionLog, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into ACTION_LOGS ( " + 
                "DATE, " + 
                "DESCRIPTION, " + 
                "ID, " + 
                "TIME, " + 
                "USERNAME " + 
            ") " + 
            "values (" +
                ":date, " + 
                ":description, " + 
                ":id, " + 
                ":time, " + 
                ":username " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(actionLog);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("ACTION_LOGS", "ID", con, key, Long.class);
        actionLog.setId(res);
        logger.info("<< DB insert() - END");
        return actionLog;
    }
    
    @Override
    public ActionLog insert(ActionLog actionLog) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(actionLog, con);
            con.commit();
            return actionLog;
        }
    }
    
    @Override
    public ActionLog update(ActionLog actionLog, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + actionLog.getId());
        
        String sql = "update ACTION_LOGS set ";
        
        if (! exclude_nulls || actionLog.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || actionLog.getDescription() != null) { 
            sql += "DESCRIPTION = :description, ";
        }
        
        if (! exclude_nulls || actionLog.getTime() != null) { 
            sql += "TIME = :time, ";
        }
        
        if (! exclude_nulls || actionLog.getUsername() != null) { 
            sql += "USERNAME = :username, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || actionLog.getDate() != null) {
                query.addParameter("date", actionLog.getDate());
            }
            
            if (! exclude_nulls || actionLog.getDescription() != null) {
                query.addParameter("description", actionLog.getDescription());
            }
            
            if (! exclude_nulls || actionLog.getId() != null) {
                query.addParameter("id", actionLog.getId());
            }
            
            if (! exclude_nulls || actionLog.getTime() != null) {
                query.addParameter("time", actionLog.getTime());
            }
            
            if (! exclude_nulls || actionLog.getUsername() != null) {
                query.addParameter("username", actionLog.getUsername());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return actionLog;
    }
    
    @Override
    public ActionLog update(ActionLog actionLog, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(actionLog, exclude_nulls, con);
            con.commit();
            return actionLog;
        }
    }
    
    @Override
    public ActionLog save(ActionLog actionLog, Connection con) {
        final Long id = actionLog.getId();

        final ActionLog actionLog2 = this.findById(id, null, con);
        
        if (actionLog2 == null) {
            return this.insert(actionLog, con);
        }
        return this.update(actionLog, false, con);
    }
    
    @Override
    public ActionLog save(ActionLog actionLog) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(actionLog, con);
            con.commit();
            return actionLog;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from ACTION_LOGS ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(ActionLog actionLog, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from ACTION_LOGS ";
        sql += "where ";
        
        if (actionLog.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (actionLog.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (actionLog.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (actionLog.getTime() != null) { 
            sql += "TIME = :time and ";
        }
        
        if (actionLog.getUsername() != null) { 
            sql += "USERNAME = :username and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (actionLog.getDate() != null) {
                query.addParameter("date", actionLog.getDate());
            }
            
            if (actionLog.getDescription() != null) {
                query.addParameter("description", actionLog.getDescription());
            }
            
            if (actionLog.getId() != null) {
                query.addParameter("id", actionLog.getId());
            }
            
            if (actionLog.getTime() != null) {
                query.addParameter("time", actionLog.getTime());
            }
            
            if (actionLog.getUsername() != null) {
                query.addParameter("username", actionLog.getUsername());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(ActionLog actionLog) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(actionLog, con);
            con.commit();
        }
    }
}
