/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.BlackList;
import com.arc.repository.BlackListRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class BlackListRepositoryImpl implements BlackListRepository {
    private final static Logger logger = LoggerFactory.getLogger(BlackListRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DESCRIPTION")) {
            res += "b.DESCRIPTION, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "b.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "b.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "b.SICK_NAME, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public BlackList findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + BlackListRepositoryImpl.getSelectBase(fields_to_ignore) + "from BLACK_LIST b ";
        sql += "where "; 
        sql += "ID = :id ";
        
        BlackList res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(BlackList.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public BlackList findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public BlackList findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public BlackList findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<BlackList> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + BlackListRepositoryImpl.getSelectBase(fields_to_ignore) + "from BLACK_LIST b ";
        
        List<BlackList> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(BlackList.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<BlackList> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<BlackList> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<BlackList> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<BlackList> findByModel(BlackList blackList, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + BlackListRepositoryImpl.getSelectBase(fields_to_ignore) + "from BLACK_LIST b ";
        sql += "where ";
        
        if (blackList.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (blackList.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (blackList.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (blackList.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<BlackList> res;
        
        try (Query query = con.createQuery(sql)) {
            if (blackList.getDescription() != null) {
                query.addParameter("description", blackList.getDescription());
            }
            
            if (blackList.getId() != null) {
                query.addParameter("id", blackList.getId());
            }
            
            if (blackList.getSick_id() != null) {
                query.addParameter("sick_id", blackList.getSick_id());
            }
            
            if (blackList.getSick_name() != null) {
                query.addParameter("sick_name", blackList.getSick_name());
            }
            
            res = query.executeAndFetch(BlackList.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<BlackList> findByModel(BlackList blackList, Connection con) {
        return this.findByModel(blackList, null, con);
    }
    
    @Override
    public List<BlackList> findByModel(BlackList blackList, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(blackList, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<BlackList> findByModel(BlackList blackList) {
        return this.findByModel(blackList, (List<String>) null);
    }
    
    @Override
    public BlackList insert(BlackList blackList, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into BLACK_LIST ( " + 
                "DESCRIPTION, " + 
                "ID, " + 
                "SICK_ID, " + 
                "SICK_NAME " + 
            ") " + 
            "values (" +
                ":description, " + 
                ":id, " + 
                ":sick_id, " + 
                ":sick_name " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(blackList);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("BLACK_LIST", "ID", con, key, Long.class);
        blackList.setId(res);
        logger.info("<< DB insert() - END");
        return blackList;
    }
    
    @Override
    public BlackList insert(BlackList blackList) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(blackList, con);
            con.commit();
            return blackList;
        }
    }
    
    @Override
    public BlackList update(BlackList blackList, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + blackList.getId());
        
        String sql = "update BLACK_LIST set ";
        
        if (! exclude_nulls || blackList.getDescription() != null) { 
            sql += "DESCRIPTION = :description, ";
        }
        
        if (! exclude_nulls || blackList.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || blackList.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || blackList.getDescription() != null) {
                query.addParameter("description", blackList.getDescription());
            }
            
            if (! exclude_nulls || blackList.getId() != null) {
                query.addParameter("id", blackList.getId());
            }
            
            if (! exclude_nulls || blackList.getSick_id() != null) {
                query.addParameter("sick_id", blackList.getSick_id());
            }
            
            if (! exclude_nulls || blackList.getSick_name() != null) {
                query.addParameter("sick_name", blackList.getSick_name());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return blackList;
    }
    
    @Override
    public BlackList update(BlackList blackList, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(blackList, exclude_nulls, con);
            con.commit();
            return blackList;
        }
    }
    
    @Override
    public BlackList save(BlackList blackList, Connection con) {
        final Long id = blackList.getId();

        final BlackList blackList2 = this.findById(id, null, con);
        
        if (blackList2 == null) {
            return this.insert(blackList, con);
        }
        return this.update(blackList, false, con);
    }
    
    @Override
    public BlackList save(BlackList blackList) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(blackList, con);
            con.commit();
            return blackList;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from BLACK_LIST ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(BlackList blackList, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from BLACK_LIST ";
        sql += "where ";
        
        if (blackList.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (blackList.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (blackList.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (blackList.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (blackList.getDescription() != null) {
                query.addParameter("description", blackList.getDescription());
            }
            
            if (blackList.getId() != null) {
                query.addParameter("id", blackList.getId());
            }
            
            if (blackList.getSick_id() != null) {
                query.addParameter("sick_id", blackList.getSick_id());
            }
            
            if (blackList.getSick_name() != null) {
                query.addParameter("sick_name", blackList.getSick_name());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(BlackList blackList) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(blackList, con);
            con.commit();
        }
    }
}
