/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.ClinicInfo;
import com.arc.repository.ClinicInfoRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class ClinicInfoRepositoryImpl implements ClinicInfoRepository {
    private final static Logger logger = LoggerFactory.getLogger(ClinicInfoRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ADDRESS")) {
            res += "c.ADDRESS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("GEN_PASS")) {
            res += "c.GEN_PASS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("NAME")) {
            res += "c.NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("PHOTO")) {
            res += "c.PHOTO, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TEL")) {
            res += "c.TEL, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public ClinicInfo findByName(String name, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByName() - name: " + name);
        
        String sql = "select " + ClinicInfoRepositoryImpl.getSelectBase(fields_to_ignore) + "from CLINIC_INFO c ";
        sql += "where "; 
        sql += "NAME = :name ";
        
        ClinicInfo res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("name", name);

            res = query.executeAndFetchFirst(ClinicInfo.class);
        }
        
        logger.debug("<< DB getByName() - END");
        return res;
    }
    
    @Override
    public ClinicInfo findByName(String name, Connection con) {
        return this.findByName(name, null, con);
    }
    
    @Override
    public ClinicInfo findByName(String name, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByName(name, fields_to_ignore, con);
        }
    }
    
    @Override
    public ClinicInfo findByName(String name) {
        return this.findByName(name, (List<String>) null);
    }
    
    @Override
    public List<ClinicInfo> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + ClinicInfoRepositoryImpl.getSelectBase(fields_to_ignore) + "from CLINIC_INFO c ";
        
        List<ClinicInfo> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(ClinicInfo.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<ClinicInfo> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<ClinicInfo> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<ClinicInfo> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<ClinicInfo> findByModel(ClinicInfo clinicInfo, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + ClinicInfoRepositoryImpl.getSelectBase(fields_to_ignore) + "from CLINIC_INFO c ";
        sql += "where ";
        
        if (clinicInfo.getAddress() != null) { 
            sql += "ADDRESS = :address and ";
        }
        
        if (clinicInfo.getGen_pass() != null) { 
            sql += "GEN_PASS = :gen_pass and ";
        }
        
        if (clinicInfo.getName() != null) { 
            sql += "NAME = :name and ";
        }
        
        if (clinicInfo.getPhoto() != null) { 
            sql += "PHOTO = :photo and ";
        }
        
        if (clinicInfo.getTel() != null) { 
            sql += "TEL = :tel and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<ClinicInfo> res;
        
        try (Query query = con.createQuery(sql)) {
            if (clinicInfo.getAddress() != null) {
                query.addParameter("address", clinicInfo.getAddress());
            }
            
            if (clinicInfo.getGen_pass() != null) {
                query.addParameter("gen_pass", clinicInfo.getGen_pass());
            }
            
            if (clinicInfo.getName() != null) {
                query.addParameter("name", clinicInfo.getName());
            }
            
            if (clinicInfo.getPhoto() != null) {
                query.addParameter("photo", clinicInfo.getPhoto());
            }
            
            if (clinicInfo.getTel() != null) {
                query.addParameter("tel", clinicInfo.getTel());
            }
            
            res = query.executeAndFetch(ClinicInfo.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<ClinicInfo> findByModel(ClinicInfo clinicInfo, Connection con) {
        return this.findByModel(clinicInfo, null, con);
    }
    
    @Override
    public List<ClinicInfo> findByModel(ClinicInfo clinicInfo, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(clinicInfo, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<ClinicInfo> findByModel(ClinicInfo clinicInfo) {
        return this.findByModel(clinicInfo, (List<String>) null);
    }
    
    @Override
    public ClinicInfo insert(ClinicInfo clinicInfo, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into CLINIC_INFO ( " + 
                "ADDRESS, " + 
                "GEN_PASS, " + 
                "NAME, " + 
                "PHOTO, " + 
                "TEL " + 
            ") " + 
            "values (" +
                ":address, " + 
                ":gen_pass, " + 
                ":name, " + 
                ":photo, " + 
                ":tel " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(clinicInfo);

            key = query.executeUpdate().getKey();
        }
        
        final String res = Sql2oUtility.getInsertedId("CLINIC_INFO", "NAME", con, key, String.class);
        clinicInfo.setName(res);
        logger.info("<< DB insert() - END");
        return clinicInfo;
    }
    
    @Override
    public ClinicInfo insert(ClinicInfo clinicInfo) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(clinicInfo, con);
            con.commit();
            return clinicInfo;
        }
    }
    
    @Override
    public ClinicInfo update(ClinicInfo clinicInfo, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - name: " + clinicInfo.getName());
        
        String sql = "update CLINIC_INFO set ";
        
        if (! exclude_nulls || clinicInfo.getAddress() != null) { 
            sql += "ADDRESS = :address, ";
        }
        
        if (! exclude_nulls || clinicInfo.getGen_pass() != null) { 
            sql += "GEN_PASS = :gen_pass, ";
        }
        
        if (! exclude_nulls || clinicInfo.getPhoto() != null) { 
            sql += "PHOTO = :photo, ";
        }
        
        if (! exclude_nulls || clinicInfo.getTel() != null) { 
            sql += "TEL = :tel, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "NAME = :name ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || clinicInfo.getAddress() != null) {
                query.addParameter("address", clinicInfo.getAddress());
            }
            
            if (! exclude_nulls || clinicInfo.getGen_pass() != null) {
                query.addParameter("gen_pass", clinicInfo.getGen_pass());
            }
            
            if (! exclude_nulls || clinicInfo.getName() != null) {
                query.addParameter("name", clinicInfo.getName());
            }
            
            if (! exclude_nulls || clinicInfo.getPhoto() != null) {
                query.addParameter("photo", clinicInfo.getPhoto());
            }
            
            if (! exclude_nulls || clinicInfo.getTel() != null) {
                query.addParameter("tel", clinicInfo.getTel());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return clinicInfo;
    }
    
    @Override
    public ClinicInfo update(ClinicInfo clinicInfo, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(clinicInfo, exclude_nulls, con);
            con.commit();
            return clinicInfo;
        }
    }
    
    @Override
    public ClinicInfo save(ClinicInfo clinicInfo, Connection con) {
        final String name = clinicInfo.getName();

        final ClinicInfo clinicInfo2 = this.findByName(name, null, con);
        
        if (clinicInfo2 == null) {
            return this.insert(clinicInfo, con);
        }
        return this.update(clinicInfo, false, con);
    }
    
    @Override
    public ClinicInfo save(ClinicInfo clinicInfo) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(clinicInfo, con);
            con.commit();
            return clinicInfo;
        }
    }
    
    @Override
    public void delete(String name, Connection con) {
        logger.info("DB>> delete() - name: " + name);
        
        String sql = "delete from CLINIC_INFO ";
        sql += "where "; 
        sql += "NAME = :name ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("name", name);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(String name) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(name, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(ClinicInfo clinicInfo, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from CLINIC_INFO ";
        sql += "where ";
        
        if (clinicInfo.getAddress() != null) { 
            sql += "ADDRESS = :address and ";
        }
        
        if (clinicInfo.getGen_pass() != null) { 
            sql += "GEN_PASS = :gen_pass and ";
        }
        
        if (clinicInfo.getName() != null) { 
            sql += "NAME = :name and ";
        }
        
        if (clinicInfo.getPhoto() != null) { 
            sql += "PHOTO = :photo and ";
        }
        
        if (clinicInfo.getTel() != null) { 
            sql += "TEL = :tel and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (clinicInfo.getAddress() != null) {
                query.addParameter("address", clinicInfo.getAddress());
            }
            
            if (clinicInfo.getGen_pass() != null) {
                query.addParameter("gen_pass", clinicInfo.getGen_pass());
            }
            
            if (clinicInfo.getName() != null) {
                query.addParameter("name", clinicInfo.getName());
            }
            
            if (clinicInfo.getPhoto() != null) {
                query.addParameter("photo", clinicInfo.getPhoto());
            }
            
            if (clinicInfo.getTel() != null) {
                query.addParameter("tel", clinicInfo.getTel());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(ClinicInfo clinicInfo) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(clinicInfo, con);
            con.commit();
        }
    }
}
