/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.Expense;
import com.arc.repository.ExpenseRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class ExpenseRepositoryImpl implements ExpenseRepository {
    private final static Logger logger = LoggerFactory.getLogger(ExpenseRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COMMENTS")) {
            res += "e.COMMENTS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COST")) {
            res += "e.COST, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "e.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "e.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TYPE")) {
            res += "e.TYPE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public Expense findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + ExpenseRepositoryImpl.getSelectBase(fields_to_ignore) + "from EXPENSES e ";
        sql += "where "; 
        sql += "ID = :id ";
        
        Expense res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(Expense.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public Expense findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public Expense findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public Expense findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<Expense> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + ExpenseRepositoryImpl.getSelectBase(fields_to_ignore) + "from EXPENSES e ";
        
        List<Expense> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(Expense.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<Expense> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<Expense> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Expense> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<Expense> findByModel(Expense expense, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + ExpenseRepositoryImpl.getSelectBase(fields_to_ignore) + "from EXPENSES e ";
        sql += "where ";
        
        if (expense.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (expense.getCost() != null) { 
            sql += "COST = :cost and ";
        }
        
        if (expense.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (expense.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (expense.getType() != null) { 
            sql += "TYPE = :type and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<Expense> res;
        
        try (Query query = con.createQuery(sql)) {
            if (expense.getComments() != null) {
                query.addParameter("comments", expense.getComments());
            }
            
            if (expense.getCost() != null) {
                query.addParameter("cost", expense.getCost());
            }
            
            if (expense.getDate() != null) {
                query.addParameter("date", expense.getDate());
            }
            
            if (expense.getId() != null) {
                query.addParameter("id", expense.getId());
            }
            
            if (expense.getType() != null) {
                query.addParameter("type", expense.getType());
            }
            
            res = query.executeAndFetch(Expense.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<Expense> findByModel(Expense expense, Connection con) {
        return this.findByModel(expense, null, con);
    }
    
    @Override
    public List<Expense> findByModel(Expense expense, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(expense, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Expense> findByModel(Expense expense) {
        return this.findByModel(expense, (List<String>) null);
    }
    
    @Override
    public Expense insert(Expense expense, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into EXPENSES ( " + 
                "COMMENTS, " + 
                "COST, " + 
                "DATE, " + 
                "ID, " + 
                "TYPE " + 
            ") " + 
            "values (" +
                ":comments, " + 
                ":cost, " + 
                ":date, " + 
                ":id, " + 
                ":type " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(expense);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("EXPENSES", "ID", con, key, Long.class);
        expense.setId(res);
        logger.info("<< DB insert() - END");
        return expense;
    }
    
    @Override
    public Expense insert(Expense expense) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(expense, con);
            con.commit();
            return expense;
        }
    }
    
    @Override
    public Expense update(Expense expense, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + expense.getId());
        
        String sql = "update EXPENSES set ";
        
        if (! exclude_nulls || expense.getComments() != null) { 
            sql += "COMMENTS = :comments, ";
        }
        
        if (! exclude_nulls || expense.getCost() != null) { 
            sql += "COST = :cost, ";
        }
        
        if (! exclude_nulls || expense.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || expense.getType() != null) { 
            sql += "TYPE = :type, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || expense.getComments() != null) {
                query.addParameter("comments", expense.getComments());
            }
            
            if (! exclude_nulls || expense.getCost() != null) {
                query.addParameter("cost", expense.getCost());
            }
            
            if (! exclude_nulls || expense.getDate() != null) {
                query.addParameter("date", expense.getDate());
            }
            
            if (! exclude_nulls || expense.getId() != null) {
                query.addParameter("id", expense.getId());
            }
            
            if (! exclude_nulls || expense.getType() != null) {
                query.addParameter("type", expense.getType());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return expense;
    }
    
    @Override
    public Expense update(Expense expense, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(expense, exclude_nulls, con);
            con.commit();
            return expense;
        }
    }
    
    @Override
    public Expense save(Expense expense, Connection con) {
        final Long id = expense.getId();

        final Expense expense2 = this.findById(id, null, con);
        
        if (expense2 == null) {
            return this.insert(expense, con);
        }
        return this.update(expense, false, con);
    }
    
    @Override
    public Expense save(Expense expense) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(expense, con);
            con.commit();
            return expense;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from EXPENSES ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(Expense expense, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from EXPENSES ";
        sql += "where ";
        
        if (expense.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (expense.getCost() != null) { 
            sql += "COST = :cost and ";
        }
        
        if (expense.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (expense.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (expense.getType() != null) { 
            sql += "TYPE = :type and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (expense.getComments() != null) {
                query.addParameter("comments", expense.getComments());
            }
            
            if (expense.getCost() != null) {
                query.addParameter("cost", expense.getCost());
            }
            
            if (expense.getDate() != null) {
                query.addParameter("date", expense.getDate());
            }
            
            if (expense.getId() != null) {
                query.addParameter("id", expense.getId());
            }
            
            if (expense.getType() != null) {
                query.addParameter("type", expense.getType());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(Expense expense) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(expense, con);
            con.commit();
        }
    }
}
