/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.MapA;
import com.arc.repository.MapARepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class MapARepositoryImpl implements MapARepository {
    private final static Logger logger = LoggerFactory.getLogger(MapARepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("CODE")) {
            res += "m.CODE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "m.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("MASRAFI_TYPE")) {
            res += "m.MASRAFI_TYPE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("MIZAN")) {
            res += "m.MIZAN, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ROOZ")) {
            res += "m.ROOZ, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TARIGHEH")) {
            res += "m.TARIGHEH, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public MapA findByCode(Long code, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByCode() - code: " + code);
        
        String sql = "select " + MapARepositoryImpl.getSelectBase(fields_to_ignore) + "from MAP_A m ";
        sql += "where "; 
        sql += "CODE = :code ";
        
        MapA res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("code", code);

            res = query.executeAndFetchFirst(MapA.class);
        }
        
        logger.debug("<< DB getByCode() - END");
        return res;
    }
    
    @Override
    public MapA findByCode(Long code, Connection con) {
        return this.findByCode(code, null, con);
    }
    
    @Override
    public MapA findByCode(Long code, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByCode(code, fields_to_ignore, con);
        }
    }
    
    @Override
    public MapA findByCode(Long code) {
        return this.findByCode(code, (List<String>) null);
    }
    
    @Override
    public List<MapA> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + MapARepositoryImpl.getSelectBase(fields_to_ignore) + "from MAP_A m ";
        
        List<MapA> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(MapA.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<MapA> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<MapA> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<MapA> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<MapA> findByModel(MapA mapA, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + MapARepositoryImpl.getSelectBase(fields_to_ignore) + "from MAP_A m ";
        sql += "where ";
        
        if (mapA.getCode() != null) { 
            sql += "CODE = :code and ";
        }
        
        if (mapA.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (mapA.getMasrafi_type() != null) { 
            sql += "MASRAFI_TYPE = :masrafi_type and ";
        }
        
        if (mapA.getMizan() != null) { 
            sql += "MIZAN = :mizan and ";
        }
        
        if (mapA.getRooz() != null) { 
            sql += "ROOZ = :rooz and ";
        }
        
        if (mapA.getTarigheh() != null) { 
            sql += "TARIGHEH = :tarigheh and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<MapA> res;
        
        try (Query query = con.createQuery(sql)) {
            if (mapA.getCode() != null) {
                query.addParameter("code", mapA.getCode());
            }
            
            if (mapA.getId() != null) {
                query.addParameter("id", mapA.getId());
            }
            
            if (mapA.getMasrafi_type() != null) {
                query.addParameter("masrafi_type", mapA.getMasrafi_type());
            }
            
            if (mapA.getMizan() != null) {
                query.addParameter("mizan", mapA.getMizan());
            }
            
            if (mapA.getRooz() != null) {
                query.addParameter("rooz", mapA.getRooz());
            }
            
            if (mapA.getTarigheh() != null) {
                query.addParameter("tarigheh", mapA.getTarigheh());
            }
            
            res = query.executeAndFetch(MapA.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<MapA> findByModel(MapA mapA, Connection con) {
        return this.findByModel(mapA, null, con);
    }
    
    @Override
    public List<MapA> findByModel(MapA mapA, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(mapA, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<MapA> findByModel(MapA mapA) {
        return this.findByModel(mapA, (List<String>) null);
    }
    
    @Override
    public MapA insert(MapA mapA, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into MAP_A ( " + 
                "CODE, " + 
                "ID, " + 
                "MASRAFI_TYPE, " + 
                "MIZAN, " + 
                "ROOZ, " + 
                "TARIGHEH " + 
            ") " + 
            "values (" +
                ":code, " + 
                ":id, " + 
                ":masrafi_type, " + 
                ":mizan, " + 
                ":rooz, " + 
                ":tarigheh " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(mapA);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("MAP_A", "CODE", con, key, Long.class);
        mapA.setCode(res);
        logger.info("<< DB insert() - END");
        return mapA;
    }
    
    @Override
    public MapA insert(MapA mapA) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(mapA, con);
            con.commit();
            return mapA;
        }
    }
    
    @Override
    public MapA update(MapA mapA, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - code: " + mapA.getCode());
        
        String sql = "update MAP_A set ";
        
        if (! exclude_nulls || mapA.getId() != null) { 
            sql += "ID = :id, ";
        }
        
        if (! exclude_nulls || mapA.getMasrafi_type() != null) { 
            sql += "MASRAFI_TYPE = :masrafi_type, ";
        }
        
        if (! exclude_nulls || mapA.getMizan() != null) { 
            sql += "MIZAN = :mizan, ";
        }
        
        if (! exclude_nulls || mapA.getRooz() != null) { 
            sql += "ROOZ = :rooz, ";
        }
        
        if (! exclude_nulls || mapA.getTarigheh() != null) { 
            sql += "TARIGHEH = :tarigheh, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "CODE = :code ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || mapA.getCode() != null) {
                query.addParameter("code", mapA.getCode());
            }
            
            if (! exclude_nulls || mapA.getId() != null) {
                query.addParameter("id", mapA.getId());
            }
            
            if (! exclude_nulls || mapA.getMasrafi_type() != null) {
                query.addParameter("masrafi_type", mapA.getMasrafi_type());
            }
            
            if (! exclude_nulls || mapA.getMizan() != null) {
                query.addParameter("mizan", mapA.getMizan());
            }
            
            if (! exclude_nulls || mapA.getRooz() != null) {
                query.addParameter("rooz", mapA.getRooz());
            }
            
            if (! exclude_nulls || mapA.getTarigheh() != null) {
                query.addParameter("tarigheh", mapA.getTarigheh());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return mapA;
    }
    
    @Override
    public MapA update(MapA mapA, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(mapA, exclude_nulls, con);
            con.commit();
            return mapA;
        }
    }
    
    @Override
    public MapA save(MapA mapA, Connection con) {
        final Long code = mapA.getCode();

        final MapA mapA2 = this.findByCode(code, null, con);
        
        if (mapA2 == null) {
            return this.insert(mapA, con);
        }
        return this.update(mapA, false, con);
    }
    
    @Override
    public MapA save(MapA mapA) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(mapA, con);
            con.commit();
            return mapA;
        }
    }
    
    @Override
    public void delete(Long code, Connection con) {
        logger.info("DB>> delete() - code: " + code);
        
        String sql = "delete from MAP_A ";
        sql += "where "; 
        sql += "CODE = :code ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("code", code);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long code) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(code, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(MapA mapA, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from MAP_A ";
        sql += "where ";
        
        if (mapA.getCode() != null) { 
            sql += "CODE = :code and ";
        }
        
        if (mapA.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (mapA.getMasrafi_type() != null) { 
            sql += "MASRAFI_TYPE = :masrafi_type and ";
        }
        
        if (mapA.getMizan() != null) { 
            sql += "MIZAN = :mizan and ";
        }
        
        if (mapA.getRooz() != null) { 
            sql += "ROOZ = :rooz and ";
        }
        
        if (mapA.getTarigheh() != null) { 
            sql += "TARIGHEH = :tarigheh and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (mapA.getCode() != null) {
                query.addParameter("code", mapA.getCode());
            }
            
            if (mapA.getId() != null) {
                query.addParameter("id", mapA.getId());
            }
            
            if (mapA.getMasrafi_type() != null) {
                query.addParameter("masrafi_type", mapA.getMasrafi_type());
            }
            
            if (mapA.getMizan() != null) {
                query.addParameter("mizan", mapA.getMizan());
            }
            
            if (mapA.getRooz() != null) {
                query.addParameter("rooz", mapA.getRooz());
            }
            
            if (mapA.getTarigheh() != null) {
                query.addParameter("tarigheh", mapA.getTarigheh());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(MapA mapA) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(mapA, con);
            con.commit();
        }
    }
}
