/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.NurseDepot;
import com.arc.repository.NurseDepotRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class NurseDepotRepositoryImpl implements NurseDepotRepository {
    private final static Logger logger = LoggerFactory.getLogger(NurseDepotRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DRUG_NAME")) {
            res += "n.DRUG_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("REMAINED")) {
            res += "n.REMAINED, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("UNIT")) {
            res += "n.UNIT, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public NurseDepot findByDrug_name(String drug_name, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByDrug_name() - drug_name: " + drug_name);
        
        String sql = "select " + NurseDepotRepositoryImpl.getSelectBase(fields_to_ignore) + "from NURSE_DEPOT n ";
        sql += "where "; 
        sql += "DRUG_NAME = :drug_name ";
        
        NurseDepot res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("drug_name", drug_name);

            res = query.executeAndFetchFirst(NurseDepot.class);
        }
        
        logger.debug("<< DB getByDrug_name() - END");
        return res;
    }
    
    @Override
    public NurseDepot findByDrug_name(String drug_name, Connection con) {
        return this.findByDrug_name(drug_name, null, con);
    }
    
    @Override
    public NurseDepot findByDrug_name(String drug_name, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByDrug_name(drug_name, fields_to_ignore, con);
        }
    }
    
    @Override
    public NurseDepot findByDrug_name(String drug_name) {
        return this.findByDrug_name(drug_name, (List<String>) null);
    }
    
    @Override
    public List<NurseDepot> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + NurseDepotRepositoryImpl.getSelectBase(fields_to_ignore) + "from NURSE_DEPOT n ";
        
        List<NurseDepot> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(NurseDepot.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<NurseDepot> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<NurseDepot> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<NurseDepot> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<NurseDepot> findByModel(NurseDepot nurseDepot, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + NurseDepotRepositoryImpl.getSelectBase(fields_to_ignore) + "from NURSE_DEPOT n ";
        sql += "where ";
        
        if (nurseDepot.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (nurseDepot.getRemained() != null) { 
            sql += "REMAINED = :remained and ";
        }
        
        if (nurseDepot.getUnit() != null) { 
            sql += "UNIT = :unit and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<NurseDepot> res;
        
        try (Query query = con.createQuery(sql)) {
            if (nurseDepot.getDrug_name() != null) {
                query.addParameter("drug_name", nurseDepot.getDrug_name());
            }
            
            if (nurseDepot.getRemained() != null) {
                query.addParameter("remained", nurseDepot.getRemained());
            }
            
            if (nurseDepot.getUnit() != null) {
                query.addParameter("unit", nurseDepot.getUnit());
            }
            
            res = query.executeAndFetch(NurseDepot.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<NurseDepot> findByModel(NurseDepot nurseDepot, Connection con) {
        return this.findByModel(nurseDepot, null, con);
    }
    
    @Override
    public List<NurseDepot> findByModel(NurseDepot nurseDepot, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(nurseDepot, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<NurseDepot> findByModel(NurseDepot nurseDepot) {
        return this.findByModel(nurseDepot, (List<String>) null);
    }
    
    @Override
    public NurseDepot insert(NurseDepot nurseDepot, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into NURSE_DEPOT ( " + 
                "DRUG_NAME, " + 
                "REMAINED, " + 
                "UNIT " + 
            ") " + 
            "values (" +
                ":drug_name, " + 
                ":remained, " + 
                ":unit " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(nurseDepot);

            key = query.executeUpdate().getKey();
        }
        
        final String res = Sql2oUtility.getInsertedId("NURSE_DEPOT", "DRUG_NAME", con, key, String.class);
        nurseDepot.setDrug_name(res);
        logger.info("<< DB insert() - END");
        return nurseDepot;
    }
    
    @Override
    public NurseDepot insert(NurseDepot nurseDepot) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(nurseDepot, con);
            con.commit();
            return nurseDepot;
        }
    }
    
    @Override
    public NurseDepot update(NurseDepot nurseDepot, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - drug_name: " + nurseDepot.getDrug_name());
        
        String sql = "update NURSE_DEPOT set ";
        
        if (! exclude_nulls || nurseDepot.getRemained() != null) { 
            sql += "REMAINED = :remained, ";
        }
        
        if (! exclude_nulls || nurseDepot.getUnit() != null) { 
            sql += "UNIT = :unit, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || nurseDepot.getDrug_name() != null) {
                query.addParameter("drug_name", nurseDepot.getDrug_name());
            }
            
            if (! exclude_nulls || nurseDepot.getRemained() != null) {
                query.addParameter("remained", nurseDepot.getRemained());
            }
            
            if (! exclude_nulls || nurseDepot.getUnit() != null) {
                query.addParameter("unit", nurseDepot.getUnit());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return nurseDepot;
    }
    
    @Override
    public NurseDepot update(NurseDepot nurseDepot, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(nurseDepot, exclude_nulls, con);
            con.commit();
            return nurseDepot;
        }
    }
    
    @Override
    public NurseDepot save(NurseDepot nurseDepot, Connection con) {
        final String drug_name = nurseDepot.getDrug_name();

        final NurseDepot nurseDepot2 = this.findByDrug_name(drug_name, null, con);
        
        if (nurseDepot2 == null) {
            return this.insert(nurseDepot, con);
        }
        return this.update(nurseDepot, false, con);
    }
    
    @Override
    public NurseDepot save(NurseDepot nurseDepot) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(nurseDepot, con);
            con.commit();
            return nurseDepot;
        }
    }
    
    @Override
    public void delete(String drug_name, Connection con) {
        logger.info("DB>> delete() - drug_name: " + drug_name);
        
        String sql = "delete from NURSE_DEPOT ";
        sql += "where "; 
        sql += "DRUG_NAME = :drug_name ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("drug_name", drug_name);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(String drug_name) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(drug_name, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(NurseDepot nurseDepot, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from NURSE_DEPOT ";
        sql += "where ";
        
        if (nurseDepot.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (nurseDepot.getRemained() != null) { 
            sql += "REMAINED = :remained and ";
        }
        
        if (nurseDepot.getUnit() != null) { 
            sql += "UNIT = :unit and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (nurseDepot.getDrug_name() != null) {
                query.addParameter("drug_name", nurseDepot.getDrug_name());
            }
            
            if (nurseDepot.getRemained() != null) {
                query.addParameter("remained", nurseDepot.getRemained());
            }
            
            if (nurseDepot.getUnit() != null) {
                query.addParameter("unit", nurseDepot.getUnit());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(NurseDepot nurseDepot) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(nurseDepot, con);
            con.commit();
        }
    }
}
