/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.Payment;
import com.arc.repository.PaymentRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class PaymentRepositoryImpl implements PaymentRepository {
    private final static Logger logger = LoggerFactory.getLogger(PaymentRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "p.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DESCRIPTION")) {
            res += "p.DESCRIPTION, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("FEE")) {
            res += "p.FEE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "p.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("PAID")) {
            res += "p.PAID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "p.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "p.SICK_NAME, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public Payment findById(String id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + PaymentRepositoryImpl.getSelectBase(fields_to_ignore) + "from PAYMENTS p ";
        sql += "where "; 
        sql += "ID = :id ";
        
        Payment res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(Payment.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public Payment findById(String id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public Payment findById(String id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public Payment findById(String id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<Payment> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + PaymentRepositoryImpl.getSelectBase(fields_to_ignore) + "from PAYMENTS p ";
        
        List<Payment> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(Payment.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<Payment> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<Payment> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Payment> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<Payment> findByModel(Payment payment, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + PaymentRepositoryImpl.getSelectBase(fields_to_ignore) + "from PAYMENTS p ";
        sql += "where ";
        
        if (payment.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (payment.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (payment.getFee() != null) { 
            sql += "FEE = :fee and ";
        }
        
        if (payment.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (payment.getPaid() != null) { 
            sql += "PAID = :paid and ";
        }
        
        if (payment.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (payment.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<Payment> res;
        
        try (Query query = con.createQuery(sql)) {
            if (payment.getDate() != null) {
                query.addParameter("date", payment.getDate());
            }
            
            if (payment.getDescription() != null) {
                query.addParameter("description", payment.getDescription());
            }
            
            if (payment.getFee() != null) {
                query.addParameter("fee", payment.getFee());
            }
            
            if (payment.getId() != null) {
                query.addParameter("id", payment.getId());
            }
            
            if (payment.getPaid() != null) {
                query.addParameter("paid", payment.getPaid());
            }
            
            if (payment.getSick_id() != null) {
                query.addParameter("sick_id", payment.getSick_id());
            }
            
            if (payment.getSick_name() != null) {
                query.addParameter("sick_name", payment.getSick_name());
            }
            
            res = query.executeAndFetch(Payment.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<Payment> findByModel(Payment payment, Connection con) {
        return this.findByModel(payment, null, con);
    }
    
    @Override
    public List<Payment> findByModel(Payment payment, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(payment, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Payment> findByModel(Payment payment) {
        return this.findByModel(payment, (List<String>) null);
    }
    
    @Override
    public Payment insert(Payment payment, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into PAYMENTS ( " + 
                "DATE, " + 
                "DESCRIPTION, " + 
                "FEE, " + 
                "ID, " + 
                "PAID, " + 
                "SICK_ID, " + 
                "SICK_NAME " + 
            ") " + 
            "values (" +
                ":date, " + 
                ":description, " + 
                ":fee, " + 
                ":id, " + 
                ":paid, " + 
                ":sick_id, " + 
                ":sick_name " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(payment);

            key = query.executeUpdate().getKey();
        }
        
        final String res = Sql2oUtility.getInsertedId("PAYMENTS", "ID", con, key, String.class);
        payment.setId(res);
        logger.info("<< DB insert() - END");
        return payment;
    }
    
    @Override
    public Payment insert(Payment payment) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(payment, con);
            con.commit();
            return payment;
        }
    }
    
    @Override
    public Payment update(Payment payment, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + payment.getId());
        
        String sql = "update PAYMENTS set ";
        
        if (! exclude_nulls || payment.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || payment.getDescription() != null) { 
            sql += "DESCRIPTION = :description, ";
        }
        
        if (! exclude_nulls || payment.getFee() != null) { 
            sql += "FEE = :fee, ";
        }
        
        if (! exclude_nulls || payment.getPaid() != null) { 
            sql += "PAID = :paid, ";
        }
        
        if (! exclude_nulls || payment.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || payment.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || payment.getDate() != null) {
                query.addParameter("date", payment.getDate());
            }
            
            if (! exclude_nulls || payment.getDescription() != null) {
                query.addParameter("description", payment.getDescription());
            }
            
            if (! exclude_nulls || payment.getFee() != null) {
                query.addParameter("fee", payment.getFee());
            }
            
            if (! exclude_nulls || payment.getId() != null) {
                query.addParameter("id", payment.getId());
            }
            
            if (! exclude_nulls || payment.getPaid() != null) {
                query.addParameter("paid", payment.getPaid());
            }
            
            if (! exclude_nulls || payment.getSick_id() != null) {
                query.addParameter("sick_id", payment.getSick_id());
            }
            
            if (! exclude_nulls || payment.getSick_name() != null) {
                query.addParameter("sick_name", payment.getSick_name());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return payment;
    }
    
    @Override
    public Payment update(Payment payment, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(payment, exclude_nulls, con);
            con.commit();
            return payment;
        }
    }
    
    @Override
    public Payment save(Payment payment, Connection con) {
        final String id = payment.getId();

        final Payment payment2 = this.findById(id, null, con);
        
        if (payment2 == null) {
            return this.insert(payment, con);
        }
        return this.update(payment, false, con);
    }
    
    @Override
    public Payment save(Payment payment) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(payment, con);
            con.commit();
            return payment;
        }
    }
    
    @Override
    public void delete(String id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from PAYMENTS ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(String id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(Payment payment, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from PAYMENTS ";
        sql += "where ";
        
        if (payment.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (payment.getDescription() != null) { 
            sql += "DESCRIPTION = :description and ";
        }
        
        if (payment.getFee() != null) { 
            sql += "FEE = :fee and ";
        }
        
        if (payment.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (payment.getPaid() != null) { 
            sql += "PAID = :paid and ";
        }
        
        if (payment.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (payment.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (payment.getDate() != null) {
                query.addParameter("date", payment.getDate());
            }
            
            if (payment.getDescription() != null) {
                query.addParameter("description", payment.getDescription());
            }
            
            if (payment.getFee() != null) {
                query.addParameter("fee", payment.getFee());
            }
            
            if (payment.getId() != null) {
                query.addParameter("id", payment.getId());
            }
            
            if (payment.getPaid() != null) {
                query.addParameter("paid", payment.getPaid());
            }
            
            if (payment.getSick_id() != null) {
                query.addParameter("sick_id", payment.getSick_id());
            }
            
            if (payment.getSick_name() != null) {
                query.addParameter("sick_name", payment.getSick_name());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(Payment payment) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(payment, con);
            con.commit();
        }
    }
}
