/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.PsychologistReal;
import com.arc.repository.PsychologistRealRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class PsychologistRealRepositoryImpl implements PsychologistRealRepository {
    private final static Logger logger = LoggerFactory.getLogger(PsychologistRealRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COMMENTS")) {
            res += "p.COMMENTS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "p.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DOCTOR_NAME")) {
            res += "p.DOCTOR_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "p.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("NEXT_DATE")) {
            res += "p.NEXT_DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_ID")) {
            res += "p.SICK_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SICK_NAME")) {
            res += "p.SICK_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TREATMENT_DATE")) {
            res += "p.TREATMENT_DATE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public PsychologistReal findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + PsychologistRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from PSYCHOLOGIST_REAL p ";
        sql += "where "; 
        sql += "ID = :id ";
        
        PsychologistReal res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(PsychologistReal.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public PsychologistReal findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public PsychologistReal findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public PsychologistReal findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<PsychologistReal> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + PsychologistRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from PSYCHOLOGIST_REAL p ";
        
        List<PsychologistReal> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(PsychologistReal.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<PsychologistReal> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<PsychologistReal> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<PsychologistReal> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<PsychologistReal> findByModel(PsychologistReal psychologistReal, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + PsychologistRealRepositoryImpl.getSelectBase(fields_to_ignore) + "from PSYCHOLOGIST_REAL p ";
        sql += "where ";
        
        if (psychologistReal.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (psychologistReal.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (psychologistReal.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name and ";
        }
        
        if (psychologistReal.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (psychologistReal.getNext_date() != null) { 
            sql += "NEXT_DATE = :next_date and ";
        }
        
        if (psychologistReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (psychologistReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (psychologistReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<PsychologistReal> res;
        
        try (Query query = con.createQuery(sql)) {
            if (psychologistReal.getComments() != null) {
                query.addParameter("comments", psychologistReal.getComments());
            }
            
            if (psychologistReal.getDate() != null) {
                query.addParameter("date", psychologistReal.getDate());
            }
            
            if (psychologistReal.getDoctor_name() != null) {
                query.addParameter("doctor_name", psychologistReal.getDoctor_name());
            }
            
            if (psychologistReal.getId() != null) {
                query.addParameter("id", psychologistReal.getId());
            }
            
            if (psychologistReal.getNext_date() != null) {
                query.addParameter("next_date", psychologistReal.getNext_date());
            }
            
            if (psychologistReal.getSick_id() != null) {
                query.addParameter("sick_id", psychologistReal.getSick_id());
            }
            
            if (psychologistReal.getSick_name() != null) {
                query.addParameter("sick_name", psychologistReal.getSick_name());
            }
            
            if (psychologistReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", psychologistReal.getTreatment_date());
            }
            
            res = query.executeAndFetch(PsychologistReal.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<PsychologistReal> findByModel(PsychologistReal psychologistReal, Connection con) {
        return this.findByModel(psychologistReal, null, con);
    }
    
    @Override
    public List<PsychologistReal> findByModel(PsychologistReal psychologistReal, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(psychologistReal, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<PsychologistReal> findByModel(PsychologistReal psychologistReal) {
        return this.findByModel(psychologistReal, (List<String>) null);
    }
    
    @Override
    public PsychologistReal insert(PsychologistReal psychologistReal, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into PSYCHOLOGIST_REAL ( " + 
                "COMMENTS, " + 
                "DATE, " + 
                "DOCTOR_NAME, " + 
                "ID, " + 
                "NEXT_DATE, " + 
                "SICK_ID, " + 
                "SICK_NAME, " + 
                "TREATMENT_DATE " + 
            ") " + 
            "values (" +
                ":comments, " + 
                ":date, " + 
                ":doctor_name, " + 
                ":id, " + 
                ":next_date, " + 
                ":sick_id, " + 
                ":sick_name, " + 
                ":treatment_date " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(psychologistReal);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("PSYCHOLOGIST_REAL", "ID", con, key, Long.class);
        psychologistReal.setId(res);
        logger.info("<< DB insert() - END");
        return psychologistReal;
    }
    
    @Override
    public PsychologistReal insert(PsychologistReal psychologistReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(psychologistReal, con);
            con.commit();
            return psychologistReal;
        }
    }
    
    @Override
    public PsychologistReal update(PsychologistReal psychologistReal, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + psychologistReal.getId());
        
        String sql = "update PSYCHOLOGIST_REAL set ";
        
        if (! exclude_nulls || psychologistReal.getComments() != null) { 
            sql += "COMMENTS = :comments, ";
        }
        
        if (! exclude_nulls || psychologistReal.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || psychologistReal.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name, ";
        }
        
        if (! exclude_nulls || psychologistReal.getNext_date() != null) { 
            sql += "NEXT_DATE = :next_date, ";
        }
        
        if (! exclude_nulls || psychologistReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id, ";
        }
        
        if (! exclude_nulls || psychologistReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name, ";
        }
        
        if (! exclude_nulls || psychologistReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || psychologistReal.getComments() != null) {
                query.addParameter("comments", psychologistReal.getComments());
            }
            
            if (! exclude_nulls || psychologistReal.getDate() != null) {
                query.addParameter("date", psychologistReal.getDate());
            }
            
            if (! exclude_nulls || psychologistReal.getDoctor_name() != null) {
                query.addParameter("doctor_name", psychologistReal.getDoctor_name());
            }
            
            if (! exclude_nulls || psychologistReal.getId() != null) {
                query.addParameter("id", psychologistReal.getId());
            }
            
            if (! exclude_nulls || psychologistReal.getNext_date() != null) {
                query.addParameter("next_date", psychologistReal.getNext_date());
            }
            
            if (! exclude_nulls || psychologistReal.getSick_id() != null) {
                query.addParameter("sick_id", psychologistReal.getSick_id());
            }
            
            if (! exclude_nulls || psychologistReal.getSick_name() != null) {
                query.addParameter("sick_name", psychologistReal.getSick_name());
            }
            
            if (! exclude_nulls || psychologistReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", psychologistReal.getTreatment_date());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return psychologistReal;
    }
    
    @Override
    public PsychologistReal update(PsychologistReal psychologistReal, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(psychologistReal, exclude_nulls, con);
            con.commit();
            return psychologistReal;
        }
    }
    
    @Override
    public PsychologistReal save(PsychologistReal psychologistReal, Connection con) {
        final Long id = psychologistReal.getId();

        final PsychologistReal psychologistReal2 = this.findById(id, null, con);
        
        if (psychologistReal2 == null) {
            return this.insert(psychologistReal, con);
        }
        return this.update(psychologistReal, false, con);
    }
    
    @Override
    public PsychologistReal save(PsychologistReal psychologistReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(psychologistReal, con);
            con.commit();
            return psychologistReal;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from PSYCHOLOGIST_REAL ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(PsychologistReal psychologistReal, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from PSYCHOLOGIST_REAL ";
        sql += "where ";
        
        if (psychologistReal.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (psychologistReal.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (psychologistReal.getDoctor_name() != null) { 
            sql += "DOCTOR_NAME = :doctor_name and ";
        }
        
        if (psychologistReal.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (psychologistReal.getNext_date() != null) { 
            sql += "NEXT_DATE = :next_date and ";
        }
        
        if (psychologistReal.getSick_id() != null) { 
            sql += "SICK_ID = :sick_id and ";
        }
        
        if (psychologistReal.getSick_name() != null) { 
            sql += "SICK_NAME = :sick_name and ";
        }
        
        if (psychologistReal.getTreatment_date() != null) { 
            sql += "TREATMENT_DATE = :treatment_date and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (psychologistReal.getComments() != null) {
                query.addParameter("comments", psychologistReal.getComments());
            }
            
            if (psychologistReal.getDate() != null) {
                query.addParameter("date", psychologistReal.getDate());
            }
            
            if (psychologistReal.getDoctor_name() != null) {
                query.addParameter("doctor_name", psychologistReal.getDoctor_name());
            }
            
            if (psychologistReal.getId() != null) {
                query.addParameter("id", psychologistReal.getId());
            }
            
            if (psychologistReal.getNext_date() != null) {
                query.addParameter("next_date", psychologistReal.getNext_date());
            }
            
            if (psychologistReal.getSick_id() != null) {
                query.addParameter("sick_id", psychologistReal.getSick_id());
            }
            
            if (psychologistReal.getSick_name() != null) {
                query.addParameter("sick_name", psychologistReal.getSick_name());
            }
            
            if (psychologistReal.getTreatment_date() != null) {
                query.addParameter("treatment_date", psychologistReal.getTreatment_date());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(PsychologistReal psychologistReal) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(psychologistReal, con);
            con.commit();
        }
    }
}
