/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.repository.imp;

import java.util.List;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

import com.arc.model.Receipts;
import com.arc.repository.ReceiptsRepository;
import com.arc.utility.Sql2oUtility;


@Repository
public class ReceiptsRepositoryImpl implements ReceiptsRepository {
    private final static Logger logger = LoggerFactory.getLogger(ReceiptsRepository.class);
    
    @Autowired
    private Sql2o sql2o;
    
    private static String getSelectBase(List<String> fields_to_ignore) {
        String res = "";
        
        if (fields_to_ignore != null) {
            fields_to_ignore = fields_to_ignore
                .stream()
                .map(field -> field.toUpperCase())
                .collect(Collectors.toList());
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COMMENTS")) {
            res += "r.COMMENTS, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("COUNT")) {
            res += "r.COUNT, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DATE")) {
            res += "r.DATE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("DRUG_NAME")) {
            res += "r.DRUG_NAME, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("FEE")) {
            res += "r.FEE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("ID")) {
            res += "r.ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("RECEIPT_ID")) {
            res += "r.RECEIPT_ID, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("SELL_PRICE")) {
            res += "r.SELL_PRICE, ";
        }
        
        if (fields_to_ignore == null || ! fields_to_ignore.contains("TOTAL_FEE")) {
            res += "r.TOTAL_FEE, ";
        }
        
        res = res.substring(0, res.length() - 2) + " ";
        
        return res;
    }
    
    @Override
    public Receipts findById(Long id, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findById() - id: " + id);
        
        String sql = "select " + ReceiptsRepositoryImpl.getSelectBase(fields_to_ignore) + "from RECEIPTS r ";
        sql += "where "; 
        sql += "ID = :id ";
        
        Receipts res;
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            res = query.executeAndFetchFirst(Receipts.class);
        }
        
        logger.debug("<< DB getById() - END");
        return res;
    }
    
    @Override
    public Receipts findById(Long id, Connection con) {
        return this.findById(id, null, con);
    }
    
    @Override
    public Receipts findById(Long id, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findById(id, fields_to_ignore, con);
        }
    }
    
    @Override
    public Receipts findById(Long id) {
        return this.findById(id, (List<String>) null);
    }
    
    @Override
    public List<Receipts> findAll(List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findAll()");
        
        final String sql = "select " + ReceiptsRepositoryImpl.getSelectBase(fields_to_ignore) + "from RECEIPTS r ";
        
        List<Receipts> res;
        
        try (Query query = con.createQuery(sql)) {
            res = query.executeAndFetch(Receipts.class);
        }
        
        logger.debug("<< DB findAll() - END");
        return res;
    }
    
    @Override
    public List<Receipts> findAll(Connection con) {
        return this.findAll(null, con);
    }
    
    @Override
    public List<Receipts> findAll(List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findAll(fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Receipts> findAll() {
        return this.findAll((List<String>) null);
    }
    
    @Override
    public List<Receipts> findByModel(Receipts receipts, List<String> fields_to_ignore, Connection con) {
        logger.debug("DB>> findByModel()");
        
        String sql = "select " + ReceiptsRepositoryImpl.getSelectBase(fields_to_ignore) + "from RECEIPTS r ";
        sql += "where ";
        
        if (receipts.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (receipts.getCount() != null) { 
            sql += "COUNT = :count and ";
        }
        
        if (receipts.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (receipts.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (receipts.getFee() != null) { 
            sql += "FEE = :fee and ";
        }
        
        if (receipts.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (receipts.getReceipt_id() != null) { 
            sql += "RECEIPT_ID = :receipt_id and ";
        }
        
        if (receipts.getSell_price() != null) { 
            sql += "SELL_PRICE = :sell_price and ";
        }
        
        if (receipts.getTotal_fee() != null) { 
            sql += "TOTAL_FEE = :total_fee and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        List<Receipts> res;
        
        try (Query query = con.createQuery(sql)) {
            if (receipts.getComments() != null) {
                query.addParameter("comments", receipts.getComments());
            }
            
            if (receipts.getCount() != null) {
                query.addParameter("count", receipts.getCount());
            }
            
            if (receipts.getDate() != null) {
                query.addParameter("date", receipts.getDate());
            }
            
            if (receipts.getDrug_name() != null) {
                query.addParameter("drug_name", receipts.getDrug_name());
            }
            
            if (receipts.getFee() != null) {
                query.addParameter("fee", receipts.getFee());
            }
            
            if (receipts.getId() != null) {
                query.addParameter("id", receipts.getId());
            }
            
            if (receipts.getReceipt_id() != null) {
                query.addParameter("receipt_id", receipts.getReceipt_id());
            }
            
            if (receipts.getSell_price() != null) {
                query.addParameter("sell_price", receipts.getSell_price());
            }
            
            if (receipts.getTotal_fee() != null) {
                query.addParameter("total_fee", receipts.getTotal_fee());
            }
            
            res = query.executeAndFetch(Receipts.class);
        }
        
        logger.debug("<< DB findByModel() - END");
        return res;
    }
    
    @Override
    public List<Receipts> findByModel(Receipts receipts, Connection con) {
        return this.findByModel(receipts, null, con);
    }
    
    @Override
    public List<Receipts> findByModel(Receipts receipts, List<String> fields_to_ignore) {
        try (Connection con = this.sql2o.open()) {
            return this.findByModel(receipts, fields_to_ignore, con);
        }
    }
    
    @Override
    public List<Receipts> findByModel(Receipts receipts) {
        return this.findByModel(receipts, (List<String>) null);
    }
    
    @Override
    public Receipts insert(Receipts receipts, Connection con) {
        logger.info("DB>> insert()");
        
        final String sql = (
            "insert into RECEIPTS ( " + 
                "COMMENTS, " + 
                "COUNT, " + 
                "DATE, " + 
                "DRUG_NAME, " + 
                "FEE, " + 
                "ID, " + 
                "RECEIPT_ID, " + 
                "SELL_PRICE, " + 
                "TOTAL_FEE " + 
            ") " + 
            "values (" +
                ":comments, " + 
                ":count, " + 
                ":date, " + 
                ":drug_name, " + 
                ":fee, " + 
                ":id, " + 
                ":receipt_id, " + 
                ":sell_price, " + 
                ":total_fee " + 
            ")"
        );
        
        Object key;
        
        try (Query query = con.createQuery(sql, true)) {
            query.bind(receipts);

            key = query.executeUpdate().getKey();
        }
        
        final Long res = Sql2oUtility.getInsertedId("RECEIPTS", "ID", con, key, Long.class);
        receipts.setId(res);
        logger.info("<< DB insert() - END");
        return receipts;
    }
    
    @Override
    public Receipts insert(Receipts receipts) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.insert(receipts, con);
            con.commit();
            return receipts;
        }
    }
    
    @Override
    public Receipts update(Receipts receipts, boolean exclude_nulls, Connection con) {
        logger.info("DB>> update() - id: " + receipts.getId());
        
        String sql = "update RECEIPTS set ";
        
        if (! exclude_nulls || receipts.getComments() != null) { 
            sql += "COMMENTS = :comments, ";
        }
        
        if (! exclude_nulls || receipts.getCount() != null) { 
            sql += "COUNT = :count, ";
        }
        
        if (! exclude_nulls || receipts.getDate() != null) { 
            sql += "DATE = :date, ";
        }
        
        if (! exclude_nulls || receipts.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name, ";
        }
        
        if (! exclude_nulls || receipts.getFee() != null) { 
            sql += "FEE = :fee, ";
        }
        
        if (! exclude_nulls || receipts.getReceipt_id() != null) { 
            sql += "RECEIPT_ID = :receipt_id, ";
        }
        
        if (! exclude_nulls || receipts.getSell_price() != null) { 
            sql += "SELL_PRICE = :sell_price, ";
        }
        
        if (! exclude_nulls || receipts.getTotal_fee() != null) { 
            sql += "TOTAL_FEE = :total_fee, ";
        }
        
        sql = sql.substring(0, sql.length() - 2) + " ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            if (! exclude_nulls || receipts.getComments() != null) {
                query.addParameter("comments", receipts.getComments());
            }
            
            if (! exclude_nulls || receipts.getCount() != null) {
                query.addParameter("count", receipts.getCount());
            }
            
            if (! exclude_nulls || receipts.getDate() != null) {
                query.addParameter("date", receipts.getDate());
            }
            
            if (! exclude_nulls || receipts.getDrug_name() != null) {
                query.addParameter("drug_name", receipts.getDrug_name());
            }
            
            if (! exclude_nulls || receipts.getFee() != null) {
                query.addParameter("fee", receipts.getFee());
            }
            
            if (! exclude_nulls || receipts.getId() != null) {
                query.addParameter("id", receipts.getId());
            }
            
            if (! exclude_nulls || receipts.getReceipt_id() != null) {
                query.addParameter("receipt_id", receipts.getReceipt_id());
            }
            
            if (! exclude_nulls || receipts.getSell_price() != null) {
                query.addParameter("sell_price", receipts.getSell_price());
            }
            
            if (! exclude_nulls || receipts.getTotal_fee() != null) {
                query.addParameter("total_fee", receipts.getTotal_fee());
            }
            

            query.executeUpdate();
        }
        
        logger.info("<< DB update() - END");
        return receipts;
    }
    
    @Override
    public Receipts update(Receipts receipts, boolean exclude_nulls) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.update(receipts, exclude_nulls, con);
            con.commit();
            return receipts;
        }
    }
    
    @Override
    public Receipts save(Receipts receipts, Connection con) {
        final Long id = receipts.getId();

        final Receipts receipts2 = this.findById(id, null, con);
        
        if (receipts2 == null) {
            return this.insert(receipts, con);
        }
        return this.update(receipts, false, con);
    }
    
    @Override
    public Receipts save(Receipts receipts) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.save(receipts, con);
            con.commit();
            return receipts;
        }
    }
    
    @Override
    public void delete(Long id, Connection con) {
        logger.info("DB>> delete() - id: " + id);
        
        String sql = "delete from RECEIPTS ";
        sql += "where "; 
        sql += "ID = :id ";
        
        try (Query query = con.createQuery(sql)) {
            query.addParameter("id", id);

            query.executeUpdate();
        }
        
        logger.info("<< DB delete() - END");
    }
    
    @Override
    public void delete(Long id) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.delete(id, con);
            con.commit();
        }
    }
    
    @Override
    public void deleteByModel(Receipts receipts, Connection con) {
        logger.info("DB>> deleteByModel()");
        
        String sql = "delete from RECEIPTS ";
        sql += "where ";
        
        if (receipts.getComments() != null) { 
            sql += "COMMENTS = :comments and ";
        }
        
        if (receipts.getCount() != null) { 
            sql += "COUNT = :count and ";
        }
        
        if (receipts.getDate() != null) { 
            sql += "DATE = :date and ";
        }
        
        if (receipts.getDrug_name() != null) { 
            sql += "DRUG_NAME = :drug_name and ";
        }
        
        if (receipts.getFee() != null) { 
            sql += "FEE = :fee and ";
        }
        
        if (receipts.getId() != null) { 
            sql += "ID = :id and ";
        }
        
        if (receipts.getReceipt_id() != null) { 
            sql += "RECEIPT_ID = :receipt_id and ";
        }
        
        if (receipts.getSell_price() != null) { 
            sql += "SELL_PRICE = :sell_price and ";
        }
        
        if (receipts.getTotal_fee() != null) { 
            sql += "TOTAL_FEE = :total_fee and ";
        }
        
        sql = sql.substring(0, sql.length() - 4);
        
        try (Query query = con.createQuery(sql)) {
            if (receipts.getComments() != null) {
                query.addParameter("comments", receipts.getComments());
            }
            
            if (receipts.getCount() != null) {
                query.addParameter("count", receipts.getCount());
            }
            
            if (receipts.getDate() != null) {
                query.addParameter("date", receipts.getDate());
            }
            
            if (receipts.getDrug_name() != null) {
                query.addParameter("drug_name", receipts.getDrug_name());
            }
            
            if (receipts.getFee() != null) {
                query.addParameter("fee", receipts.getFee());
            }
            
            if (receipts.getId() != null) {
                query.addParameter("id", receipts.getId());
            }
            
            if (receipts.getReceipt_id() != null) {
                query.addParameter("receipt_id", receipts.getReceipt_id());
            }
            
            if (receipts.getSell_price() != null) {
                query.addParameter("sell_price", receipts.getSell_price());
            }
            
            if (receipts.getTotal_fee() != null) {
                query.addParameter("total_fee", receipts.getTotal_fee());
            }
            
            query.executeUpdate();
        }
        
        logger.info("<< DB deleteByModel() - END");
    }
    
    @Override
    public void deleteByModel(Receipts receipts) {
        try (Connection con = this.sql2o.beginTransaction()) {
            this.deleteByModel(receipts, con);
            con.commit();
        }
    }
}
