/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.service;

import java.util.List;

import org.sql2o.Connection;

import com.arc.aggregator.ReceiptsRealAggregator;
import com.arc.model.ReceiptsReal;


public interface ReceiptsRealService {
    ReceiptsRealAggregator findById(Long id, List<String> fields_to_ignore, Connection con);
    
    ReceiptsRealAggregator findById(Long id, Connection con);
    
    ReceiptsRealAggregator findById(Long id, List<String> fields_to_ignore);
    
    ReceiptsRealAggregator findById(Long id);
    
    ReceiptsReal insert(ReceiptsReal receiptsReal, Connection con);
    
    ReceiptsReal insert(ReceiptsReal receiptsReal);
    
    ReceiptsReal update(ReceiptsReal receiptsReal, boolean exclude_nulls, Connection con);
    
    ReceiptsReal update(ReceiptsReal receiptsReal, boolean exclude_nulls);
    
    ReceiptsReal save(ReceiptsReal receiptsReal, Connection con);
    
    ReceiptsReal save(ReceiptsReal receiptsReal);
    
    List<ReceiptsRealAggregator> findAll(List<String> fields_to_ignore, Connection con);
    
    List<ReceiptsRealAggregator> findAll(Connection con);
    
    List<ReceiptsRealAggregator> findAll(List<String> fields_to_ignore);
    
    List<ReceiptsRealAggregator> findAll();
    
    List<ReceiptsRealAggregator> findByModel(ReceiptsReal receiptsReal, List<String> fields_to_ignore, Connection con);
    
    List<ReceiptsRealAggregator> findByModel(ReceiptsReal receiptsReal, Connection con);
    
    List<ReceiptsRealAggregator> findByModel(ReceiptsReal receiptsReal, List<String> fields_to_ignore);
    
    List<ReceiptsRealAggregator> findByModel(ReceiptsReal receiptsReal);
    
    void delete(Long id, Connection con);
    
    void delete(Long id);
    
    void deleteByModel(ReceiptsReal receiptsReal, Connection con);
    
    void deleteByModel(ReceiptsReal receiptsReal);
}
