/**
 * This file was firstly auto-generated by EWA: 
 * https://marco-sulla.github.io/ewa/
 */

package com.arc.aggregator;

import com.arc.model.Tracking;


public class TrackingAggregator {
    private Tracking tracking;
    
    public Tracking getTracking() {
        return this.tracking;
    }
    
    public void setTracking(Tracking tracking) {
        this.tracking = tracking;
    }
}
